export const PROMPT_SET_ID='school-calendar-design@0.4.0';

export const COMMON_PROMPT=`Create a coherent, premium print-design asset for a Korean calendar template. This is a decorative asset, not a finished calendar page. Keep one consistent visual language across the set: palette, shape family, line weight, texture, whitespace, and frame language. Vary seasonal color and motifs between months without repeating one background. Respect every protected editable-object region. Keep important decoration inside the safe margin while allowing background color through bleed. Never rasterize editable content. Absolutely no readable letters, words, numbers, dates, calendar grids, school names, addresses, contacts, logos, emblems, watermarks, UI, or fake text.`;

export const ROLE_PROMPTS=Object.freeze({
 cover:{label:'표지',purpose:'Establish the visual identity of the complete calendar set.',generate:['printable background','edge pattern','decorative motifs','empty photo-frame treatment'],reserve:['editable year and title','school photo','school logo and name','address and contact'],prompt:'Make the year/title area the first visual focus and the school-photo area second. Keep the school logo and contact areas quiet and clearly separated. Place decoration at corners, edges, or between protected regions. Never invent or embed a school photo, building, person, logo, or emblem.'},
 annual:{label:'연력',purpose:'Support a readable twelve-month annual overview.',generate:['quiet annual background','thin frame','corner decoration','subtle pattern'],reserve:['editable year','complete twelve-month calendar','holiday information'],prompt:'Keep a large clean central field for the twelve-month calendar and a separate header field for the year. Use lower decoration density than the cover. Avoid photographs, strong contrast, or patterns behind calendar content.'},
 'school-symbols':{label:'학교 상징',purpose:'Organize school identity and information as a refined editorial page.',generate:['section frames','dividers','quiet background','small supporting motifs'],reserve:['school logo','school name','motto','school song','school tree','school flower','descriptions'],prompt:'Create clearly separated editable information zones using whitespace, frames, or dividers. Leave image slots empty. Do not invent any school identity, symbol, song, logo, or written content.'},
 month:{label:'월력',purpose:'Frame one readable monthly calendar while expressing its season.',generate:['monthly background tone','month accent','seasonal edge illustration','grid-edge pattern'],reserve:['editable month and year','weekday row','full date grid','school events','mini calendars','school logo and slogan'],prompt:'Keep the complete calendar grid area bright, calm, and unobstructed. Place seasonal illustration around the title, corners, header, or outside the grid. Ensure multi-line school events remain legible. Do not draw a calendar, date, weekday, event, mini calendar, or title.'},
 'month-back':{label:'월력 뒷면',purpose:'Support a flexible composition of images, calendars, planners, and notes.',generate:['independent monthly illustration','supporting background','frame decoration','section dividers'],reserve:['every selected month-back component and its coordinates'],prompt:'Respect the supplied component list and protected regions. Keep image frames, current calendar, adjacent mini calendars, goals, checklist, weekly planner, memo, and date strip as separate editable objects. Do not fill an image frame with an invented photo. The editor may add, remove, duplicate, resize, or move components.'},
 'back-cover':{label:'뒷표지',purpose:'Close the design set with a quiet continuation of the cover.',generate:['closing background','brand pattern','information frame','restrained decoration'],reserve:['school name','school logo','address','phone and fax','website'],prompt:'Use the cover palette and motif language with lower visual intensity. Reserve one bright, orderly information area. Do not invent school information, contact details, or logos.'}
});

export const ROLE_DIRECTIONS=Object.freeze({
 cover:['centered-photo','asymmetric-photo'],annual:['open-grid','header-band'],'school-symbols':['editorial-cards','heritage-panels'],month:['seasonal-corner','header-accent'],'month-back':['image-calendar','planner-collage'],'back-cover':['quiet-information','closing-motif']
});

const STYLE_NAMES={balanced:'clean balanced editorial',seasonal:'connected seasonal illustration',photo:'photo-led brand framing',playful:'student-friendly graphic accents'};
const LEVEL_NAMES={all:'general audience',elementary:'elementary school',middle:'middle school',high:'high school'};
const DENSITY_NAMES={low:'restrained',medium:'moderate',high:'rich but never over protected information'};

export function buildPrompt(input){const role=ROLE_PROMPTS[input.pageRole];if(!role)throw new Error(`Unknown page role: ${input.pageRole}`);const colors=input.palette?.length?input.palette.join(', '):'calm print-appropriate colors',month=input.month?` Target month: ${input.month.year}-${String(input.month.month).padStart(2,'0')}; season: ${input.month.season||'unspecified'}; monthly accent: ${input.month.accentColor||'derive from palette'}.`:'';return `${COMMON_PROMPT} Page role: ${role.label}. Purpose: ${role.purpose} Style: ${STYLE_NAMES[input.styleKey]||STYLE_NAMES.balanced}. Audience: ${LEVEL_NAMES[input.schoolLevel]||LEVEL_NAMES.all}. Decoration density: ${DENSITY_NAMES[input.decorationDensity]||DENSITY_NAMES.medium}. Palette: ${colors}. Composition direction: ${input.variantDirection}. Generate only: ${role.generate.join(', ')}. Reserve clean areas for: ${role.reserve.join(', ')}. ${role.prompt}${month} ${input.protectedRegions?.length?`Protected editable regions: ${input.protectedRegions.map(item=>`${item.role}(${item.x},${item.y},${item.width},${item.height})`).join('; ')}.`:''} ${input.monthBackComponents?.length?`Selected month-back components: ${input.monthBackComponents.join(', ')}.`:''} ${input.instruction||''}`.replace(/\s+/g,' ').trim()}

