export const PROMPT_SET_ID='school-calendar-design@0.5.0';

export const COMMON_PROMPT=`Create a coherent, premium print-design asset for a Korean calendar template. This is a decorative asset, not a finished calendar page. Keep one consistent visual language across the set: palette, shape family, line weight, texture, whitespace, and frame language. Vary seasonal color and motifs between months without repeating one background. Respect every protected editable-object region. Keep important decoration inside the safe margin while allowing background color through bleed. Never rasterize editable content. Absolutely no readable letters, words, numbers, dates, calendar grids, school names, addresses, contacts, logos, emblems, watermarks, UI, or fake text.`;

export const ROLE_PROMPTS=Object.freeze({
 cover:{label:'표지',purpose:'Establish the visual identity of the complete calendar set.',generate:['printable background','edge pattern','decorative motifs','empty photo-frame treatment'],reserve:['editable year and title','school photo','school logo and name','address and contact'],prompt:'Make the year/title area the first visual focus and the school-photo area second. Keep the school logo and contact areas quiet and clearly separated. Place decoration at corners, edges, or between protected regions. Never invent or embed a school photo, building, person, logo, or emblem.'},
 annual:{label:'연력',purpose:'Support a readable twelve-month annual overview.',generate:['quiet annual background','thin frame','corner decoration','subtle pattern'],reserve:['editable year','complete twelve-month calendar','holiday information'],prompt:'Keep a large clean central field for the twelve-month calendar and a separate header field for the year. Use lower decoration density than the cover. Avoid photographs, strong contrast, or patterns behind calendar content.'},
 'school-symbols':{label:'학교 상징',purpose:'Organize school identity and information as a refined editorial page.',generate:['section frames','dividers','quiet background','small supporting motifs'],reserve:['school logo','school name','motto','school song','school tree','school flower','descriptions'],prompt:'Create clearly separated editable information zones using whitespace, frames, or dividers. Leave image slots empty. Do not invent any school identity, symbol, song, logo, or written content.'},
 month:{label:'월력',purpose:'Frame one readable monthly calendar while expressing its season.',generate:['monthly background tone','month accent','seasonal edge illustration','grid-edge pattern'],reserve:['editable month and year','weekday row','full date grid','school events','mini calendars','school logo and slogan'],prompt:'Keep the complete calendar grid area bright, calm, and unobstructed. Place seasonal illustration around the title, corners, header, or outside the grid. Ensure multi-line school events remain legible. Do not draw a calendar, date, weekday, event, mini calendar, or title.'},
 'month-back':{label:'월력 뒷면',purpose:'Support a flexible composition of images, calendars, planners, and notes.',generate:['independent monthly illustration','supporting background','frame decoration','section dividers'],reserve:['every selected month-back component and its coordinates'],prompt:'Respect the supplied component list and protected regions. Keep image frames, current calendar, adjacent mini calendars, goals, checklist, weekly planner, memo, and date strip as separate editable objects. Do not fill an image frame with an invented photo. The editor may add, remove, duplicate, resize, or move components.'},
 'back-cover':{label:'뒷표지',purpose:'Close the design set with a quiet continuation of the cover.',generate:['closing background','brand pattern','information frame','restrained decoration'],reserve:['school name','school logo','address','phone and fax','website'],prompt:'Use the cover palette and motif language with lower visual intensity. Reserve one bright, orderly information area. Do not invent school information, contact details, or logos.'}
});

export const ROLE_DIRECTIONS=Object.freeze({cover:['centered-photo','asymmetric-photo'],annual:['open-grid','header-band'],'school-symbols':['editorial-cards','heritage-panels'],month:['seasonal-corner','header-accent'],'month-back':['image-calendar','planner-collage'],'back-cover':['quiet-information','closing-motif']});

const STYLE_NAMES={balanced:'clean balanced editorial',seasonal:'connected seasonal illustration',photo:'photo-led brand framing',playful:'student-friendly graphic accents'};
const DESIGN_STYLE_NAMES={editorial:'disciplined editorial with fine rules and generous whitespace','seasonal-watercolor':'seasonal watercolor with soft natural transitions',geometry:'modern geometry with decisive planes and brand-color rhythm','photo-story':'photo-story framing with quiet documentary details','student-playful':'student-friendly graphic language with rounded educational motifs','premium-minimal':'premium minimal typography with restrained material texture'};
const LEVEL_NAMES={all:'general audience',elementary:'elementary school',middle:'middle school',high:'high school'};
const DENSITY_NAMES={low:'restrained',medium:'moderate',high:'rich but never over protected information'};
const PAGE_TYPE_GUIDANCE={
 cover:{'large-photo':'one dominant photo opening with a calm lower information zone','photo-collage':'several clearly separated empty photo openings','typography':'a large quiet title field with small supporting image space',illustration:'one dominant decorative illustration field beside protected content',split:'a strong image and information split'},
 annual:{'balanced-4x3':'a centered 4 by 3 annual grid field','open-grid':'a wide low-density annual grid with generous margins','header-band':'a distinct full-width year header band above the annual grid','split-info':'a large annual grid beside a separate information column'},
 'school-symbols':{'editorial-cards':'independent editorial cards for each school symbol','section-panels':'clear vertical and horizontal information panels','heritage-document':'a formal centered document composition with subtle heritage cues','symbol-photo':'a dominant empty symbol-image field beside text panels'},
 month:{'calendar-led':'a dominant unobstructed calendar field','large-month-number':'a tall protected month-title zone above the grid','top-image-band':'an empty decorative image band above the calendar','split-calendar-image':'a vertical image field beside the calendar grid','open-editorial':'a compact centered calendar with generous editorial whitespace'},
 'month-back':{'image-calendar':'a large empty image field beside one editable calendar','large-image':'a dominant landscape image field above compact information','photo-collage':'a modular empty photo collage beside calendar information',planner:'a dominant planner field with compact image and calendar zones','memo-calendar':'a large memo field paired with calendar information'},
 'back-cover':{'school-info':'a structured school-information panel beside a closing image','cover-continuation':'a quieter continuation of the cover image and motif split','photo-closing':'one wide closing photo opening above school information','minimal-brand':'a sparse brand mark and information composition'}
};

export function buildPrompt(input){const role=ROLE_PROMPTS[input.pageRole];if(!role)throw new Error(`Unknown page role: ${input.pageRole}`);const colors=input.palette?.length?input.palette.join(', '):'calm print-appropriate colors',month=input.month?` Target month: ${input.month.year}-${String(input.month.month).padStart(2,'0')}; season: ${input.month.season||'unspecified'}; monthly accent: ${input.month.accentColor||'derive from palette'}.`:'',spec=input.designSpec||{},typeId=spec.pageTypeId,typeGuide=PAGE_TYPE_GUIDANCE[input.pageRole]?.[typeId],designStyle=DESIGN_STYLE_NAMES[spec.styleId],expression=spec.expression?` Design expression: decoration ${spec.expression.decoration}; photo mode ${spec.expression.photoMode}; seasonal variation ${spec.expression.seasonal}; information density ${spec.expression.density}.`:'';return `${COMMON_PROMPT} Page role: ${role.label}. Purpose: ${role.purpose} Style: ${designStyle||STYLE_NAMES[input.styleKey]||STYLE_NAMES.balanced}. ${typeGuide?`Selected editable composition: ${typeId}, meaning ${typeGuide}. Build decoration around this composition and do not replace it.`:''}${expression} Audience: ${LEVEL_NAMES[input.schoolLevel]||LEVEL_NAMES.all}. Decoration density: ${DENSITY_NAMES[input.decorationDensity]||DENSITY_NAMES.medium}. Palette: ${colors}. Composition direction: ${input.variantDirection}. Generate only: ${role.generate.join(', ')}. Reserve clean areas for: ${role.reserve.join(', ')}. ${role.prompt}${month} ${input.protectedRegions?.length?`Protected editable regions: ${input.protectedRegions.map(item=>`${item.role}(${item.x},${item.y},${item.width},${item.height})`).join('; ')}.`:''} ${spec.protectedContent?.length?`Protected content contract: ${spec.protectedContent.join(', ')}.`:''} ${input.monthBackComponents?.length?`Selected month-back components: ${input.monthBackComponents.join(', ')}.`:''} ${input.instruction||''}`.replace(/\s+/g,' ').trim()}
