export const PROMPT_SET_ID='school-calendar-design@0.7.1';

export const COMMON_PROMPT=`Create a quiet, premium background-and-edge-decoration asset for a Korean calendar template. This is not a page layout and not a finished calendar page. A professional designer will place every functional object separately. Generate only paper color or texture plus sparse edge or corner motifs. Keep the central content field open and calm. Never draw, imitate, outline, shadow, or reserve visible boxes for editable objects. Never create photo frames, cards, panels, dividers, tables, planner sections, memo lines, checklists, calendar cells, title bands, labels, or UI-like geometry. Do not draw spiral binding, punched holes, perforations, dotted loops, crop marks, registration marks, or any repeated production-like motif along an edge. Respect every protected editable-object region and keep those regions visually empty. Keep one consistent visual language across the set while following the requested monthly rhythm. Never rasterize editable content. Absolutely no readable letters, words, numbers, dates, calendar grids, school names, addresses, contacts, logos, emblems, watermarks, UI, or fake text.`;

export const ROLE_PROMPTS=Object.freeze({
 cover:{label:'표지',purpose:'Establish a restrained visual identity behind editable cover objects.',generate:['printable paper background','sparse edge motif','one restrained corner accent'],reserve:['editable year and title','school photo','school logo and name','address and contact'],prompt:'Keep the photo and information regions completely plain. Never invent or embed a school photo, building, person, logo, emblem, frame, or panel.'},
 annual:{label:'연력',purpose:'Provide a quiet surface behind a readable twelve-month overview.',generate:['quiet paper background','very sparse corner decoration'],reserve:['editable year','complete twelve-month calendar','holiday information'],prompt:'Keep almost the entire page plain. Do not create a border, frame, grid, header band, column, or information panel. Use lower decoration density than the cover.'},
 'school-symbols':{label:'학교 상징',purpose:'Provide a calm background behind independently editable school identity objects.',generate:['quiet paper background','small edge motifs'],reserve:['school logo','school name','motto','school song','school tree','school flower','descriptions'],prompt:'Do not divide the page into visible zones. Do not create cards, panels, frames, dividers, image slots, or invented school identity content.'},
 month:{label:'월력',purpose:'Provide a subtle seasonal background without depicting the calendar structure.',generate:['monthly paper tone','one sparse seasonal corner or edge motif'],reserve:['editable month and year','weekday row','full date grid','school events','mini calendars','school logo and slogan'],prompt:'Keep at least eighty-five percent of the surface visually quiet. Do not create a border around the grid, a title band, a photo opening, a memo area, a calendar cell, or any functional-looking region.'},
 'month-back':{label:'월력 뒷면',purpose:'Provide a quiet surface behind separately editable images, calendars, planners, and notes.',generate:['supporting paper background','one small independent edge illustration'],reserve:['every selected month-back component and its coordinates'],prompt:'Keep all component regions plain. Do not create or imitate photo frames, calendars, planner panels, memo lines, checklists, cards, dividers, or captions. The designer will create the complete composition with editable objects.'},
 'back-cover':{label:'뒷표지',purpose:'Close the design set with a quiet continuation of the cover background.',generate:['closing paper background','one restrained edge motif'],reserve:['school name','school logo','address','phone and fax','website'],prompt:'Use the cover visual language at much lower intensity. Do not create an information frame, photo opening, brand panel, or logo-like mark.'}
});

export const ROLE_DIRECTIONS=Object.freeze({cover:['centered-photo','asymmetric-photo'],annual:['open-grid','header-band'],'school-symbols':['editorial-cards','heritage-panels'],month:['seasonal-corner','header-accent'],'month-back':['image-calendar','planner-collage'],'back-cover':['quiet-information','closing-motif']});
const STYLE_NAMES={balanced:'clean balanced editorial',seasonal:'connected seasonal illustration',photo:'photo-led brand framing',playful:'student-friendly graphic accents'};
const DESIGN_STYLE_NAMES={editorial:'disciplined editorial with fine rules and generous whitespace','seasonal-watercolor':'seasonal watercolor with soft natural transitions',geometry:'modern geometry with decisive planes and brand-color rhythm','photo-story':'photo-story framing with quiet documentary details','student-playful':'student-friendly graphic language with rounded educational motifs','premium-minimal':'premium minimal typography with restrained material texture'};
const LEVEL_NAMES={all:'general audience',elementary:'elementary school',middle:'middle school',high:'high school'};
const DENSITY_NAMES={low:'restrained',medium:'moderate',high:'rich but never over protected information'};
const RHYTHM_GUIDANCE={uniform:'keep the same composition, palette balance, and motif intensity across all months',color:'keep composition stable and vary the accent and background colors by month',seasonal:'vary colors and motifs by four seasons while retaining one visual family',alternating:'alternate two related composition directions between odd and even months',story:'develop a visible month-to-month narrative while preserving the shared visual identity'};
const MONTH_BACK_GUIDANCE={fixed:'use the same editable component arrangement across all months',alternating:'mirror the editable component arrangement between odd and even months',cycle:'cycle through three related editable component arrangements across the twelve months'};
const DECORATION_GUIDANCE={none:'no decorative motif',geometric:'geometric planes and fine rules','hand-drawn':'restrained hand-drawn marks','paper-scrap':'paper scraps, clips, and archival layers',postmark:'postage stamp and postmark-inspired shapes without readable text',seasonal:'seasonal natural motifs','school-symbol':'abstract school-identity motifs without inventing a logo'};
const MATERIAL_GUIDANCE={'clean-digital':'clean digital print surface','matte-print':'soft matte print appearance','ivory-paper':'warm ivory paper surface','rough-paper':'subtle rough paper grain','vintage-print':'restrained vintage print texture with safe contrast'};
const PAGE_TYPE_GUIDANCE={
 cover:{'large-photo':'one dominant photo opening with a calm lower information zone','photo-collage':'several clearly separated empty photo openings',typography:'a large quiet title field with small supporting image space',illustration:'one dominant decorative illustration field beside protected content',split:'a strong image and information split'},
 annual:{'balanced-4x3':'a centered 4 by 3 annual grid field','open-grid':'a wide low-density annual grid with generous margins','header-band':'a distinct full-width year header band above the annual grid','split-info':'a large annual grid beside a separate information column'},
 'school-symbols':{'editorial-cards':'independent editorial cards for each school symbol','section-panels':'clear vertical and horizontal information panels','heritage-document':'a formal centered document composition with subtle heritage cues','symbol-photo':'a dominant empty symbol-image field beside text panels'},
 month:{'calendar-led':'a dominant unobstructed calendar field','large-month-number':'a tall protected month-title zone above the grid','top-image-band':'an empty decorative image band above the calendar','split-calendar-image':'a vertical image field beside the calendar grid','open-editorial':'a compact centered calendar with generous editorial whitespace'},
 'month-back':{'image-calendar':'a large empty image field beside one editable calendar','large-image':'a dominant landscape image field above compact information','photo-collage':'a modular empty photo collage beside calendar information',planner:'a dominant planner field with compact image and calendar zones','memo-calendar':'a large memo field paired with calendar information'},
 'back-cover':{'school-info':'a structured school-information panel beside a closing image','cover-continuation':'a quieter continuation of the cover image and motif split','photo-closing':'one wide closing photo opening above school information','minimal-brand':'a sparse brand mark and information composition'}
};

export function buildPrompt(input){const role=ROLE_PROMPTS[input.pageRole];if(!role)throw new Error(`Unknown page role: ${input.pageRole}`);const colors=input.palette?.length?input.palette.join(', '):'calm print-appropriate colors',month=input.month?` Target month: ${input.month.year}-${String(input.month.month).padStart(2,'0')}; season: ${input.month.season||'unspecified'}; monthly accent: ${input.month.accentColor||'derive from palette'}.`:'',spec=input.designSpec||{},typeId=spec.pageTypeId,typeGuide=PAGE_TYPE_GUIDANCE[input.pageRole]?.[typeId],designStyle=DESIGN_STYLE_NAMES[spec.styleId],values=spec.expression||{},expression=` Design expression: decoration ${values.decoration||'medium'}; photo mode ${values.photoMode||'mixed'}; seasonal intensity ${values.seasonal||'medium'}; information density ${values.density||'medium'}. Monthly rhythm: ${RHYTHM_GUIDANCE[values.variationRhythm]||RHYTHM_GUIDANCE.seasonal}. Month-back variation: ${MONTH_BACK_GUIDANCE[values.monthBackVariation]||MONTH_BACK_GUIDANCE.fixed}. Decoration family: ${DECORATION_GUIDANCE[values.decorationFamily]||DECORATION_GUIDANCE.seasonal}. Material: ${MATERIAL_GUIDANCE[values.material]||MATERIAL_GUIDANCE['clean-digital']}.`;return `${COMMON_PROMPT} Page role: ${role.label}. Purpose: ${role.purpose} Style: ${designStyle||STYLE_NAMES[input.styleKey]||STYLE_NAMES.balanced}. ${typeGuide?`The editable composition is ${typeId}, meaning ${typeGuide}; use it only to know where decoration is forbidden, never depict or outline it.`:''}${expression} Audience: ${LEVEL_NAMES[input.schoolLevel]||LEVEL_NAMES.all}. Decoration density is an upper limit: ${DENSITY_NAMES[input.decorationDensity]||DENSITY_NAMES.medium}. Palette: ${colors}. Composition direction: ${input.variantDirection}. Generate only: ${role.generate.join(', ')}. Keep visually empty for: ${role.reserve.join(', ')}. ${role.prompt}${month} ${input.protectedRegions?.length?`Protected editable regions: ${input.protectedRegions.map(item=>`${item.role}(${item.x},${item.y},${item.width},${item.height})`).join('; ')}.`:''} ${spec.protectedContent?.length?`Protected content contract: ${spec.protectedContent.join(', ')}.`:''} ${input.monthBackComponents?.length?`The following components will be added later as editable objects, so do not depict them: ${input.monthBackComponents.join(', ')}.`:''} ${input.instruction||''}`.replace(/\s+/g,' ').trim()}
