import assert from 'node:assert/strict';
import test from 'node:test';

await import('../apps/designer-studio/ai-design/design-type-catalog@0.1.0.js');
await import('../apps/designer-studio/ai-design/design-spec@0.1.0.js');
await import('../apps/designer-studio/ai-design/design-layout-application@0.1.0.js');

const api=globalThis.ACDLDesignLayoutApplication,specApi=globalThis.ACDLDesignSpec,catalog=globalThis.ACDLDesignTypeCatalog;
function element(id,role,type='text'){return {id,role,type,x:0,y:0,width:1,height:1,zIndex:1,content:id}}
function project(){const pages=[['cover','cover-front'],['annual','cover-back'],['symbols','front-insert-front'],['month','monthly-front'],['month-back','monthly-back'],['back','back-cover-back']].map(([id,role],index)=>({id,role,number:index+1,overrides:{}}));return {template:{settings:{},masters:{calendar:{}}},book:{pageInstances:pages,elementsByPage:{cover:[element('cover-photo','school-building','image'),element('cover-year','year'),element('cover-name','school-name')],annual:[element('annual-calendar','annual','year-calendar'),element('annual-year','year')],symbols:[element('symbol-logo','school-logo','image'),element('symbol-motto','school-motto'),element('symbol-song','school-song','image')],month:[element('month-photo','monthly-image','image'),element('month-title','month-title')],'month-back':[element('back-photo','monthly-image','image'),element('back-calendar','current-calendar','mini-calendar'),element('back-memo','memo','memo')],back:[element('closing-photo','school-building','image'),element('closing-contact','school-contact')]}}}}

test('all six selected page types become editable page layout metadata',()=>{const draft=project(),spec=specApi.normalize({styleId:'geometry',pageTypes:{cover:'split',annual:'split-info','school-symbols':'section-panels',month:'split-calendar-image','month-back':'planner','back-cover':'minimal-brand'}},catalog),result=api.apply(draft,spec);assert.equal(result.pages.length,6);assert.ok(result.pages.every(page=>page.elementCount>0));assert.equal(draft.book.pageInstances.find(page=>page.id==='cover').aiDesignLayout.typeId,'split');assert.equal(draft.book.pageInstances.find(page=>page.id==='month').overrides.calendarRegion.x,38);assert.equal(draft.template.masters.calendar.calendarRegion.x,38);assert.equal(draft.template.settings.aiDesignLayoutApplication.editable,true)});
test('layout application preserves content and keeps the AI background full bleed',()=>{const draft=project();draft.book.elementsByPage.cover.unshift({id:'bg',role:'ai-design-background',type:'image',x:0,y:0,width:100,height:100,zIndex:0});const before=draft.book.elementsByPage.cover.map(item=>item.content||item.id);api.apply(draft,specApi.normalize({},catalog));assert.deepEqual(draft.book.elementsByPage.cover.map(item=>item.content||item.id),before);assert.deepEqual((({x,y,width,height})=>({x,y,width,height}))(draft.book.elementsByPage.cover[0]),{x:0,y:0,width:100,height:100})});
