import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {buildImagePrompt,validateGenerationInput} from '../api/ai-design-generate.js';

function load(relative,name,context={}){context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL(relative,import.meta.url),'utf8'),context);return context[name]}

test('desk style catalog exposes seven template-editable styles and one flexible divider role',()=>{
 const context={},catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',context),specApi=load('../apps/designer-studio/ai-design/design-spec@0.3.0.js','ACDLDesignSpec',context);
 assert.equal(catalog.scope,'desk-first');assert.equal(catalog.styles.length,7);assert.deepEqual(Object.keys(catalog.roles),['cover','annual','divider','month','month-back','back-cover']);
 assert.deepEqual(Object.keys(catalog.expressionOptions),['variationRhythm','monthColorVariation','monthCompositionVariation','monthMotifVariation','monthDecorationVariation','monthBackPhoto','monthBackSeason']);
 const project={template:{settings:{}}},saved=specApi.write(project,{styleId:'modern-geometry',commonGuideline:'현재 템플릿 공통 지침',styleSnapshots:[{id:'modern-geometry',name:'학교 전용 모던',guidance:{divider:{description:'간지 설명',keywords:'unique edge',forbidden:'letters'}}}]},catalog);
 assert.equal(saved.styleSnapshots.find(item=>item.id==='modern-geometry').name,'학교 전용 모던');assert.equal(specApi.read(structuredClone(project),catalog).commonGuideline,'현재 템플릿 공통 지침');
});

test('actual divider pages become separate generation targets without a fixed 28-page assumption',()=>{
 const api=load('../apps/designer-studio/ai-design/ai-generation-context@0.2.0.js','ACDLAIGenerationContext'),pages=[{id:'cover',role:'cover-front'},{id:'insert-a',role:'front-insert-front',semanticPageRole:'school-symbols'},{id:'insert-b',role:'rear-insert-back',semanticPageRole:'divider'},{id:'month',role:'monthly-front'}],project={productType:{category:'desk'},template:{calendarTypeSnapshot:{definition:{id:'desk-standard',family:{id:'desk'},finishedSize:{width:260,height:180},productionSize:{width:266,height:186},binding:{edge:'top',method:'wire-o'}}},resources:{exportSettings:{bleed:3}}},book:{pageInstances:pages,elementsByPage:{'insert-a':[{role:'school-song'}],'insert-b':[{role:'history'}]}}};
 const context=api.build(project),divider=context.roles.find(item=>item.role==='divider');assert.equal(divider.targets.length,2);assert.deepEqual(divider.targets.map(item=>item.pageId),['insert-a','insert-b']);assert.equal(api.plan(context,{monthCount:12}).generationCount,15);
});

test('prompt prioritizes saved page guidance and the concrete divider instance',()=>{
 const designSpec={schemaVersion:'ai-design-spec.v2',version:'0.3.0',styleId:'modern-geometry',commonGuideline:'CURRENT TEMPLATE RULES FIRST',styleSnapshots:[{id:'modern-geometry',name:'학교 전용 모던',guidance:{divider:{description:'THIS DIVIDER DESCRIPTION',keywords:'unique quiet edge',forbidden:'busy center'}}}],pageTypes:{divider:'content-led'},pageInstance:{position:'rear',surface:'back',contentPurpose:'school-history',index:2,total:3},expression:{variationRhythm:'story',monthBackPhoto:'use',monthBackSeason:'subtle'},protectedContent:['school-text']};
 const input=validateGenerationInput({styleKey:'balanced',pageRole:'divider',request:{designSpec}}),prompt=buildImagePrompt(input);assert.equal(input.designSpec.pageInstance.index,2);assert.match(prompt,/CURRENT TEMPLATE RULES FIRST/);assert.match(prompt,/THIS DIVIDER DESCRIPTION/);assert.match(prompt,/unique quiet edge/);assert.match(prompt,/rear/);assert.match(prompt,/school-history/);assert.match(prompt,/Never rasterize editable content/);
});

test('new style editor preserves page composition and preview while removing obsolete expression controls',()=>{
 const source=fs.readFileSync(new URL('../apps/designer-studio/features/template-settings-refresh-runtime.js',import.meta.url),'utf8');
 assert.match(source,/pageTypeCard/);assert.match(source,/2\. 페이지별 시작 구성/);assert.match(source,/6\. 조합 미리보기/);assert.match(source,/4\. 월력 디자인 변화/);assert.match(source,/dividerSelect\.dataset\.designPageType='divider'/);assert.match(source,/expression:current\.expression/);assert.match(source,/if\(\/\^1\\\.\|\^3\\\.\|\^4\\\.\//);
});
test('divider composition survives normalization and reaches each actual generation target',()=>{const runtime={},catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',runtime),specApi=load('../apps/designer-studio/ai-design/design-spec@0.3.0.js','ACDLDesignSpec',runtime),contextApi=load('../apps/designer-studio/ai-design/ai-generation-context@0.2.0.js','ACDLAIGenerationContext',runtime),spec=specApi.normalize({dividerPages:{'surface.2.back':{purpose:'academic-schedule',layoutId:'open-gallery',imageSource:'user-assets',fallbackPreset:'yearly-plan',objects:['title','annual-calendar','image-slot','yearly-plan','invalid']}}},catalog);assert.deepEqual(JSON.parse(JSON.stringify(spec.dividerPages['surface.2.back'])),{purpose:'academic-schedule',layoutId:'open-gallery',imageSource:'user-assets',fallbackPreset:'yearly-plan',objects:['title','annual-calendar','image-slot','yearly-plan']});const project={template:{settings:{aiDesignSpec:spec},calendarTypeSnapshot:{definition:{id:'desk-standard',family:{id:'desk'},policies:{frontInsert:'optional'},finishedSize:{width:260,height:180},productionSize:{width:266,height:186}}}},productType:{category:'desk'},book:{pageInstances:[{id:'surface.2.back',role:'front-insert-back',side:'back'}]}};const target=contextApi.build(project).roles.find(role=>role.role==='divider').targets[0];assert.equal(target.contentPurpose,'academic-schedule');assert.equal(target.layoutId,'open-gallery');assert.equal(target.imageSource,'user-assets');assert.equal(target.fallbackPreset,'yearly-plan');assert.deepEqual(JSON.parse(JSON.stringify(target.objects)),['title','annual-calendar','image-slot','yearly-plan'])});

test('divider presets live in AI design generation and cover every product preset',()=>{const source=fs.readFileSync(new URL('../apps/designer-studio/ai-design/divider-composition-runtime.js',import.meta.url),'utf8');assert.match(source,/data-resource-content="ai-design"/);assert.doesNotMatch(source,/data-resource-content="design-types"/);for(const id of ['school-introduction','school-symbols','annual-calendar','academic-schedule','school-history','education-vision','user-image','yearly-plan','yearly-checklist','free','blank'])assert.match(source,new RegExp(`id:'${id}'`));assert.match(source,/data-divider-image-source/);assert.match(source,/data-divider-fallback/)});
