import assert from 'node:assert/strict';
import test from 'node:test';

await import('../apps/designer-studio/ai-design/design-object-style-presets@0.2.0.js');
const api=globalThis.ACDLDesignObjectStylePresets;
function project(){return {template:{resources:{colorTheme:{},fontTheme:{}},settings:{},masters:{calendar:{design:{}}},masterElements:{back:[{id:'mini',type:'mini-calendar',style:{}},{id:'planner',type:'memo',memoLayout:'weekly',style:{}}]}},book:{monthlyStyleOverrides:Array.from({length:12},(_,index)=>({monthKey:`m${index+1}`,tokens:{}})),elementsByPage:{cover:[{id:'year',type:'text',role:'year',style:{}},{id:'photo',type:'image-frame',role:'school-building',style:{}}]}}}}

test('six current design styles provide calendar, frame, mini-calendar and planner presets',()=>{const current=['editorial-graphic','campus-documentary','modular-color-system','contemporary-illustration','digital-aura-motion','korean-modern-graphic'];current.forEach(id=>{const preset=api.presets[id];assert.ok(preset,`${id} preset`);assert.ok(preset.calendar.monthTitleStyle);assert.equal(preset.calendar.background,false);assert.equal(preset.calendar.gridBackground,'transparent');assert.ok(preset.frame.stroke);assert.equal(typeof preset.mini.background,'boolean');assert.ok(preset.planner.background)})});
test('active object-style runtime contains only the six current styles',()=>{assert.deepEqual(Object.keys(api.presets),['editorial-graphic','campus-documentary','modular-color-system','contemporary-illustration','digital-aura-motion','korean-modern-graphic'])});
test('selected style updates real editable objects and monthly calendar master',()=>{const draft=project(),result=api.apply(draft,{styleId:'modular-color-system',expression:{monthFrontMode:'color-accent'}});assert.equal(result.schemaVersion,'ai-design-object-style-application.v1');assert.equal(draft.template.masters.calendar.design.gridStyle,'open-rows');assert.equal(draft.book.elementsByPage.cover[0].style.fontFamily,'Pretendard');assert.equal(draft.book.elementsByPage.cover[1].style.stroke,'#2458a6');assert.equal(draft.template.masterElements.back[0].style.gridLine,true);assert.equal(draft.template.masterElements.back[1].style.borderRadius,0);assert.equal(new Set(draft.book.monthlyStyleOverrides.map(item=>item.tokens.primary)).size,3);assert.equal(draft.template.settings.aiDesignObjectStyleApplication.editable,true)});
test('month-front preset controls color cadence and records the simplified expression',()=>{for(const [mode,count] of [['alternating-accent',2],['color-only',3],['quarterly-theme',4]]){const draft=project(),result=api.apply(draft,{styleId:'contemporary-illustration',expression:{monthFrontMode:mode,monthBackMode:'auto-match'}});assert.equal(new Set(draft.book.monthlyStyleOverrides.map(item=>item.tokens.primary)).size,count);assert.equal(result.expression.monthFrontMode,mode);assert.equal(result.expression.monthBackMode,'auto-match');assert.equal(result.monthlyColorCount,count);assert.ok(draft.book.monthlyStyleOverrides.every(item=>item.tokens.monthFrontMode===mode))}});
