import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {buildImagePrompt,validateGenerationInput} from '../api/ai-design-generate.js';

function load(relative,name,context={}){context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL(relative,import.meta.url),'utf8'),context);return context[name]}

test('desk style catalog exposes six template-editable styles and one flexible divider role',()=>{
 const context={},catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',context),specApi=load('../apps/designer-studio/ai-design/design-spec@0.3.0.js','ACDLDesignSpec',context);
 assert.equal(catalog.scope,'desk-first');assert.equal(catalog.styles.length,6);assert.deepEqual(Object.keys(catalog.roles),['cover','annual','divider','month','month-back','back-cover']);
 assert.deepEqual(Object.keys(catalog.expressionOptions),['monthFrontMode','monthBackMode']);
 assert.equal(catalog.roles['month-back'].options.at(-1)[0],'illustration-led');
 const project={template:{settings:{}}},saved=specApi.write(project,{promptCompositionVersion:'shape-system.v2',styleId:'modular-color-system',commonGuideline:'현재 템플릿 공통 지침',styleSnapshots:[{id:'modular-color-system',name:'학교 전용 모던',guidance:{divider:{description:'간지 설명',keywords:'unique edge',forbidden:'letters'}}}]},catalog);
 assert.equal(saved.styleSnapshots.find(item=>item.id==='modular-color-system').name,'학교 전용 모던');assert.equal(specApi.read(structuredClone(project),catalog).commonGuideline,'현재 템플릿 공통 지침');
});

test('versioned style profiles document six mutually distinct visual signatures',()=>{const profiles=JSON.parse(fs.readFileSync(new URL('../apps/designer-studio/ai-design/rules/style-profiles@0.3.0.json',import.meta.url)));assert.equal(profiles.principle,'shape-system-before-material');assert.equal(profiles.profiles.length,6);assert.equal(new Set(profiles.profiles.map(item=>item.signature)).size,6);assert.ok(profiles.profiles.every(item=>item.exclude.length>=3))});

test('six shape-system styles keep role-specific directions without rasterizing functional objects',()=>{const catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',{}),byId=Object.fromEntries(catalog.styles.map(item=>[item.id,item]));assert.match(byId['editorial-graphic'].guidance.cover[1],/no generated text/);assert.match(byId['campus-documentary'].guidance['month-back'][1],/real replaceable school photography remains dominant/);assert.match(byId['modular-color-system'].guidance.month[1],/transparent calendar grid/);assert.match(byId['korean-modern-graphic'].guidance.cover[1],/no paper texture/);assert.ok(catalog.styles.every(style=>Object.keys(style.guidance).length===6))});

test('all twelve retired style selections migrate to the six current styles',()=>{const runtime={},catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',runtime),specApi=load('../apps/designer-studio/ai-design/design-spec@0.3.0.js','ACDLDesignSpec',runtime),expected={editorial:'editorial-graphic','seasonal-watercolor':'contemporary-illustration',geometry:'modular-color-system','photo-story':'campus-documentary','student-playful':'contemporary-illustration','premium-minimal':'editorial-graphic','warm-neutral-mocha':'editorial-graphic','modern-sage-eco':'modular-color-system','soft-pastel-watercolor':'contemporary-illustration','clear-ui-line':'modular-color-system','traditional-hanji-tone':'korean-modern-graphic','trendy-mesh-aura':'digital-aura-motion'};for(const [retired,current] of Object.entries(expected))assert.equal(specApi.normalize({styleId:retired},catalog).styleId,current)});

test('actual divider pages become separate generation targets without a fixed 28-page assumption',()=>{
 const api=load('../apps/designer-studio/ai-design/ai-generation-context@0.2.0.js','ACDLAIGenerationContext'),pages=[{id:'cover',role:'cover-front'},{id:'insert-a',role:'front-insert-front',semanticPageRole:'school-symbols'},{id:'insert-b',role:'rear-insert-back',semanticPageRole:'divider'},{id:'month',role:'monthly-front'}],project={productType:{category:'desk'},template:{calendarTypeSnapshot:{definition:{id:'desk-standard',family:{id:'desk'},finishedSize:{width:260,height:180},productionSize:{width:266,height:186},binding:{edge:'top',method:'wire-o'}}},resources:{exportSettings:{bleed:3}}},book:{pageInstances:pages,elementsByPage:{'insert-a':[{role:'school-song'}],'insert-b':[{role:'history'}]}}};
 const context=api.build(project),divider=context.roles.find(item=>item.role==='divider');assert.equal(divider.targets.length,2);assert.deepEqual(divider.targets.map(item=>item.pageId),['insert-a','insert-b']);assert.equal(api.plan(context,{monthCount:12}).generationCount,15);
});

test('prompt prioritizes saved page guidance and the concrete divider instance',()=>{
 const designSpec={schemaVersion:'ai-design-spec.v2',version:'0.3.0',styleId:'modular-color-system',commonGuideline:'CURRENT TEMPLATE RULES FIRST',styleSnapshots:[{id:'modular-color-system',name:'학교 전용 모던',guidance:{divider:{description:'THIS DIVIDER DESCRIPTION',keywords:'unique quiet edge',forbidden:'busy center'}}}],pageTypes:{divider:'content-led'},pageInstance:{position:'rear',surface:'back',contentPurpose:'school-history',index:2,total:3},expression:{monthFrontMode:'color-accent',monthBackMode:'auto-match'},protectedContent:['school-text']};
 const input=validateGenerationInput({styleKey:'balanced',pageRole:'divider',request:{designSpec}}),prompt=buildImagePrompt(input);assert.equal(input.designSpec.pageInstance.index,2);assert.match(prompt,/CURRENT TEMPLATE RULES FIRST/);assert.match(prompt,/THIS DIVIDER DESCRIPTION/);assert.match(prompt,/unique quiet edge/);assert.match(prompt,/rear/);assert.match(prompt,/school-history/);assert.match(prompt,/Never rasterize or invent school photos/);
});

test('new style editor moves page composition before visual style and uses front/back preset cards',()=>{
 const source=fs.readFileSync(new URL('../apps/designer-studio/features/template-settings-refresh-runtime.js',import.meta.url),'utf8');
 assert.match(source,/pageTypeCard/);assert.match(source,/pageSettings\.querySelector\('#pageSettingsPolicyMount'\)\?\.after\(pageTypeCard\)/);assert.match(source,/monthFrontModeCards/);assert.match(source,/monthBackModeCards/);assert.match(source,/recommendedBackMode/);assert.match(source,/expression:current\.expression/);
});
test('divider composition survives normalization and reaches each actual generation target',()=>{const runtime={},catalog=load('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js','ACDLDesignTypeCatalog',runtime),specApi=load('../apps/designer-studio/ai-design/design-spec@0.3.0.js','ACDLDesignSpec',runtime),contextApi=load('../apps/designer-studio/ai-design/ai-generation-context@0.2.0.js','ACDLAIGenerationContext',runtime),spec=specApi.normalize({dividerPages:{'surface.2.back':{purpose:'academic-schedule',layoutId:'open-gallery',imageSource:'user-assets',fallbackPreset:'yearly-plan',objects:['title','annual-calendar','image-slot','yearly-plan','invalid']}}},catalog);assert.deepEqual(JSON.parse(JSON.stringify(spec.dividerPages['surface.2.back'])),{purpose:'academic-schedule',layoutId:'open-gallery',imageSource:'user-assets',fallbackPreset:'yearly-plan',objects:['title','annual-calendar','image-slot','yearly-plan']});const project={template:{settings:{aiDesignSpec:spec},calendarTypeSnapshot:{definition:{id:'desk-standard',family:{id:'desk'},policies:{frontInsert:'optional'},finishedSize:{width:260,height:180},productionSize:{width:266,height:186}}}},productType:{category:'desk'},book:{pageInstances:[{id:'surface.2.back',role:'front-insert-back',side:'back'}]}};const target=contextApi.build(project).roles.find(role=>role.role==='divider').targets[0];assert.equal(target.contentPurpose,'academic-schedule');assert.equal(target.layoutId,'open-gallery');assert.equal(target.imageSource,'user-assets');assert.equal(target.fallbackPreset,'yearly-plan');assert.deepEqual(JSON.parse(JSON.stringify(target.objects)),['title','annual-calendar','image-slot','yearly-plan'])});

test('divider presets live in page settings and expose the five approved composition types',()=>{const source=fs.readFileSync(new URL('../apps/designer-studio/ai-design/divider-composition-runtime.js',import.meta.url),'utf8');assert.match(source,/data-resource-content="page-settings"/);assert.doesNotMatch(source,/data-resource-content="design-types"/);for(const id of ['school-symbols','school-introduction','yearly-plan','annual-calendar','free'])assert.match(source,new RegExp(`id:'${id}'`));for(const id of ['academic-schedule','school-history','education-vision','user-image','yearly-checklist','blank'])assert.doesNotMatch(source,new RegExp(`id:'${id}'`));assert.match(source,/data-divider-image-source/);assert.match(source,/data-divider-fallback/)});
test('divider composition mounts in page settings and joins the single page-settings save',()=>{const source=fs.readFileSync(new URL('../apps/designer-studio/ai-design/divider-composition-runtime.js',import.meta.url),'utf8');assert.match(source,/pageSettingsDividerMount/);assert.match(source,/mount\.appendChild\(card\)/);assert.match(source,/card\.hidden=!items\.length/);assert.match(source,/function collect\(/);assert.match(source,/render,entryFor,collect/);assert.doesNotMatch(source,/saveDividerCompositionBtn/)});
test('school-symbol settings expose four physical-reference layouts after object selection',()=>{const source=fs.readFileSync(new URL('../apps/designer-studio/ai-design/divider-composition-runtime.js',import.meta.url),'utf8');for(const id of ['individual-cards','split-panels','open-editorial','ruled-editorial'])assert.match(source,new RegExp(`'${id}'`));assert.match(source,/2\. 포함 개체/);assert.match(source,/3\. 대표 배치/);assert.match(source,/symbolBoxes\(entry\.objects\)/)});
test('month settings expose four header compositions without address contact or website objects',()=>{const source=fs.readFileSync(new URL('../apps/designer-studio/features/template-settings-refresh-runtime.js',import.meta.url),'utf8'),specSource=fs.readFileSync(new URL('../apps/designer-studio/ai-design/design-spec@0.3.0.js',import.meta.url),'utf8');for(const id of ['distributed-header','center-title-school-left','center-title-block','left-title-split'])assert.match(source,new RegExp(`'${id}'`));const monthOptions=source.match(/month:\['월력 앞면',(.*?)\],'back-cover-front'/)?.[1]||'';for(const label of ['교표','학교명','교훈','슬로건','사진 프레임'])assert.match(monthOptions,new RegExp(label));for(const label of ['주소','연락처','웹사이트'])assert.doesNotMatch(monthOptions,new RegExp(label));assert.match(specSource,/month:\['school-logo','school-name','school-motto','school-slogan','image-frame'\]/)});
