import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';

await import('../apps/designer-studio/ai-design/design-type-catalog@0.3.0.js');
await import('../apps/designer-studio/ai-design/design-spec@0.3.0.js');
await import('../apps/designer-studio/ai-design/design-layout-application@0.1.0.js');

const api=globalThis.ACDLDesignLayoutApplication,specApi=globalThis.ACDLDesignSpec,catalog=globalThis.ACDLDesignTypeCatalog;
const studioRuntime=fs.readFileSync(new URL('../apps/designer-studio/features/studio-runtime-core.js',import.meta.url),'utf8');
function element(id,role,type='text'){return {id,role,type,x:0,y:0,width:1,height:1,zIndex:1,content:id}}
function project(){const pages=[['cover','cover-front'],['annual','cover-back'],['symbols','front-insert-front'],['month','monthly-front'],['month-back','monthly-back'],['back','back-cover-back']].map(([id,role],index)=>({id,role,number:index+1,overrides:{}}));return {template:{settings:{},masters:{calendar:{}}},book:{pageInstances:pages,elementsByPage:{cover:[element('cover-photo','school-building','image'),element('cover-year','year'),element('cover-name','school-name')],annual:[element('annual-calendar','annual','year-calendar'),element('annual-year','year')],symbols:[element('symbol-logo','school-logo','image'),element('symbol-motto','school-motto'),element('symbol-song','school-song','image')],month:[element('month-photo','monthly-image','image'),element('month-title','month-title')],'month-back':[element('back-photo','monthly-image','image'),element('back-calendar','current-calendar','mini-calendar'),element('back-memo','memo','memo')],back:[element('closing-photo','school-building','image'),element('closing-contact','school-contact')]}}}}

test('all six selected page types become editable page layout metadata',()=>{const draft=project(),spec=specApi.normalize({styleId:'geometry',pageTypes:{cover:'split',annual:'split-info','school-symbols':'section-panels',month:'split-calendar-image','month-back':'planner','back-cover':'minimal-brand'}},catalog),result=api.apply(draft,spec);assert.equal(result.pages.length,6);assert.ok(result.pages.every(page=>page.elementCount>0));assert.equal(draft.book.pageInstances.find(page=>page.id==='cover').aiDesignLayout.typeId,'split');assert.equal(draft.book.pageInstances.find(page=>page.id==='month').overrides.calendarRegion.x,38);assert.equal(draft.template.masters.calendar.calendarRegion.x,38);assert.equal(draft.template.settings.aiDesignLayoutApplication.editable,true)});
test('layout application preserves existing objects, fills missing bound objects and keeps the AI background full bleed',()=>{const draft=project();draft.book.elementsByPage.cover.unshift({id:'bg',role:'ai-design-background',type:'image',x:0,y:0,width:100,height:100,zIndex:0});const before=draft.book.elementsByPage.cover.map(item=>item.id);api.apply(draft,specApi.normalize({},catalog));const after=draft.book.elementsByPage.cover.map(item=>item.id);before.forEach(value=>assert.ok(after.includes(value)));assert.ok(draft.book.elementsByPage.cover.some(item=>item.binding==='school.profile.logo'));assert.ok(draft.book.elementsByPage.cover.some(item=>item.binding==='school.address'));assert.deepEqual((({x,y,width,height})=>({x,y,width,height}))(draft.book.elementsByPage.cover[0]),{x:0,y:0,width:100,height:100})});
test('blank fixed pages receive editable school data scaffolds before layout',()=>{const draft=project();for(const id of ['cover','annual','symbols','back'])draft.book.elementsByPage[id]=[];api.apply(draft,specApi.normalize({},catalog));assert.ok(draft.book.elementsByPage.cover.some(item=>item.binding==='school.profile.building'));assert.ok(draft.book.elementsByPage.annual.some(item=>item.type==='year-calendar'));for(const binding of ['school.profile.motto','school.profile.song','school.profile.tree','school.profile.flower'])assert.ok(draft.book.elementsByPage.symbols.some(item=>item.binding===binding));for(const binding of ['school.name','school.address','school.contacts','school.website'])assert.ok(draft.book.elementsByPage.back.some(item=>item.binding===binding))});
test('desk reverse surfaces avoid duplicated divider and back-cover compositions without leaving an accidental blank',()=>{const draft=project(),divider=draft.book.pageInstances.find(page=>page.id==='symbols'),back=draft.book.pageInstances.find(page=>page.id==='back');divider.side='back';back.side='front';draft.book.elementsByPage.symbols=[];draft.book.elementsByPage.back=[];api.apply(draft,specApi.normalize({},catalog));assert.ok(draft.book.elementsByPage.symbols.some(item=>item.binding==='school.name'));assert.equal(draft.book.elementsByPage.symbols.some(item=>item.binding==='school.profile.song'),false);assert.deepEqual(draft.book.elementsByPage.back.map(item=>item.binding).sort(),['calendar.year','school.profile.building'])});
test('calendar year bindings are synchronized while selected layouts are applied',()=>{const draft=project();draft.settings={year:2031,startMonth:3};draft.book.elementsByPage.cover.find(item=>item.role==='year').content='2027';api.apply(draft,specApi.normalize({},catalog));assert.equal(draft.book.elementsByPage.cover.find(item=>item.role==='year').content,'2031')});
test('page selection avoids rebuilding the full navigator and resource library',()=>{const handler=studioRuntime.match(/function pageButton\(p\)\{([^\n]+)\}/)?.[1]||'';assert.match(handler,/renderPage\(\)/);assert.match(handler,/renderInspector\(\)/);assert.doesNotMatch(handler,/;render\(\)/);assert.doesNotMatch(handler,/renderResourceAssetManager\(\)/)});
test('generated cover identity stays inside the bottom safe area',()=>{const draft=project(),spec=specApi.normalize({pageTypes:{cover:'large-photo'}},catalog);draft.book.elementsByPage.cover.push(element('cover-slogan','slogan'));api.apply(draft,spec);for(const item of draft.book.elementsByPage.cover.filter(item=>item.role!=='ai-design-background'))assert.ok(item.y+item.height<=95,`${item.id} leaves safe area`)});
test('school symbol title and image cards receive independent readable zones',()=>{const draft=project(),spec=specApi.normalize({pageTypes:{'school-symbols':'editorial-cards'}},catalog);draft.book.elementsByPage.symbols.push(element('symbols-title','symbols-title'),element('symbol-tree','school-tree','image'),element('symbol-flower','school-flower','image'));api.apply(draft,spec);const items=draft.book.elementsByPage.symbols,title=items.find(item=>item.id==='symbols-title'),tree=items.find(item=>item.id==='symbol-tree'),flower=items.find(item=>item.id==='symbol-flower');assert.equal(title.y,7);assert.ok(tree.width<60);assert.notEqual(tree.x,flower.x)});
test('song-led school symbol layout protects the score and separates supporting symbols',()=>{const draft=project(),spec=specApi.normalize({pageTypes:{'school-symbols':'song-led-split'}},catalog);draft.book.elementsByPage.symbols.push(element('symbols-title','symbols-title'),element('symbol-tree','school-tree','image'),element('symbol-flower','school-flower','image'));api.apply(draft,spec);const items=draft.book.elementsByPage.symbols,song=items.find(item=>item.role==='school-song'),motto=items.find(item=>item.role==='school-motto'),tree=items.find(item=>item.role==='school-tree'),flower=items.find(item=>item.role==='school-flower');assert.deepEqual((({x,y,width,height})=>({x,y,width,height}))(song),{x:55,y:20,width:39,height:72});assert.equal(song.imageFit,'contain');assert.equal(song.cropAllowed,false);assert.deepEqual(song.minimumReadableSizeMm,{width:90,height:95});assert.ok(motto.x+ motto.width<=song.x);assert.notEqual(tree.x,flower.x)});
test('named image layouts create real replaceable image frames',()=>{const draft=project();draft.book.elementsByPage.cover=[];draft.book.elementsByPage.month=[];api.apply(draft,specApi.normalize({pageTypes:{cover:'photo-collage',month:'top-image-band'}},catalog));const coverFrames=draft.book.elementsByPage.cover.filter(item=>item.type==='image-frame');assert.equal(coverFrames.length,2);assert.ok(coverFrames.every(item=>item.replaceable&&item.image?.binding));const monthFrame=draft.book.elementsByPage.month.find(item=>item.type==='image-frame');assert.equal(monthFrame.image.binding,'calendar.monthlyImages.current');assert.deepEqual((({x,y,width,height})=>({x,y,width,height}))(monthFrame),{x:5,y:5,width:90,height:14})});
test('academic schedule and split annual information use the real calendar event-list widget',()=>{const draft=project();draft.template.settings.aiDesignSpec={dividerPages:{symbols:{purpose:'academic-schedule',objects:['title','schedule-list']}}};draft.book.events=[{startDate:'2031-03-02',endDate:'2031-03-02',title:'입학식'}];draft.book.elementsByPage.symbols=[];draft.book.elementsByPage.annual=[];api.apply(draft,specApi.normalize({pageTypes:{annual:'split-info'}},catalog));for(const item of [draft.book.elementsByPage.symbols.find(item=>item.role==='schedule-list'),draft.book.elementsByPage.annual.find(item=>item.role==='annual-schedule-list')]){assert.equal(item.type,'event-list');assert.equal(item.binding,'calendar.events');assert.equal(item.displayMode,'all');assert.equal(item.columns,'auto');assert.equal(item.autoShrink,true)}});
