import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';
const source=fs.readFileSync(new URL('../apps/designer-studio/ai-design-settings.js',import.meta.url),'utf8');const context={};vm.createContext(context);vm.runInContext(source,context);const api=context.ACDLAIDesignSettings;
test('AI design settings keep independently versioned rule identities',()=>{assert.equal(api.VERSION.module,'1.1.0');assert.match(api.VERSION.promptSet,/@/);assert.match(api.VERSION.pageRules,/@/);assert.match(api.VERSION.qualityProfile,/@/)});
test('AI design summary derives the new-template structure without mutating it',()=>{const project={productType:{category:'desk',pageSize:{width:260,height:180,unit:'mm'}},settings:{year:2028,startMonth:3},book:{pages:[{role:'cover'},{role:'month'},{role:'month'}]}};const before=JSON.stringify(project),result=api.summary(project);assert.equal(result.pageCount,3);assert.deepEqual([...result.roles],['표지','월력']);assert.equal(JSON.stringify(project),before)});
test('mock design session keeps conditions, versions and page-role result parts',()=>{const session=api.createSession({variantCount:3,scope:'template',schoolLevel:'elementary'});assert.equal(session.variants.length,3);assert.equal(session.conditions.schoolLevel,'elementary');assert.equal(session.scope,'template');assert.ok(session.variants.every(item=>item.assets.length&&item.styles.length&&item.layout&&item.pagePlans.length===5));assert.deepEqual([...session.variants[0].pagePlans.map(item=>item.role)],['cover','annual','month','month-back','back-cover']);assert.equal(session.versions.module,'1.1.0')});
test('selecting a proposal returns a new session and keeps the previous session untouched',()=>{const session=api.createSession({variantCount:2}),selected=api.selectVariant(session,session.variants[1].id);assert.equal(session.selectedVariantId,null);assert.equal(selected.selectedVariantId,session.variants[1].id);assert.equal(selected.variants.filter(item=>item.selected).length,1)});
test('a new template enters the editor only after selecting a proposal',()=>{const session=api.createSession({variantCount:2});assert.equal(api.canEnterEditor(session),false);const selected=api.selectVariant(session,session.variants[0].id);assert.equal(api.canEnterEditor(selected),true);const draft=api.createDraft(selected,'2026-09-04T00:00:00.000Z');assert.equal(draft.status,'selected-not-applied');assert.equal(draft.selectedVariant.id,selected.selectedVariantId);assert.equal(draft.session.versions.module,'1.1.0')});
test('regenerating one page role does not replace the design set or other roles',()=>{const session=api.createSession({variantCount:2}),variant=session.variants[0],next=api.regeneratePage(session,variant.id,'month');assert.equal(next.variants[0].pagePlans.find(item=>item.role==='month').revision,1);assert.equal(next.variants[0].pagePlans.find(item=>item.role==='cover').revision,0);assert.equal(next.variants[1].pagePlans.find(item=>item.role==='month').revision,0);assert.equal(session.variants[0].pagePlans.find(item=>item.role==='month').revision,0)});
test('new template creation routes through the nine-step settings flow before editor entry',()=>{const html=fs.readFileSync(new URL('../apps/designer-studio/index.html',import.meta.url),'utf8');assert.match(html,/const NEW_TEMPLATE_SETTINGS_PAGES=\["basic","school","colors","fonts","masters","events","export","graphics","ai-design"\]/);assert.match(html,/createFromSetup\(\)[\s\S]*newTemplateSetupInProgress=true;[\s\S]*openResourceModal\("basic"\)/);assert.doesNotMatch(html,/function createFromSetup\(\)[^\n]*setTimeout\(\(\)=>el\("saveBtn"\)\?\.click\(\),0\)/);assert.match(html,/AI 디자인 초안으로 편집 시작/)});
