import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';

const runtime=fs.readFileSync(new URL('../apps/designer-studio/calendar-type-platform-runtime.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../apps/designer-studio/index.html',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migrations/202609070003_calendar_type_platform.sql',import.meta.url),'utf8');

test('calendar type gallery exposes filters, status, settings and direct template creation',()=>{for(const value of ['typeFamilyFilter','typeStatusFilter','typeSearch','data-configure-type','data-create-type','typePlatformAdd'])assert.match(runtime,new RegExp(value))});
test('calendar type cards use compact product illustrations with real size differences',()=>{const css=fs.readFileSync(new URL('../apps/designer-studio/calendar-type-platform.css',import.meta.url),'utf8');assert.match(runtime,/function productVisual\(type\)/);assert.match(runtime,/calendar-product-visual/);assert.match(runtime,/Math\.sqrt\(\(Number\(size\.width\)/);assert.doesNotMatch(runtime,/type\.orientation==='portrait'\?'▯':'▭'/);assert.match(css,/minmax\(240px,1fr\)/);assert.match(css,/min-height:326px/);assert.match(css,/calendar-product-desk \.calendar-product-stand/)});
test('new calendar type opens one blank settings form without a clone menu',()=>{assert.match(runtime,/function blankType\(\)/);assert.match(runtime,/typePlatformAdd'\)\.onclick=\(\)=>detail\(blankType\(\),\{draft:true\}\)/);assert.match(runtime,/finishedSize:\{width:0,height:0/);assert.match(runtime,/name:''/);assert.doesNotMatch(runtime,/data-add-mode|현재 유형 복제|typeAddMenu/)});
test('desk type policy shows one cover-inside sharing checkbox and a calculated minimum',()=>{assert.match(runtime,/ctpShareCoverBack/);assert.match(runtime,/표지 안쪽면을 첫 월력 뒷면으로 함께 사용/);assert.doesNotMatch(runtime,/id="ctpBackCoverBack"/);assert.match(runtime,/calendarTypeMinimum/);assert.match(runtime,/applyDeskSurfacePolicy/);assert.ok(runtime.indexOf("page.role==='back-cover-back'")<runtime.indexOf("page.role==='back-cover-front'"))});
test('basic settings omit derived policies and calendar type save gives visible feedback',()=>{assert.match(runtime,/visiblePolicies=\{cover:'표지',backCover:'뒷표지',monthlyFront:'월력 앞면',monthlyBack:'월력 뒷면'\}/);assert.match(runtime,/표지 안쪽면/);assert.match(runtime,/button\.textContent='저장 중…'/);assert.match(runtime,/button\.textContent='저장 완료'/);assert.match(runtime,/button\.textContent='저장 실패'/);assert.match(runtime,/setTimeout\(exitAfterSave,650\)/)});
test('calendar type detail keeps its compatibility field and guards unsaved closing',()=>{assert.match(runtime,/annual\.closest\('label'\)\.hidden=true/);assert.doesNotMatch(runtime,/annual\.closest\('label'\)\.remove\(\)/);assert.match(runtime,/변경사항이 저장되지 않습니다/);assert.match(runtime,/detailBaseline=JSON\.stringify\(readDetail\(\)\)/);assert.match(runtime,/>닫기<\/button>/)});
test('calendar type save returns to the screen that opened the manager',()=>{assert.match(runtime,/managerOrigin='service-home'/);assert.match(runtime,/openManager\('service-home'\)/);assert.match(runtime,/openManager\('template-create'\)/);assert.match(runtime,/managerOrigin==='service-home'/);assert.match(runtime,/entryScreen'\)\?\.classList\.remove\('hidden'\)/)});
test('desk surface compaction runs after base constraints and preserves the outer back cover',()=>{assert.match(runtime,/const result=baseApplyConstraints\(type\);applyDeskSurfacePolicy\(type\)/);assert.match(runtime,/closing=pages\.find\(page=>page\.role==='back-cover-back'\)\|\|pages\.find\(page=>page\.role==='back-cover-front'\)/)});
test('calendar type UI uses the same control height and card hierarchy as template settings',()=>{const css=fs.readFileSync(new URL('../apps/designer-studio/calendar-type-platform.css',import.meta.url),'utf8');assert.match(css,/\.type-platform-shell button\{min-height:40px/);assert.match(css,/\.type-setting-card/);assert.match(css,/\.type-fields/);assert.match(css,/\.type-detail-footer/)});
test('calendar type workspace owns its background and scrolls only the card gallery',()=>{const css=fs.readFileSync(new URL('../apps/designer-studio/calendar-type-platform.css',import.meta.url),'utf8'),overrides=fs.readFileSync(new URL('../apps/designer-studio/designer-studio-overrides.css',import.meta.url),'utf8');assert.match(overrides,/\.type-manager-overlay\{[^}]*box-sizing:border-box[^}]*background:#eef2f7[^}]*overflow:hidden/);assert.match(css,/\.type-platform-shell\{[^}]*grid-template-rows:auto auto minmax\(0,1fr\)[^}]*height:100%[^}]*overflow:hidden/);assert.match(css,/\.type-gallery\{[^}]*min-height:0[^}]*overflow-x:hidden[^}]*overflow-y:auto/)});
test('reselect type action follows the shared template settings button scale',()=>{const css=fs.readFileSync(new URL('../apps/designer-studio/calendar-type-platform-basic.css',import.meta.url),'utf8');assert.match(css,/\.calendar-type-context-head > button \{[\s\S]*min-width: 108px;[\s\S]*height: 36px;[\s\S]*border-radius: 8px;[\s\S]*font-size: 10px;/)});
test('new templates start blank and show type constraints inside basic settings',()=>{assert.match(runtime,/creationMode='blank'/);assert.match(runtime,/renderBasicTypeContext/);assert.match(runtime,/빈 페이지 구성에서 시작하며 디자인과 AI 이미지는 새로 만듭니다/);assert.doesNotMatch(runtime,/creationProductPage|creationStartMode|기존 템플릿을 디자인 참고자료로 사용/);assert.match(runtime,/calendarTypeSnapshot/)});
test('direct type creation clears a stale library base before building the selected type',()=>{const start=runtime.match(/function startCreation\(typeId\)\{([^\n]+)\}/)?.[1]||'';assert.match(start,/clearNewTemplateBase\(\)/);assert.ok(start.indexOf('clearNewTemplateBase()')<start.indexOf('createFromSetup()'));assert.match(html,/calendar-type-platform-runtime\.js\?v=20260911\.4/)});
test('direct type creation keeps the type chooser visible until setup succeeds and recovers on failure',()=>{const start=runtime.match(/function startCreation\(typeId\)\{([^\n]+)\}/)?.[1]||'';assert.ok(start.indexOf('createFromSetup()')<start.indexOf("overlay?.classList.add('hidden')"));assert.match(start,/catch\(error\)/);assert.match(start,/overlay\?\.classList\.remove\('hidden'\)/);assert.match(start,/newTemplateSetupInProgress=false/)});
test('legacy local calendar type manager is bypassed when the common domain is loaded',()=>{assert.match(html,/calendar-type-domain\.js/);assert.match(html,/calendar-type-platform-runtime\.js/);assert.match(fs.readFileSync(new URL('../apps/designer-studio/features/template-settings-workspace-runtime.js',import.meta.url),'utf8'),/if\(window\.ACDLCalendarTypeDomain\)return/)});
test('Supabase schema owns five normalized calendar type tables without changing template rows',()=>{for(const table of ['calendar_product_families','calendar_type_definitions','calendar_type_sizes','calendar_type_capabilities','calendar_type_page_rules'])assert.match(migration,new RegExp(`create table if not exists public\\.${table}`));assert.doesNotMatch(migration,/update public\.template_(projects|versions|assets)/)});
