import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
import {validateGraphicMetadata,uploadChunk,createGraphic,listGraphics,updateGraphic} from '../server/graphic-library.js';
const source=await readFile(new URL('../apps/designer-studio/graphic-library-runtime.js',import.meta.url),'utf8');const window={crypto:{randomUUID}};vm.runInNewContext(source,{window});const model=window.ACDLGraphicLibraryModel,graphic={id:randomUUID(),originalAssetId:randomUUID(),name:'검증 이미지',width:2400,height:1800,createdAt:'2026-10-01'};
test('frame replacement preserves layout and pins the original',()=>{const frame={type:'image-frame',x:8,y:24,width:84,height:48,image:{fit:'contain',scale:2,src:'old'}};model.replaceImage(frame,graphic,'blob:new');assert.deepEqual([frame.x,frame.y,frame.width,frame.height],[8,24,84,48]);assert.equal(frame.image.fit,'contain');assert.equal(frame.image.scale,1);assert.equal(frame.graphicSource.originalAssetId,graphic.originalAssetId)});
test('school linked frames cannot be changed through common library',()=>assert.throws(()=>model.replaceImage({type:'image-frame',image:{binding:'school.profile.logo'}},graphic,'new')));
test('background is fixed to the page and serializes pinned identity',()=>{const item=model.placement(graphic,'acdl-asset://'+graphic.originalAssetId,{mode:'background'});assert.equal(item.width,100);assert.equal(item.height,100);assert.equal(item.locked,true);assert.equal(JSON.parse(JSON.stringify(item)).graphicSource.originalAssetId,graphic.originalAssetId)});
test('metadata rejects unsupported categories',()=>assert.throws(()=>validateGraphicMetadata({...graphic,category:'school'})));
test('chunked originals survive catalog reload and archive keeps asset identity',async()=>{const originalFetch=globalThis.fetch;process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';const objects=new Map(),assets=[];let bucketExists=false;
 globalThis.fetch=async(url,opt={})=>{const u=new URL(url),p=u.pathname,r=value=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});if(p.includes('/rest/v1/template_assets')){if(opt.method==='POST'){const row={id:randomUUID(),...JSON.parse(opt.body)};assets.push(row);return r([row])}return r(assets.filter(a=>u.searchParams.get('content_hash')==='eq.'+a.content_hash))}if(p==='/storage/v1/bucket/common-graphics')return bucketExists?r({id:'common-graphics',public:false}):new Response('{}',{status:404});if(p==='/storage/v1/bucket'&&opt.method==='POST'){const config=JSON.parse(opt.body);assert.equal(config.id,'common-graphics');assert.equal(config.public,false);assert.ok(config.allowed_mime_types.includes('application/octet-stream'));assert.ok(config.allowed_mime_types.includes('application/json'));bucketExists=true;return r({})}if(p.includes('/object/sign/'))return r({signedURL:'/object/sign/test'});if(p.includes('/object/list/'))return r([...objects.keys()].filter(k=>k.startsWith('graphics-library/')).map(k=>({name:k.split('/').at(-1)})));if(p.includes('/object/template-assets')||p.includes('/object/common-graphics')){const bucket=p.includes('/object/common-graphics')?'common-graphics':'template-assets',key=p.split('/object/'+bucket+'/')[1];if(opt.method==='POST'){const allowed=bucket==='template-assets'?['image/png','image/jpeg','image/webp','image/svg+xml']:['application/json','application/octet-stream'];if(!allowed.includes(opt.headers['Content-Type']))return new Response('',{status:415})}if(opt.method==='DELETE'){for(const key of JSON.parse(opt.body).prefixes)objects.delete(key);return r({})}if(opt.method==='POST'){objects.set(key,typeof opt.body==='string'?Buffer.from(opt.body):opt.body);return r({})}return objects.has(key)?new Response(objects.get(key)):new Response('',{status:404})}throw Error(url)};
 try{const uploadId=randomUUID(),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l0AAAAASUVORK5CYII=','base64');await uploadChunk({uploadId,index:0,total:1,data:png.toString('base64')});const saved=await createGraphic({name:'共通',category:'background',width:1,height:1,uploadId,total:1,mimeType:'image/png',previewDataUrl:'data:image/png;base64,'+png.toString('base64')});assert.equal((await listGraphics())[0].id,saved.id);const archived=await updateGraphic({id:saved.id,status:'archived'});assert.equal(archived.originalAssetId,saved.originalAssetId);assert.equal((await listGraphics())[0].status,'archived');assert.ok([...objects.values()].some(v=>Buffer.isBuffer(v)&&v.equals(png)))}finally{globalThis.fetch=originalFetch;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY}});

test('selected file supplies an editable default name without extension',()=>{assert.equal(model.defaultName('학교 봄 풍경.JPG'),'학교 봄 풍경');assert.equal(model.defaultName('spring.photo.webp'),'spring.photo');assert.equal(model.defaultName('가'.repeat(130)+'.png').length,120)});

test('library addition reuses a selected optional empty frame without removing other objects',()=>{
 const empty={id:'element.ai-month-back.image.3.0.0',type:'image-frame',emptyBehavior:'placeholder',x:12,y:15,width:70,height:65,image:{src:'',binding:'',fit:'cover'}},other={id:'other',type:'text'},items=[other,empty];
 assert.equal(model.emptyFrameTarget(items,empty),empty);assert.equal(model.emptyFrameTarget(items,null),empty);model.replaceImage(empty,graphic,'new');assert.equal(model.emptyFrameTarget(items,empty),null);assert.equal(items.length,2);assert.equal(empty.id,'element.ai-month-back.image.3.0.0');assert.equal(empty.image.src,'new');assert.deepEqual([empty.x,empty.y,empty.width,empty.height],[12,15,70,65]);
});
test('library never guesses among multiple empty frames or fills required and bound slots',()=>{
 const make=id=>({id,type:'image-frame',emptyBehavior:'placeholder',image:{src:'',binding:''}}),a=make('element.ai-month-back.image.a'),b=make('element.ai-month-back.image.b');
 assert.equal(model.emptyFrameTarget([a,b],null),null);assert.equal(model.emptyFrameTarget([a,b],b),b);
 for(const item of [{...a,required:true},{...a,image:{binding:'school.profile.building'}},{...a,image:{binding:'calendar.monthlyImages.current'}},{...a,assetRef:{ref:'template',id:'missing'}}])assert.equal(model.emptyFrameTarget([item],item),null);
});
