import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
// Minimal DOM fixture exercises the real menu, form, and persistence callbacks.
class Element{
 constructor(tag='div',attrs={}){this.tag=tag;this.attrs=attrs;this.children=[];this.listeners={};this.value=attrs.value||'';this.hidden='hidden'in attrs;this.disabled=false;this.textContent='';this.style={setProperty(){},removeProperty(){}};this.classList={toggle(){}};}
 set innerHTML(html){this.children=[];const stack=[this],voids=new Set(['input','img','br','hr']);for(const token of html.matchAll(/<\/?([\w-]+)([^>]*)>/g)){const [raw,tag,attributes]=token;if(raw.startsWith('</')){if(stack.at(-1).tag===tag)stack.pop();continue;}const attrs={};for(const a of attributes.matchAll(/([\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=a[2]??'';const e=new Element(tag,attrs);stack.at(-1).appendChild(e);if(!voids.has(tag))stack.push(e);}for(const e of this.all())if(e.tag==='select')e.value=e.children.find(c=>c.tag==='option')?.attrs.value||'';}
 get id(){return this.attrs.id;}set id(v){this.attrs.id=v;}get innerHTML(){return '';}all(){return this.children.flatMap(e=>[e,...e.all()]);}appendChild(e){e.parent=this;this.children.push(e);return e;}
 matches(selector){if(selector.startsWith('#'))return this.attrs.id===selector.slice(1);const m=selector.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);if(m)return m[1]in this.attrs&&(m[2]===undefined||this.attrs[m[1]]===m[2]);return this.tag===selector;}
 querySelectorAll(selector){return this.all().filter(e=>selector.split(',').some(s=>e.matches(s.trim())));}querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 get elements(){const entries=this.all().filter(e=>e.attrs.name);const result={namedItem:name=>entries.find(e=>e.attrs.name===name)};entries.forEach(e=>result[e.attrs.name]=e);return result;}
 get options(){return this.children.filter(e=>e.tag==='option');}get dataset(){return Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]));}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}async fire(type,target=this){const event={target,preventDefault(){}};for(const fn of this.listeners[type]||[])await fn(event);if(this['on'+type])await this['on'+type](event);}
 closest(selector){return this.matches(selector)?this:this.parent?.closest(selector);}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}getBoundingClientRect(){return {top:0,bottom:200};}scrollIntoView(){}showModal(){this.open=true;}close(){this.open=false;this.fire('close');}reset(){for(const e of this.all())if(e.attrs.name)e.value=e.tag==='select'?e.options[0]?.attrs.value||'':e.attrs.value||'';}
}
function setup(){
 const body=new Element('body'),document={body,createElement:tag=>{const e=new Element(tag);if(tag==='canvas'){e.getContext=()=>({drawImage(){}});e.toDataURL=()=> 'data:image/webp;base64,UklGRgAAAABXRUJQ';}return e;},getElementById:id=>body.querySelector('#'+id)};let records=[],packages=[],requests=[],fail=false;
 const window={document,crypto:{randomUUID},URL:{revokeObjectURL(){}},confirm:()=>true,requestAnimationFrame:fn=>fn(),addEventListener(){},ACDLAdminAuth:{authorizedFetch:async(path,options={})=>{if(!options.method)return {ok:true,json:async()=>({graphics:records,packages})};const input=JSON.parse(options.body);requests.push(input);if(fail)return {ok:false,status:500,json:async()=>({error:'TEST_FAILED'})};if(input.operation==='create-package'){const pkg={id:randomUUID(),schemaVersion:'graphic-package.v1',name:input.name,size:input.size,tags:input.tags,status:'active',revision:1,pages:{},createdAt:'2026-10-08'};packages.push(pkg);return {ok:true,json:async()=>({package:pkg})};}if(input.operation==='update-package'){const pkg=packages.find(p=>p.id===input.id);Object.assign(pkg,input,{revision:pkg.revision+1});return {ok:true,json:async()=>({package:pkg})};}if(input.operation==='preview-vector'){const scene={shapes:[{type:'ellipse',paint:'linear',fill:1,stroke:-1,x:0,y:0,width:100,height:100,radius:0,rotate:0,strokeWidth:0,opacity:.5,path:''}]};const design=window.ACDLGraphicVectorDesign.normalize({...input.design,scene});return {ok:true,json:async()=>({generation:{generationId:randomUUID(),design,engine:'openai-vector-scene',model:'test',generatedAt:'2026-10-07'}})};}if(['generate-vector','save-package-page'].includes(input.operation)){const graphic={id:randomUUID(),...input,design:window.ACDLGraphicVectorDesign.normalize(input.design),status:'active',mimeType:'image/svg+xml',previewAssetId:'asset',originalAssetId:'asset',width:1300,height:900,byteSize:1000,createdAt:'2026-10-07',setInfo:window.ACDLGraphicVectorDesign.setInfo(input.design)};records.push(graphic);if(input.operation==='save-package-page'){const pkg=packages.find(p=>p.id===input.packageId);const updated={...pkg,pages:{...pkg.pages,[input.page]:{graphicId:graphic.id,derivedFromCoverId:input.page==='cover'?null:pkg.pages.cover.graphicId}},thumbnailDataUrl:input.page==='cover'?input.thumbnailDataUrl:pkg.thumbnailDataUrl,revision:pkg.revision+1};packages[packages.indexOf(pkg)]=updated;return {ok:true,json:async()=>({graphic,package:updated})};}return {ok:true,json:async()=>({graphic})};}const g=records.find(g=>g.id===input.id);Object.assign(g,input);return {ok:true,json:async()=>({graphic:g})};}},ACDLTemplateRemotePersistence:{assetObjectUrl:async()=> 'blob:test'}};
 const context=vm.createContext({window,document,Image:class{naturalWidth=1300;naturalHeight=900;async decode(){}},FileReader:class{}});for(const file of ['graphic-vector-design.js','graphic-package-model.js','graphic-library-packages.js','graphic-library-generator.js','graphic-library-runtime.js'])vm.runInContext(readFileSync(new URL('../apps/designer-studio/'+file,import.meta.url),'utf8'),context);
 return {window,document,requests,records,packages,setFailure:value=>fail=value,$:id=>document.getElementById(id)};
}
test('library defaults to assets; generator stores pure vector recipe, reopens variants, and preserves originals',async()=>{
 const env=setup(),{$,window,requests,records}=env;await window.ACDLGraphicLibrary.open();assert.equal($('graphicAssetsPanel').hidden,false);assert.equal($('graphicUploadForm').hidden,true);assert.equal($('graphicGeneratePanel').hidden,true);
 const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');assert.equal($('graphicGeneratePanel').hidden,false);
 const form=$('graphicGenerateForm');form.elements.composition.value='ai';form.elements.page.value='month-front';form.elements.variation.value='seasonal';await form.fire('input',form.elements.page);assert.equal($('graphicMonthPreview').hidden,true);assert.equal($('graphicMonthGrid').querySelectorAll('figure').length,0);
 await form.fire('submit');assert.equal($('graphicMonthPreview').hidden,false);assert.equal($('graphicMonthGrid').querySelectorAll('figure').length,12);await dialog.querySelector('[data-gl-preview="example"]').fire('click');assert.equal($('graphicDesignPreview').querySelectorAll('div').length,2);await dialog.querySelector('[data-gl-preview="pure"]').fire('click');assert.equal($('graphicDesignPreview').querySelectorAll('div').length,0);
 assert.equal(records.length,0);await $('graphicSaveGenerated').fire('click');assert.equal(requests.length,2);assert.equal(requests[0].operation,'preview-vector');assert.equal(requests[1].operation,'generate-vector');assert.ok(!JSON.stringify(requests[0]).includes('학교 전경 사진'));assert.equal(records.length,1);assert.equal($('graphicAssetsPanel').hidden,false);
 const first=records[0];await dialog.fire('click',dialog.querySelector('[data-gl-action="variant"]'));assert.equal($('graphicGeneratePanel').hidden,false);assert.equal(form.elements.page.value,'month-front');form.elements.scale.value='120';await form.fire('input',form.elements.scale);await form.fire('submit');await $('graphicSaveGenerated').fire('click');assert.equal(requests.at(-1).parentGraphicId,first.id);assert.equal(first.design.scale,100);assert.equal(records[1].design.scale,120);
 await window.ACDLGraphicLibrary.open('pick');assert.equal(dialog.querySelector('[data-gl-action="background"]'),null);assert.equal(dialog.querySelector('[data-gl-action="image"]'),null);
});
test('failed generation leaves settings visible and unlocks save for retry',async()=>{const env=setup();await env.window.ACDLGraphicLibrary.open();const dialog=env.$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');const form=env.$('graphicGenerateForm');form.elements.composition.value='ai';env.setFailure(true);await form.fire('submit');assert.equal(env.records.length,0);assert.equal(env.$('graphicGeneratePanel').hidden,false);assert.equal(form.querySelector('[type="submit"]').disabled,false);assert.match(env.$('graphicLibraryFeedback').textContent,/실패/);});

test('AI generation uses current page settings, preserves previous scene for edits and supports undo',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm');form.elements.composition.value='ai';assert.equal($('graphicSaveGenerated').disabled,true);assert.equal($('graphicDesignPreview').querySelectorAll('img').length,0);form.elements.page.value='symbols';await form.fire('input',form.elements.page);await form.fire('submit');assert.equal(env.requests[0].design.page,'symbols');assert.equal(env.requests[0].operation,'preview-vector');assert.equal($('graphicSaveGenerated').disabled,false);form.elements.scale.value='120';await form.fire('input',form.elements.scale);assert.equal($('graphicSaveGenerated').disabled,true);$('graphicGenerationPrompt').value='큰 원을 줄이고 작은 잎을 넣어줘';await $('graphicGenerateForm').fire('submit');assert.equal(env.requests.at(-1).design.scale,120);assert.ok(env.requests.at(-1).previousScene);assert.equal(env.requests.at(-1).prompt,'큰 원을 줄이고 작은 잎을 넣어줘');await $('graphicUndoGenerated').fire('click');assert.equal(form.elements.scale.value,100);await $('graphicSaveGenerated').fire('click');assert.equal(env.records[0].design.scale,100);assert.ok(env.records[0].design.scene);});
test('asset details edit metadata without changing original identity',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');$('graphicGenerateForm').elements.composition.value='ai';await $('graphicGenerateForm').fire('submit');await $('graphicSaveGenerated').fire('click');const first=env.records[0],original=first.originalAssetId;await dialog.fire('click',dialog.querySelector('[data-gl-action="preview"]'));assert.equal($('graphicViewer').open,true);const form=$('graphicMetadataForm');form.elements.name.value='새 이름';form.elements.tags.value='봄, 표지';await form.fire('submit');assert.equal(first.name,'새 이름');assert.equal(first.tags,'봄, 표지');assert.equal(first.originalAssetId,original);assert.match($('graphicMetadataStatus').textContent,/저장/);});

test('failed AI regeneration preserves a generated scene and permits retry',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="generate"]').fire('click');$('graphicGenerateForm').elements.composition.value='ai';await $('graphicGenerateForm').fire('submit');env.setFailure(true);await $('graphicGenerateForm').fire('submit');assert.equal($('graphicDesignPreview').querySelectorAll('img').length,1);assert.equal($('graphicSaveGenerated').disabled,false);assert.match($('graphicGenerationStatus').textContent,/유지/);});

test('cover composition generates locally, changes selected values, saves and reopens a variant',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm');assert.equal(form.elements.composition.value,'cover-circle-01');await form.fire('submit');assert.equal(env.requests.length,0);assert.match($('graphicGenerationStatus').textContent,/구성 01/);const before=$('graphicDesignPreview').querySelector('img').attrs.src;form.elements.gradient.value='50';await form.fire('input',form.elements.gradient);assert.equal($('graphicSaveGenerated').disabled,true);await form.fire('submit');assert.equal(env.requests.length,0);assert.notEqual($('graphicDesignPreview').querySelector('img').attrs.src,before);await $('graphicSaveGenerated').fire('click');assert.equal(env.records[0].design.composition,'cover-circle-01');assert.equal(env.records[0].design.coverTuning.tone,50);assert.equal(env.records[0].generationInfo.engine,'cover-circle-01');await dialog.fire('click',dialog.querySelector('[data-gl-action="variant"]'));assert.equal(form.elements.composition.value,'cover-circle-01');});
test('cover prompt updates visible controls and saved recipe while unsupported changes preserve result',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm');form.elements.instruction.value='봄 색상, 그라데이션 115%, 장식 밀도 85%, 크기 120%';await form.fire('submit');assert.equal(form.elements.gradient.value,115);assert.equal(form.elements.density.value,85);assert.equal(form.elements.scale.value,120);assert.equal(env.requests.length,0);const before=$('graphicDesignPreview').querySelector('img').attrs.src;$('graphicGenerationPrompt').value='사진을 왼쪽으로 이동하고 꽃을 추가';await $('graphicGenerateForm').fire('submit');assert.equal($('graphicDesignPreview').querySelector('img').attrs.src,before);assert.match($('graphicGenerationStatus').textContent,/지원하지/);$('graphicGenerationPrompt').value='장식 적게, 바탕 #FFF8EE';await $('graphicGenerateForm').fire('submit');assert.equal(form.elements.density.value,70);assert.equal(form.elements.color0.value,'#FFF8EE');assert.match($('graphicGenerationStatus').textContent,/적용/);await $('graphicSaveGenerated').fire('click');assert.equal(env.records[0].design.colors[0],'#FFF8EE');assert.equal(env.records[0].generationInfo.prompt,'장식 적게, 바탕 #FFF8EE');});


test('package flow creates cover first, derives pages, reopens saved results and edits one page without replacing others',async()=>{
 const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="packages"]').fire('click');assert.equal($('graphicPackagePanel').hidden,false);assert.equal($('graphicGeneratePanel').hidden,true);
 assert.equal($('graphicPackageHome').hidden,false);assert.equal($('graphicPackageInfo').hidden,true);await $('graphicPackageNew').fire('click');assert.equal($('graphicPackageInfo').hidden,false);assert.equal($('graphicGeneratePanel').hidden,true);const pf=$('graphicPackageForm');pf.elements.name.value='블루 패키지';await pf.fire('submit');assert.equal(env.packages.length,1);const front=()=>$('graphicPackagePage').options.find(o=>o.attrs.value==='month-front');assert.ok('disabled' in front().attrs); // HTML boolean is represented as an attribute by this fixture.
 await $('graphicGenerateForm').fire('submit');await $('graphicSaveGenerated').fire('click');assert.equal(env.packages[0].pages.cover.graphicId,env.records[0].id);assert.equal($('graphicGeneratePanel').hidden,false);assert.equal('disabled' in front().attrs,false);
 $('graphicPackagePage').value='month-front';await $('graphicPackagePage').fire('change');const form=$('graphicGenerateForm');assert.equal(form.elements.page.value,'month-front');assert.equal(form.elements.composition.value,'package-family');assert.equal(form.elements.page.disabled,true);await form.fire('submit');await $('graphicSaveGenerated').fire('click');const coverId=env.packages[0].pages.cover.graphicId,monthId=env.packages[0].pages['month-front'].graphicId;assert.equal(env.records[1].design.familyTuning.tone,100);assert.equal(env.requests.filter(r=>r.operation==='preview-vector').length,0);
 await dialog.querySelector('[data-gl-tab="assets"]').fire('click');$('graphicAssetType').value='package';await $('graphicAssetType').fire('input');assert.equal(dialog.querySelectorAll('[data-gl-action="preview"]').length,0);assert.equal(dialog.querySelectorAll('[data-gl-package-action="open"]').length,2);
 await dialog.fire('click',dialog.querySelector('[data-gl-package-action="open"]'));$('graphicPackagePage').value='cover';await $('graphicPackagePage').fire('change');assert.equal($('graphicDesignPreview').querySelectorAll('img').length,1);form.elements.gradient.value='115';await form.fire('input',form.elements.gradient);await form.fire('submit');await $('graphicSaveGenerated').fire('click');assert.notEqual(env.packages[0].pages.cover.graphicId,coverId);assert.equal(env.packages[0].pages['month-front'].graphicId,monthId);assert.equal(env.records.find(g=>g.id===coverId).design.coverTuning.tone,100);
});


test('package entry displays saved packages directly; metadata save failure does not enter the workspace',async()=>{
 const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="packages"]').fire('click');assert.equal($('graphicPackageHome').hidden,false);assert.equal($('graphicPackageBrowse'),null);assert.equal($('graphicPackageExisting'),null);assert.equal($('graphicPackageWorkspace').hidden,true);assert.equal($('graphicGeneratePanel').hidden,true);
 await $('graphicPackageNew').fire('click');const form=$('graphicPackageForm');form.elements.name.value='실패 후 재시도';env.setFailure(true);await form.fire('submit');assert.equal($('graphicPackageInfo').hidden,false);assert.equal($('graphicGeneratePanel').hidden,true);assert.equal(form.elements.name.value,'실패 후 재시도');env.setFailure(false);await form.fire('submit');assert.equal($('graphicPackageInfo').hidden,true);assert.equal($('graphicPackageWorkspace').hidden,false);assert.equal($('graphicGeneratePanel').hidden,false);assert.equal(env.packages.length,1);
 await $('graphicPackageEditInfo').fire('click');assert.equal($('graphicGeneratePanel').hidden,true);form.elements.name.value='이름 변경';await form.fire('submit');assert.equal($('graphicPackageWorkspace').hidden,false);assert.equal(env.packages[0].name,'이름 변경');
 await $('graphicLibraryDialog').querySelector('[data-gl-package-home]').fire('click');assert.equal($('graphicPackageHome').hidden,false);assert.equal($('graphicPackageBrowseList').closest('section'),$('graphicPackageHome'));const card=$('graphicPackageBrowseList').querySelector('[data-gl-package-edit]');await $('graphicPackageBrowseList').fire('click',card);assert.equal($('graphicPackageWorkspace').hidden,false);assert.equal($('graphicGeneratePanel').hidden,false);
});
test('vector form places basic fields above the preview and exposes only one generation/edit prompt',async()=>{
 const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm'),basics=$('graphicGeneratorBasics'),prompts=$('graphicGeneratorPrompts');assert.equal(form.elements.name.closest('section'),basics);assert.equal(form.elements.composition.closest('section'),basics);assert.equal(form.elements.palette.closest('aside'),prompts);assert.equal(form.elements.instruction.closest('aside'),prompts);assert.equal(form.querySelectorAll('[name="instruction"]').length,1);assert.equal(form.elements.method,undefined);assert.equal($('graphicRegenerate'),null);assert.equal(form.elements.style.closest('label').hidden,true);
 await form.fire('submit');$('graphicGenerationPrompt').value='조금 진하게';await form.fire('submit');assert.equal(form.elements.gradient.value,115);await $('graphicUndoGenerated').fire('click');assert.equal(form.elements.gradient.value,100);assert.equal(form.elements.instruction.value,'');
});
