import test from 'node:test';
import assert from 'node:assert/strict';
import '../apps/designer-studio/graphic-vector-design.js';
import {validateGraphicSvg} from '../server/graphic-library.js';
const model=globalThis.ACDLGraphicVectorDesign;
test('all supported background pages export vector-only assets without layout examples',()=>{
 for(const page of Object.keys(model.pages))for(const style of ['circle','curve','diagonal']){const design=model.normalize({page,style}),svg=model.svg(design);assert.equal(validateGraphicSvg(svg),svg);assert.ok(svg.includes('linearGradient'));assert.ok(!/<(?:image|text|filter|foreignObject)\b/.test(svg));assert.ok(!svg.includes('학교'));assert.ok(model.zones(design).length>0);}
});
test('illustration SVG has no full-page opaque background',()=>{for(const style of ['plant','stationery']){const p=model.normalize({kind:'illustration',style});assert.equal(model.zones(p).length,0);assert.ok(!model.svg(p).includes('<rect width="1300"'));validateGraphicSvg(model.svg(p));}});
test('monthly variations preserve composition and include academic month order',()=>{const p=model.normalize({page:'month-front',variation:'monthly'}),set=model.setInfo(p);assert.deepEqual(set.monthOrder,[3,4,5,6,7,8,9,10,11,12,1,2]);assert.equal(set.scope,'background-only');assert.equal(set.months.length,12);assert.notEqual(model.svg(p,3),model.svg(p,4));assert.equal(model.svg(p,3).replace(/#[\da-f]{6}/gi,'COLOR'),model.svg(p,4).replace(/#[\da-f]{6}/gi,'COLOR'));assert.equal(model.setInfo({page:'cover'}),null);});
test('stored recipe reproduces the exact vector and custom palette',()=>{const p=model.normalize({colors:['#ffffff','#aabbcc','#ddeeff','#112233'],gradient:0,scale:120});assert.equal(model.svg(p),model.svg(JSON.parse(JSON.stringify(p))));assert.ok(model.svg(p).includes('fill="#aabbcc"'));});
test('invalid generated inputs cannot inject markup or expensive unbounded settings',()=>{for(const input of [{colors:['red','blue','white','black']},{scale:999},{style:'<script>'},{kind:'background',style:'plant'},{size:'unknown'},{gradient:NaN}])assert.throws(()=>model.normalize(input));});
test('uploaded SVG rejects scripts, external content, filters, entities, and malformed markup',()=>{for(const content of ['<script>alert(1)</script>','<image href="https://example.com/a.png"/>','<rect onclick="evil()"/>','<foreignObject/>','<filter/>','<rect fill="url(https://example.com)"/>','<rect fill="&#106;avascript"/>','<g style="color:red"/>','<g><circle/></rect>'])assert.throws(()=>validateGraphicSvg(`<svg xmlns="http://www.w3.org/2000/svg">${content}</svg>`));assert.throws(()=>validateGraphicSvg('<!DOCTYPE svg><svg></svg>'));});

test('gradient, density, scale and mirror change the actual vector; prompt applies bounded controls',()=>{const model=globalThis.ACDLGraphicVectorDesign;for(const style of ['circle','curve','diagonal']){const base={style};for(const changes of [{gradient:0},{density:0},{density:80},{scale:125},{orientation:'mirror'}])assert.notEqual(model.svg(base),model.svg({...base,...changes}));}const result=model.applyPrompt({},'봄 색상, 장식 적게, 작게, 좌우 반전');assert.equal(result.design.palette,'spring');assert.equal(result.design.density,20);assert.equal(result.design.scale,75);assert.equal(result.design.orientation,'mirror');assert.equal(model.applyPrompt({},'지원하지 않는 요청').applied.length,0);});

test('cover composition retains circular photo geometry and changes actual vector parameters',()=>{const m=globalThis.ACDLGraphicVectorDesign,p=m.normalize({composition:'cover-circle-01'}),base=m.svg(p);for(const z of m.zones(p).filter(z=>z.type==='photo'))assert.ok(Math.abs(z.w*13-z.h*9)<.001);for(const update of [{gradient:0},{density:0},{density:100},{scale:120},{palette:'spring',colors:m.palettes.spring}])assert.notEqual(base,m.svg({...p,...update}));assert.ok(!base.includes('gl-safe'));assert.ok(!base.includes('<image'));assert.equal(base,m.svg(JSON.parse(JSON.stringify(p))));});
test('cover prompt applies bounded percentages and colors without changing its composition',()=>{const m=globalThis.ACDLGraphicVectorDesign;const p=m.normalize({composition:'cover-circle-01'});const r=m.applyPrompt(p,'가을 색상, 그라데이션 80%, 밀도 25%, 크기 110%, 강조 1 #ABCDEF');assert.equal(r.design.gradient,80);assert.equal(r.design.density,25);assert.equal(r.design.scale,110);assert.equal(r.design.colors[1],'#ABCDEF');assert.equal(r.design.composition,p.composition);assert.equal(m.applyPrompt(p,'그라데이션 120%').applied.length,0);assert.equal(m.applyPrompt(p,'사진 이동').applied.length,0);});

test('reference cover tuning preserves reserved zones and decoration count while changing each control',()=>{const p=model.normalize({composition:'cover-circle-01',coverTuning:{tone:100,density:100,scale:100}}),base=model.svg(p);for(const key of ['tone','density','scale'])for(const value of [50,150]){const q={...p,coverTuning:{...p.coverTuning,[key]:value}},svg=model.svg(q);assert.notEqual(svg,base);assert.deepEqual(model.zones(q),model.zones(p));assert.equal((svg.match(/<circle/g)||[]).length,(base.match(/<circle/g)||[]).length);validateGraphicSvg(svg)}assert.equal(base,model.svg(JSON.parse(JSON.stringify(p))));assert.throws(()=>model.normalize({...p,coverTuning:{tone:100,density:49,scale:100}}));});

test('independent backgrounds ignore content layout, vary by page and preserve legacy reproduction',()=>{const m=globalThis.ACDLGraphicVectorDesign,p=m.normalize({composition:'cover-circle-01',backgroundRevision:2,coverTuning:{tone:100,density:100,scale:100}});for(const page of ['cover','month-back','month-front','cover-inside']){const q=page==='cover'?p:m.normalize({...p,page,composition:null,coverTuning:null,familyTuning:p.coverTuning});const svg=m.svg(q);validateGraphicSvg(svg);assert.ok(!/clipPath|mask|<image|<text|filter/.test(svg));assert.equal(svg,m.svg({...q,layout:'text-only'}));assert.equal(svg,m.svg(JSON.parse(JSON.stringify(q))));for(const key of ['tone','density','scale']){const tuning=q.coverTuning?'coverTuning':'familyTuning';const changed=m.svg({...q,[tuning]:{...q[tuning],[key]:125}});assert.notEqual(changed,svg);assert.equal((changed.match(/<circle/g)||[]).length,(svg.match(/<circle/g)||[]).length)}}const b=m.normalize({...p,page:'month-back',composition:null,coverTuning:null,familyTuning:p.coverTuning});assert.notEqual(m.svg(b),m.svg({...b,page:'month-front'}));assert.notEqual(m.svg(p),m.svg({...p,backgroundRevision:1}));assert.equal(m.normalize({composition:'cover-circle-01'}).backgroundRevision,1);});

test('terracotta palette can be selected, prompted and reproduced',()=>{const m=globalThis.ACDLGraphicVectorDesign,p=m.normalize({composition:'cover-circle-01',backgroundRevision:2,coverTuning:{tone:100,density:100,scale:100},palette:'terracotta'});assert.deepEqual(p.colors,m.palettes.terracotta);validateGraphicSvg(m.svg(p));assert.equal(m.svg(p),m.svg(JSON.parse(JSON.stringify(p))));const q=m.applyPrompt({...p,palette:'mist',colors:m.palettes.mist},'테라코타 색상');assert.equal(q.design.palette,'terracotta');assert.deepEqual(q.design.colors,p.colors);});

test('rectangle cover has one photo example, no footer band or content clipping, and fixed decoration count',()=>{const m=globalThis.ACDLGraphicVectorDesign,p=m.normalize({composition:'cover-rectangle-02',backgroundRevision:2,palette:'terracotta',coverTuning:{tone:100,density:100,scale:100}}),base=m.svg(p);assert.equal(p.style,'rectangle');assert.equal(p.layout,'single-photo');assert.equal(m.zones(p).filter(z=>z.type==='photo').length,1);assert.equal(m.zones(p).filter(z=>z.type==='footer').length,0);assert.ok(!/circle|clipPath|<image|<text|filter/.test(base));validateGraphicSvg(base);for(const key of ['tone','density','scale']){const q={...p,coverTuning:{...p.coverTuning,[key]:125}},svg=m.svg(q);assert.notEqual(svg,base);assert.equal((svg.match(/<rect/g)||[]).length,(base.match(/<rect/g)||[]).length);assert.deepEqual(m.zones(q),m.zones(p))}assert.equal(base,m.svg(JSON.parse(JSON.stringify(p))));});
