import test from 'node:test';
import assert from 'node:assert/strict';
import {curatedThemes,installCuratedIllustrations} from '../server/graphic-curated-library.js';
import {validateGraphicSvg,validateThumbnail} from '../server/graphic-library.js';
const model=globalThis.ACDLGraphicIllustrationModel;
function fixture(){const records=[],sources=[];return {records,sources,createRecord:async r=>{assert.ok(!records.some(x=>x.id===r.id));records.push(r);return r},storeAsset:async src=>{sources.push(src);return {id:'asset-'+sources.length}},validateSvg:validateGraphicSvg,validateThumbnail};}
test('eight directly authored vectors persist as two complete themes and reload without duplicates or overwriting edits',async()=>{const f=fixture(),added=await installCuratedIllustrations(f);assert.equal(added.length,10);assert.equal(f.sources.length,8);const themes=f.records.filter(r=>r.schemaVersion==='graphic-illustration-theme.v1'),graphics=f.records.filter(r=>r.schemaVersion==='graphic-library.v1');assert.deepEqual(graphics.map(g=>g.name),['연필','지우개','자','공책','벚꽃','해바라기','단풍잎','눈송이']);for(const t of themes){assert.equal(Object.keys(t.assets).length,4);assert.equal(model.validatePlan(t.plan,t).subjects.length,4);for(const a of Object.values(t.assets))assert.ok(graphics.some(g=>g.id===a.graphicId));}for(const g of graphics){assert.equal(g.generationInfo.engine,'direct-authored-vector');assert.equal(g.physicalSizeMm.width,40);assert.equal(g.printQuality.output,'not_run');assert.equal(g.vectorObject.parts.length,g.illustrationRecipe.scene.parts.length);const svg=Buffer.from(f.sources[graphics.indexOf(g)].split(',')[1],'base64').toString();assert.equal(validateGraphicSvg(svg),svg);assert.ok(!/<image|<text|href|filter/.test(svg));}graphics[0].name='관리자 수정';graphics[0].status='archived';assert.equal((await installCuratedIllustrations(f)).length,0);assert.equal(graphics[0].name,'관리자 수정');assert.equal(graphics[0].status,'archived');});
test('partial installation resumes existing immutable assets after a storage failure',async()=>{const f=fixture(),create=f.createRecord;let writes=0;f.createRecord=async r=>{if(++writes===3)throw Error('storage unavailable');return create(r)};await assert.rejects(()=>installCuratedIllustrations(f));assert.equal(f.records.length,2);const originals=f.records.map(r=>JSON.stringify(r));f.createRecord=create;await installCuratedIllustrations(f);assert.equal(f.records.length,10);assert.deepEqual(f.records.slice(0,2).map(r=>JSON.stringify(r)),originals);});
test('curated subjects use editable vector recipes with differentiated silhouettes and thumbnail previews',()=>{for(const theme of curatedThemes()){assert.equal(theme.items.length,4);const silhouettes=new Set();for(const item of theme.items){const r=model.normalize(item.recipe);assert.equal(r.subject,item.name);assert.ok(r.scene.parts.length>=2);silhouettes.add(JSON.stringify(r.scene.parts));assert.ok(validateThumbnail(item.thumbnailDataUrl));}assert.equal(silhouettes.size,4);}});
