import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
// Minimal DOM fixture exercises the real menu, form, and persistence callbacks.
class Element{
 constructor(tag='div',attrs={}){this.tag=tag;this.attrs=attrs;this.children=[];this.listeners={};this.value=attrs.value||'';this.hidden='hidden'in attrs;this.disabled=false;this.textContent='';this.style={setProperty(){},removeProperty(){}};this.classList={toggle(){}};}
 set innerHTML(html){this.children=[];const stack=[this],voids=new Set(['input','img','br','hr']);for(const token of html.matchAll(/<\/?([\w-]+)([^>]*)>/g)){const [raw,tag,attributes]=token;if(raw.startsWith('</')){if(stack.at(-1).tag===tag)stack.pop();continue;}const attrs={};for(const a of attributes.matchAll(/([\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=a[2]??'';const e=new Element(tag,attrs);stack.at(-1).appendChild(e);if(!voids.has(tag))stack.push(e);}for(const e of this.all())if(e.tag==='select')e.value=e.children.find(c=>c.tag==='option')?.attrs.value||'';}
 get id(){return this.attrs.id;}set id(v){this.attrs.id=v;}get innerHTML(){return '';}all(){return this.children.flatMap(e=>[e,...e.all()]);}appendChild(e){e.parent=this;this.children.push(e);return e;}
 matches(selector){if(selector.startsWith('#'))return this.attrs.id===selector.slice(1);const m=selector.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);if(m)return m[1]in this.attrs&&(m[2]===undefined||this.attrs[m[1]]===m[2]);return this.tag===selector;}
 querySelectorAll(selector){return this.all().filter(e=>selector.split(',').some(s=>e.matches(s.trim())));}querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 get elements(){const entries=this.all().filter(e=>e.attrs.name);const result={namedItem:name=>entries.find(e=>e.attrs.name===name)};entries.forEach(e=>result[e.attrs.name]=e);return result;}
 get options(){return this.children.filter(e=>e.tag==='option');}get dataset(){return Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]));}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}async fire(type,target=this){const event={target,preventDefault(){}};for(const fn of this.listeners[type]||[])await fn(event);if(this['on'+type])await this['on'+type](event);}
 closest(selector){return this.matches(selector)?this:this.parent?.closest(selector);}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}getBoundingClientRect(){return {top:0,bottom:200};}scrollIntoView(){}showModal(){this.open=true;}close(){this.open=false;this.fire('close');}reset(){for(const e of this.all())if(e.attrs.name)e.value=e.tag==='select'?e.options[0]?.attrs.value||'':e.attrs.value||'';}
}
function setup(){
 const body=new Element('body'),document={body,createElement:tag=>{const e=new Element(tag);if(tag==='canvas'){e.getContext=()=>({drawImage(){}});e.toDataURL=()=> 'data:image/webp;base64,UklGRgAAAABXRUJQ';}return e;},getElementById:id=>body.querySelector('#'+id)};let records=[],requests=[],fail=false;
 const window={document,crypto:{randomUUID},URL:{revokeObjectURL(){}},confirm:()=>true,requestAnimationFrame:fn=>fn(),addEventListener(){},ACDLAdminAuth:{authorizedFetch:async(path,options={})=>{if(!options.method)return {ok:true,json:async()=>({graphics:records})};const input=JSON.parse(options.body);requests.push(input);if(fail)return {ok:false,status:500,json:async()=>({error:'TEST_FAILED'})};if(input.operation==='preview-vector'){const scene={shapes:[{type:'ellipse',paint:'linear',fill:1,stroke:-1,x:0,y:0,width:100,height:100,radius:0,rotate:0,strokeWidth:0,opacity:.5,path:''}]};const design=window.ACDLGraphicVectorDesign.normalize({...input.design,scene});return {ok:true,json:async()=>({generation:{generationId:randomUUID(),design,engine:'openai-vector-scene',model:'test',generatedAt:'2026-10-07'}})};}if(input.operation==='generate-vector'){const graphic={id:randomUUID(),...input,design:window.ACDLGraphicVectorDesign.normalize(input.design),status:'active',mimeType:'image/svg+xml',previewAssetId:'asset',originalAssetId:'asset',width:1300,height:900,byteSize:1000,createdAt:'2026-10-07',setInfo:window.ACDLGraphicVectorDesign.setInfo(input.design)};records.push(graphic);return {ok:true,json:async()=>({graphic})};}const g=records.find(g=>g.id===input.id);Object.assign(g,input);return {ok:true,json:async()=>({graphic:g})};}},ACDLTemplateRemotePersistence:{assetObjectUrl:async()=> 'blob:test'}};
 const context=vm.createContext({window,document,Image:class{naturalWidth=1300;naturalHeight=900;async decode(){}},FileReader:class{}});for(const file of ['graphic-vector-design.js','graphic-library-generator.js','graphic-library-runtime.js'])vm.runInContext(readFileSync(new URL('../apps/designer-studio/'+file,import.meta.url),'utf8'),context);
 return {window,document,requests,records,setFailure:value=>fail=value,$:id=>document.getElementById(id)};
}
test('library defaults to assets; generator stores pure vector recipe, reopens variants, and preserves originals',async()=>{
 const env=setup(),{$,window,requests,records}=env;await window.ACDLGraphicLibrary.open();assert.equal($('graphicAssetsPanel').hidden,false);assert.equal($('graphicUploadForm').hidden,true);assert.equal($('graphicGeneratePanel').hidden,true);
 const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');assert.equal($('graphicGeneratePanel').hidden,false);
 const form=$('graphicGenerateForm');form.elements.composition.value='ai';form.elements.page.value='month-front';form.elements.variation.value='seasonal';await form.fire('input',form.elements.page);assert.equal($('graphicMonthPreview').hidden,true);assert.equal($('graphicMonthGrid').querySelectorAll('figure').length,0);
 await form.fire('submit');assert.equal($('graphicMonthPreview').hidden,false);assert.equal($('graphicMonthGrid').querySelectorAll('figure').length,12);await dialog.querySelector('[data-gl-preview="example"]').fire('click');assert.equal($('graphicDesignPreview').querySelectorAll('div').length,2);await dialog.querySelector('[data-gl-preview="pure"]').fire('click');assert.equal($('graphicDesignPreview').querySelectorAll('div').length,0);
 assert.equal(records.length,0);await $('graphicSaveGenerated').fire('click');assert.equal(requests.length,2);assert.equal(requests[0].operation,'preview-vector');assert.equal(requests[1].operation,'generate-vector');assert.ok(!JSON.stringify(requests[0]).includes('학교 전경 사진'));assert.equal(records.length,1);assert.equal($('graphicAssetsPanel').hidden,false);
 const first=records[0];await dialog.fire('click',dialog.querySelector('[data-gl-action="variant"]'));assert.equal($('graphicGeneratePanel').hidden,false);assert.equal(form.elements.page.value,'month-front');form.elements.scale.value='120';await form.fire('input',form.elements.scale);await form.fire('submit');await $('graphicSaveGenerated').fire('click');assert.equal(requests.at(-1).parentGraphicId,first.id);assert.equal(first.design.scale,100);assert.equal(records[1].design.scale,120);
 await window.ACDLGraphicLibrary.open('pick');assert.equal(dialog.querySelector('[data-gl-action="background"]'),null);assert.equal(dialog.querySelector('[data-gl-action="image"]'),null);
});
test('failed generation leaves settings visible and unlocks save for retry',async()=>{const env=setup();await env.window.ACDLGraphicLibrary.open();const dialog=env.$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');const form=env.$('graphicGenerateForm');form.elements.composition.value='ai';env.setFailure(true);await form.fire('submit');assert.equal(env.records.length,0);assert.equal(env.$('graphicGeneratePanel').hidden,false);assert.equal(form.querySelector('[type="submit"]').disabled,false);assert.match(env.$('graphicLibraryFeedback').textContent,/실패/);});

test('AI generation uses current page settings, preserves previous scene for edits and supports undo',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm');form.elements.composition.value='ai';assert.equal($('graphicSaveGenerated').disabled,true);assert.equal($('graphicDesignPreview').querySelectorAll('img').length,0);form.elements.page.value='symbols';await form.fire('input',form.elements.page);await form.fire('submit');assert.equal(env.requests[0].design.page,'symbols');assert.equal(env.requests[0].operation,'preview-vector');assert.equal($('graphicSaveGenerated').disabled,false);form.elements.scale.value='120';await form.fire('input',form.elements.scale);assert.equal($('graphicSaveGenerated').disabled,true);$('graphicGenerationPrompt').value='큰 원을 줄이고 작은 잎을 넣어줘';await $('graphicRegenerate').fire('click');assert.equal(env.requests.at(-1).design.scale,120);assert.ok(env.requests.at(-1).previousScene);assert.equal(env.requests.at(-1).prompt,'큰 원을 줄이고 작은 잎을 넣어줘');await $('graphicUndoGenerated').fire('click');assert.equal(form.elements.scale.value,100);await $('graphicSaveGenerated').fire('click');assert.equal(env.records[0].design.scale,100);assert.ok(env.records[0].design.scene);});
test('asset details edit metadata without changing original identity',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');$('graphicGenerateForm').elements.composition.value='ai';await $('graphicGenerateForm').fire('submit');await $('graphicSaveGenerated').fire('click');const first=env.records[0],original=first.originalAssetId;await dialog.fire('click',dialog.querySelector('[data-gl-action="preview"]'));assert.equal($('graphicViewer').open,true);const form=$('graphicMetadataForm');form.elements.name.value='새 이름';form.elements.tags.value='봄, 표지';await form.fire('submit');assert.equal(first.name,'새 이름');assert.equal(first.tags,'봄, 표지');assert.equal(first.originalAssetId,original);assert.match($('graphicMetadataStatus').textContent,/저장/);});

test('failed AI regeneration preserves a generated scene and permits retry',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();await $('graphicLibraryDialog').querySelector('[data-gl-tab="generate"]').fire('click');$('graphicGenerateForm').elements.composition.value='ai';await $('graphicGenerateForm').fire('submit');env.setFailure(true);await $('graphicRegenerate').fire('click');assert.equal($('graphicDesignPreview').querySelectorAll('img').length,1);assert.equal($('graphicSaveGenerated').disabled,false);assert.match($('graphicGenerationStatus').textContent,/유지/);});

test('cover composition generates locally, changes selected values, saves and reopens a variant',async()=>{const env=setup(),{$}=env;await env.window.ACDLGraphicLibrary.open();const dialog=$('graphicLibraryDialog');await dialog.querySelector('[data-gl-tab="generate"]').fire('click');const form=$('graphicGenerateForm');assert.equal(form.elements.composition.value,'cover-circle-01');await form.fire('submit');assert.equal(env.requests.length,0);assert.match($('graphicGenerationStatus').textContent,/구성 01/);const before=$('graphicDesignPreview').querySelector('img').attrs.src;form.elements.gradient.value='0';await form.fire('input',form.elements.gradient);assert.equal($('graphicSaveGenerated').disabled,true);await form.fire('submit');assert.equal(env.requests.length,0);assert.notEqual($('graphicDesignPreview').querySelector('img').attrs.src,before);await $('graphicSaveGenerated').fire('click');assert.equal(env.records[0].design.composition,'cover-circle-01');assert.equal(env.records[0].design.gradient,0);assert.equal(env.records[0].generationInfo.engine,'cover-circle-01');await dialog.fire('click',dialog.querySelector('[data-gl-action="variant"]'));assert.equal(form.elements.composition.value,'cover-circle-01');});
