import test from 'node:test';import assert from 'node:assert/strict';
import {generateVectorPreview,generationInput,buildVectorPrompt,VECTOR_SCENE_SCHEMA} from '../server/graphic-vector-generation.js';
import {validateGraphicSvg} from '../server/graphic-library.js';
const scene={shapes:[{type:'path',paint:'linear',fill:1,stroke:-1,x:0,y:0,width:100,height:100,radius:0,rotate:0,strokeWidth:0,opacity:.6,path:'M0 0Q80 20 100 0L100 80Z'}]};
test('all pages pass actual role, safe zones and selections to AI and produce validated vector scenes',async()=>{for(const page of Object.keys(globalThis.ACDLGraphicVectorDesign.pages)){let request;const result=await generateVectorPreview({design:{page,layout:'two-photos',density:70,scale:120},prompt:'작은 잎 장식',previousScene:scene},{getKey:async()=> 'test-only',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');request=JSON.parse(options.body);return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(scene)}]}]}))}});assert.equal(request.store,false);assert.equal(request.text.format.strict,true);assert.deepEqual(request.text.format.schema,VECTOR_SCENE_SCHEMA);assert.ok(request.input[1].content.includes(globalThis.ACDLGraphicVectorDesign.pages[page]));assert.match(request.input[1].content,/Previous scene/);assert.equal(result.design.page,page);assert.ok(result.design.scene);validateGraphicSvg(result.svg);assert.match(result.svg,/clip-path="url\(#gl-safe\)"/);assert.ok(!/학교|사진|text>|image /.test(result.svg));}});
test('missing key, refusal, incomplete and bad upstream scenes never become generated successes',async()=>{
 await assert.rejects(generateVectorPreview({design:{}},{getKey:async()=>''}),e=>e.code==='AI_VECTOR_NOT_CONFIGURED');
 const bodies=[{status:'incomplete'}, {status:'completed',output:[{content:[{type:'refusal',refusal:'no'}]}]}, {status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({shapes:[{...scene.shapes[0],path:'<script/>'}]})}]}]}];
 for(const body of bodies)await assert.rejects(generateVectorPreview({design:{}},{getKey:async()=> 'test-only',fetchImpl:async()=>new Response(JSON.stringify(body))}),e=>/^AI_VECTOR_/.test(e.code));
});
test('scene bounds and free prompts are validated before provider call',()=>{assert.throws(()=>generationInput({design:{scene:{shapes:Array(81).fill(scene.shapes[0])}}}));assert.throws(()=>generationInput({design:{},prompt:'a'.repeat(2001)}));assert.throws(()=>generationInput({design:{},previousScene:{shapes:[{...scene.shapes[0],x:Infinity}]}}));assert.match(buildVectorPrompt(generationInput({design:{page:'planner'}})),/계획·메모/);});
test('page layouts reserve distinct actual content zones and illustrations remain transparent',()=>{const m=globalThis.ACDLGraphicVectorDesign;assert.notDeepEqual(m.zones(m.normalize({page:'cover',layout:'single-photo'})),m.zones(m.normalize({page:'cover',layout:'two-photos'})));const svg=m.svg({kind:'illustration',style:'plant',page:'symbols',scene});validateGraphicSvg(svg);assert.ok(!svg.includes('rect width="1300"'));assert.ok(!svg.includes('gl-safe'));const mirrored=m.svg({page:'cover',scene,orientation:'mirror'});assert.ok(mirrored.indexOf('clip-path=')<mirrored.indexOf('translate(1300 0)'));});
