import test from 'node:test';import assert from 'node:assert/strict';
import {upscaleCandidates,replaceImageReferences,applyUpscale} from '../server/production-upscale.js';
import {sealProductionDocument,documentHash} from '../server/production-corrections.js';
const adapter=globalThis.ACDLProductionEditorAdapter;
test('target reached is excluded even below recommended and below-minimum remains an admin candidate',()=>{
 const item=dpi=>({placements:[{measurable:true,effectiveDpi:dpi}]});assert.equal(upscaleCandidates([item(260),item(150),item(300),{vector:true,...item(100)}],{upscaleTargetDpi:250}).length,1);
});
test('replacement handles shared sources and package refs without mutating original',()=>{const source='package-asset://a',original={template:{pages:[{objects:[{payload:{src:source,assetRef:{ref:'package',id:'a'}}},{payload:{src:source}}]}]},editorProject:{private:true}};const result=replaceImageReferences(original,new Map([[source,'production-asset://b']]));assert.equal(result.template.pages[0].objects[0].payload.assetRef.ref,'url');assert.equal(result.template.pages[0].objects[1].payload.src,'production-asset://b');assert.equal(original.template.pages[0].objects[0].payload.src,source);assert.equal(result.editorProject,undefined);});
test('applying reviewed result saves a new round-trip revision and preserves placement and receipt',async()=>{
 const requestId='11111111-1111-4111-a111-111111111111',revisionId='22222222-2222-4222-a222-222222222222',assetId='33333333-3333-4333-a333-333333333333',source='package-asset://original',resultHash='a'.repeat(64);
 const project={format:'acdl-project',settings:{year:2027},productType:{category:'desk',pageSize:{width:260,height:180,unit:'mm'}},template:{masters:{calendar:{}},masterElements:{},resources:{},metadata:{}},book:{pageInstances:[{id:'p1',role:'cover-front'}],elementsByPage:{p1:[]},school:{},events:[],monthlyImages:{},monthlyQuotes:{}}};
 const document={template:{pages:[{id:'p1',size:{width:260,height:180},objects:[{id:'photo',type:'image',frame:{x:10,y:20,width:100,height:70},payload:{src:source,fit:'contain',placement:{scale:1.2}}}]}]},dataset:{school:{},calendar:{events:[]}}};document.editorProject=adapter.createProject(project,document,requestId);const revision={id:revisionId,document,document_hash:sealProductionDocument(document)},receipt={id:requestId,snapshot:{assets:[]}},before=structuredClone(revision);
 const old=globalThis.fetch;process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';let saved;
 globalThis.fetch=async(url,options={})=>{if(url.includes('calendar_production_correction_assets'))return Response.json([{id:assetId,content_hash:resultHash}]);if(url.includes('save_calendar_production_revision')){saved=JSON.parse(options.body);return Response.json([{id:saved.p_id}]);}throw Error('unexpected');};
 try{await applyUpscale(receipt,revision,{id:'job',status:'done',payload:{production:{documentHash:revision.document_hash}},report:{results:[{source,status:'completed',assetId,resultHash}]}},[source],'admin','44444444-4444-4444-a444-444444444444');assert.deepEqual(revision,before);assert.deepEqual(saved.p_document.template.pages[0].objects[0].frame,document.template.pages[0].objects[0].frame);assert.equal(saved.p_document.template.pages[0].objects[0].payload.src,`production-asset://${assetId}`);assert.equal(saved.p_document_hash,documentHash(saved.p_document));assert.deepEqual(adapter.toDocument(saved.p_document.editorProject),adapter.withoutEditor(saved.p_document));}finally{globalThis.fetch=old;}
});
