import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import handler from '../api/production-print-preflight.js';import {documentHash} from '../server/production-corrections.js';
const requestId='11111111-1111-4111-a111-111111111111',revisionId='22222222-2222-4222-a222-222222222222';
const document={template:{pages:[{id:'p1',size:{unit:'mm'},objects:[]}]},editorProject:{template:{masters:{},resources:{},masterElements:{}},settings:{},productType:{pageSize:{width:260,height:180}},book:{pageInstances:[{id:'p1',number:1}],elementsByPage:{p1:[]}}}},hash=documentHash(document);
const revision={id:revisionId,revision_number:5,document_hash:hash,document};
process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';const old=fetch;
function res(){return {setHeader(){},statusCode:200,end(value){this.body=JSON.parse(value);}};}
function setup({admin=true,rows=[revision]}={}){const calls=[];globalThis.fetch=async(url,options={})=>{calls.push({url,method:options.method||'GET'});if(url.includes('/auth/v1/user'))return Response.json({id:requestId});if(url.includes('template_admins'))return Response.json(admin?[{user_id:requestId}]:[]);if(url.includes('calendar_production_revisions'))return Response.json(rows);if(url.includes('calendar_production_requests'))return Response.json([{id:requestId,status:'reviewing'}]);if(url.includes('template_print_preflight_jobs'))return Response.json([]);throw Error(url);};return calls;}
function request(overrides={}){return {method:'POST',headers:{authorization:'Bearer test'},body:{requestId,revisionId,documentHash:hash,...overrides}};}
test('existing inspection boundary binds exact receipt/revision/content and does not queue legacy work',async()=>{const calls=setup(),response=res(),before=structuredClone(revision);await handler(request(),response);assert.equal(response.statusCode,200);const i=response.body.inspection;assert.equal(i.identity.contentHash,hash);assert.equal(i.identity.revisionId,revisionId);assert.equal(i.status,'ready');assert.equal(i.jobCreated,false);assert.equal(i.finalApproved,false);assert.equal(i.rendererId,'template-editor-review-dom.v1');assert.equal(i.blockerCode,undefined);assert.deepEqual(revision,before);assert.ok(calls.every(x=>x.method==='GET'));assert.ok(calls.find(x=>x.url.includes('calendar_production_revisions')).url.includes(`request_id=eq.${requestId}&id=eq.${revisionId}`));});
test('foreign, stale or corrupt revision cannot use current template as fallback',async()=>{setup({rows:[]});let response=res();await handler(request(),response);assert.equal(response.statusCode,404);setup();response=res();await handler(request({documentHash:'0'.repeat(64)}),response);assert.equal(response.statusCode,409);const corrupt=structuredClone(revision);corrupt.document.productionIntegrity={hashScheme:'sorted-json.v1'};setup({rows:[corrupt]});response=res();await handler(request(),response);assert.equal(response.statusCode,409);});
test('non-admin and malformed requests cannot read frozen content',async()=>{let calls=setup({admin:false}),response=res();await handler(request(),response);assert.equal(response.statusCode,403);assert.ok(!calls.some(x=>x.url.includes('calendar_production_revisions')));calls=setup();response=res();await handler(request({revisionId:'bad'}),response);assert.equal(response.statusCode,400);assert.ok(!calls.some(x=>x.url.includes('calendar_production_revisions')));});
test('correction final action and refresh branch before legacy template publication and worker request',()=>{const source=readFileSync(new URL('../apps/designer-studio/template-library-runtime.js',import.meta.url),'utf8');for(const name of ['runFinalPreflight','refreshPreflightResult']){const body=source.split(`async function ${name}(){`)[1];assert.ok(body.trimStart().startsWith('if(preflightRecord?.productionProject)return runProductionFinalPreflight();'));}});
test('final request requires matching quick inspection and explicit warning acknowledgement before any job write',async()=>{
 for(const extra of [{},{quickInspection:{revisionId,documentHash:hash,errors:1,warnings:0}},{quickInspection:{revisionId,documentHash:hash,errors:0,warnings:1}}]){const calls=setup(),response=res();await handler(request({action:'request',...extra}),response);assert.equal(response.statusCode,409);assert.ok(calls.every(call=>call.method==='GET'));}
});
test('foreign origin cannot enqueue saved correction; status lookup never creates work',async()=>{
 let calls=setup(),response=res();const req=request({action:'request',quickInspection:{revisionId,documentHash:hash,errors:0,warnings:0}});req.headers={authorization:'Bearer test',origin:'https://foreign.invalid',host:'editor.invalid'};await handler(req,response);assert.equal(response.statusCode,400);assert.ok(calls.every(call=>call.method==='GET'));
 calls=setup();response=res();await handler(request({action:'status'}),response);assert.equal(response.statusCode,200);assert.deepEqual(response.body.jobs,[]);assert.ok(calls.every(call=>call.method==='GET'));
});
test.after(()=>{globalThis.fetch=old;});
