import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/production-corrections.js';
process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';const old=globalThis.fetch;
const id='11111111-1111-4111-a111-111111111111',revisionId='22222222-2222-4222-a222-222222222222';
function response(){return {statusCode:200,setHeader(){},status(c){this.statusCode=c;return this},json(b){this.body=b;return this},end(b){this.body=b?JSON.parse(b):null;return this}};}
function setup({admin=true,status='reviewing',revisions=[]}={}){const calls=[];globalThis.fetch=async(url,options={})=>{calls.push({url,options});if(url.includes('/auth/v1/user'))return new Response(JSON.stringify({id}));if(url.includes('template_admins'))return new Response(JSON.stringify(admin?[{user_id:id}]:[]));if(url.includes('calendar_production_requests'))return new Response(JSON.stringify([{id,status,snapshot:{document:{template:{pages:[]}},assets:[]}}]));if(url.includes('/calendar_production_revisions?'))return new Response(JSON.stringify(revisions));if(url.includes('/calendar_production_correction_assets?'))return new Response('[]');if(url.includes('/rpc/'))return new Response(JSON.stringify([{id:revisionId,revision_number:1}]));throw Error(url);};return calls;}
const req=()=>({method:'POST',headers:{authorization:'Bearer token'},body:{id:revisionId,requestId:id,baseRevisionId:null,patches:[],note:'첫 교정본'}});
test('non-admin cannot access correction snapshots',async()=>{const calls=setup({admin:false}),res=response();await handler(req(),res);assert.equal(res.statusCode,403);assert.equal(calls.length,2);});
test('stale version and approved receipt cannot create revisions',async()=>{setup({revisions:[{id:revisionId,document:{template:{pages:[]}}}]});let res=response();const request=req();request.body.id='33333333-3333-4333-a333-333333333333';await handler(request,res);assert.equal(res.statusCode,409);setup({status:'approved'});res=response();await handler(req(),res);assert.equal(res.statusCode,409);});
test('new correction uses server receipt data and leaves original receipt untouched',async()=>{const calls=setup(),res=response();await handler(req(),res);assert.equal(res.statusCode,201);const mutation=calls.find(c=>c.options.method==='POST');assert.ok(mutation.url.includes('/rpc/save_calendar_production_revision'));const body=JSON.parse(mutation.options.body);assert.deepEqual(body.p_document,{template:{pages:[]}});assert.equal(body.p_created_by,id);assert.equal(calls.some(c=>c.options.method==='PATCH'),false);});
test.after(()=>globalThis.fetch=old);
