import test from 'node:test';import assert from 'node:assert/strict';
import handler from '../api/production-print-images.js';import {documentHash} from '../server/production-corrections.js';
import {createHash} from 'node:crypto';
const original=fetch,id='11111111-1111-4111-a111-111111111111',revisionId='22222222-2222-4222-a222-222222222222',assetId='33333333-3333-4333-a333-333333333333';
process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';
const document={productionIntegrity:{hashScheme:'sorted-json.v1'},template:{pages:[{id:'p1',size:{unit:'mm'},objects:[{id:'photo',type:'image',frame:{width:10,height:10},payload:{src:`production-asset://${assetId}`}}]}]}};
function setup({admin=true,missing=false,path=`${id}/${id}/${assetId}`}={}){const calls=[];globalThis.fetch=async url=>{calls.push(url);if(url.includes('/auth/v1/user'))return new Response(JSON.stringify({id}));if(url.includes('template_admins'))return new Response(JSON.stringify(admin?[{user_id:id}]:[]));if(url.includes('calendar_production_revisions'))return new Response(JSON.stringify(missing?[]:[{id:revisionId,revision_number:5,document,document_hash:documentHash(document)}]));if(url.includes('calendar_production_requests'))return new Response(JSON.stringify([{id,owner_id:id,snapshot:{assets:[{id:assetId,path,byteSize:24,mimeType:'image/png'}]}}]));if(url.includes('/storage/v1/object/')){const bytes=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(bytes);bytes.write('IHDR',12);bytes.writeUInt32BE(1000,16);bytes.writeUInt32BE(1000,20);return new Response(bytes);}throw Error(url);};return calls;}
function res(){return {statusCode:200,setHeader(){},end(value){this.body=JSON.parse(value);}};}
const req=()=>({method:'GET',headers:{authorization:'Bearer test'},query:{requestId:id,revisionId,assetId}});
test('admin inspection reads the immutable source and returns version-bound dimensions and DPI',async()=>{const calls=setup(),response=res();await handler(req(),response);assert.equal(response.statusCode,200);assert.equal(response.body.report.pixelWidth,1000);assert.equal(response.body.report.placements[0].effectiveDpi,2540);assert.equal(response.body.report.revisionId,revisionId);assert.ok(calls.some(url=>url.includes(`request_id=eq.${id}&id=eq.${revisionId}`)));assert.equal(calls.some(url=>url.includes('/object/sign/')),false);});
test('non-admin and unrelated asset requests do not read storage',async()=>{let calls=setup({admin:false}),response=res();await handler(req(),response);assert.equal(response.statusCode,403);assert.equal(calls.some(url=>url.includes('calendar_production_revisions')),false);calls=setup();response=res();await handler({...req(),query:{...req().query,assetId:id}},response);assert.equal(response.statusCode,400);assert.equal(calls.some(url=>url.includes('/storage/')),false);});
test('missing versions and foreign paths are blocked without reading another original',async()=>{let calls=setup({missing:true}),response=res();await handler(req(),response);assert.equal(response.statusCode,404);calls=setup({path:`other/${assetId}`});response=res();await handler(req(),response);assert.ok(response.statusCode>=400);assert.equal(calls.some(url=>url.includes('/storage/')),false);});
test('changed content during an inspection is rejected before reading originals',async()=>{const calls=setup(),response=res();await handler({...req(),query:{...req().query,contentHash:'different'}},response);assert.equal(response.statusCode,409);assert.equal(response.body.error,'PRINT_DOCUMENT_CONTENT_CHANGED');assert.equal(calls.some(url=>url.includes('/storage/')),false);});
test('canonical content mismatch has an actionable response instead of INTERNAL_ERROR',async()=>{setup();const mocked=fetch;globalThis.fetch=async url=>{const response=await mocked(url);if(url.includes('calendar_production_revisions')){const data=await response.json();data[0].document_hash='0'.repeat(64);return new Response(JSON.stringify(data));}return response;};const response=res();await handler(req(),response);assert.equal(response.statusCode,409);assert.equal(response.body.error,'PRINT_DOCUMENT_HASH_MISMATCH');assert.ok(response.body.message.includes('내용'));});
test('legacy jsonb revision reaches the image inspection API without a resave',async()=>{setup();const mocked=fetch;let historicalHash;globalThis.fetch=async url=>{const response=await mocked(url);if(url.includes('calendar_production_revisions')){const rows=await response.json(),doc=rows[0].document;delete doc.productionIntegrity;historicalHash=createHash('sha256').update(JSON.stringify(doc)).digest('hex');const reverse=value=>Array.isArray(value)?value.map(reverse):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).reverse().map(key=>[key,reverse(value[key])])):value;rows[0].document=reverse(doc);rows[0].document_hash=historicalHash;return new Response(JSON.stringify(rows));}return response;};const response=res();await handler(req(),response);assert.equal(response.statusCode,200);assert.equal(response.body.report.documentHash,historicalHash);assert.equal(response.body.report.integrity.storedHashVerified,false);assert.equal(response.body.report.pixelWidth,1000);});
test.after(()=>{globalThis.fetch=original;});
