import test from 'node:test';
import assert from 'node:assert/strict';
import {documentHash} from '../server/production-corrections.js';
import {productionImagePlan, inspectProductionImageBytes} from '../server/production-print-images.js';
const source='production-asset://11111111-1111-4111-a111-111111111111';
function fixture(){const document={template:{pages:[{id:'p1',size:{unit:'mm'},objects:[{id:'photo',type:'image',frame:{x:0,y:0,width:100,height:100},payload:{assetRef:{ref:'url',src:source},fit:'cover',placement:{scale:2}}},{id:'logo',type:'semantic-object',role:'school-logo',frame:{x:0,y:0,width:20,height:20},payload:{image:source}},{id:'song',type:'semantic-object',role:'school-song',frame:{x:0,y:0,width:90,height:90},payload:{image:source}}]}]}};return {id:'v5',revision_number:5,document,document_hash:documentHash(document)};}
function png(width=1000,height=1000){const bytes=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(bytes);bytes.write('IHDR',12);bytes.writeUInt32BE(width,16);bytes.writeUInt32BE(height,20);return bytes;}
test('a single original is inspected at every placement and compound image geometry stays unresolved',()=>{const revision=fixture(),before=structuredClone(revision),plan=productionImagePlan(revision),bytes=png(),report=inspectProductionImageBytes(plan,source,{byteSize:24,mimeType:'image/png'},bytes);assert.equal(plan.sources.length,1);assert.equal(plan.uses.length,3);assert.equal(report.placements[0].effectiveDpi,127);assert.equal(report.placements[0].status,'warning');assert.equal(report.placements[1].effectiveDpi,1270);assert.equal(report.placements[1].status,'passed');assert.equal(report.placements[2].status,'unresolved');assert.equal(report.placements[2].effectiveDpi,null);assert.equal(report.finalApproved,false);assert.equal(report.cmykDerived,false);assert.deepEqual(revision,before);});
test('size, media type, source SHA and unrelated sources are checked without a fallback',()=>{const plan=productionImagePlan(fixture()),bytes=png();assert.throws(()=>inspectProductionImageBytes(plan,source,{byteSize:23,mimeType:'image/png'},bytes),/크기/);assert.throws(()=>inspectProductionImageBytes(plan,source,{byteSize:24,mimeType:'image/jpeg'},bytes),/형식/);assert.throws(()=>inspectProductionImageBytes(plan,source,{byteSize:24,mimeType:'image/png',content_hash:'bad'},bytes),/SHA/);assert.throws(()=>inspectProductionImageBytes(plan,'production-asset://other',{byteSize:24},bytes),/사용된 원본/);});
test('corrupted frozen document cannot be inspected as its stored version',()=>{const revision=fixture();revision.document.template.pages[0].objects[0].frame.width=5;assert.throws(()=>productionImagePlan(revision),/해시/);});
test('invisible objects are excluded and ambiguous or nested placements are never measured as a whole parent',()=>{const revision=fixture(),page=revision.document.template.pages[0];page.objects[0].visible=false;page.objects[1].payload.second='production-asset://other';page.objects.push({id:'group',type:'group',children:[{id:'nested',type:'image',frame:{width:5,height:5},payload:{src:source}}]});revision.document_hash=documentHash(revision.document);const plan=productionImagePlan(revision);assert.equal(plan.uses.some(use=>use.objectId==='photo'),false);assert.ok(plan.uses.filter(use=>use.objectId==='logo').every(use=>!use.measurable));assert.equal(plan.uses.find(use=>use.objectId==='nested').measurable,false);});
