import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtemp,writeFile,readFile,mkdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {documentHash} from '../server/production-corrections.js';
import {inspectProductionIcc,convertRasterToCmyk,prepareProductionCmykImages} from '../tools/lib/production-cmyk-images.mjs';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
function profile(){const name=Buffer.from('Japan Color 2011 Coated\0'),b=Buffer.alloc(156+name.length);b.writeUInt32BE(b.length,0);b.write('CMYK',16);b.write('acsp',36);b.writeUInt32BE(1,128);b.write('desc',132);b.writeUInt32BE(144,136);b.writeUInt32BE(12+name.length,140);b.write('desc',144);b.writeUInt32BE(name.length,152);name.copy(b,156);return b;}
test('production ICC must match the specified SHA and Japan Color 2011 identity',()=>{const p=profile();assert.equal(inspectProductionIcc(p,hash(p)).outputConditionIdentifier,'Japan Color 2011 Coated');assert.throws(()=>inspectProductionIcc(p,'0'.repeat(64)),/SHA/);const q=Buffer.from(p);q.write('Other',156);assert.throws(()=>inspectProductionIcc(q,hash(q)),/Japan/);});
test('transparent images are blocked before conversion, without white compositing',async()=>{let calls=0;await assert.rejects(convertRasterToCmyk('source','output','icc',{runCommand:async()=>{calls++;return {stdout:'1|False|Undefined|'};},srgbProfilePath:'srgb'}),/투명/);assert.equal(calls,1);});
test('CMYK preparation verifies original hash, preserves originals and never grants print approval',async()=>{const root=await mkdtemp(path.join(tmpdir(),'production-cmyk-'));try{const originals=path.join(root,'originals');await mkdir(originals);const id='11111111-1111-4111-a111-111111111111',source=`production-asset://${id}`,bytes=Buffer.from('immutable-original');await writeFile(path.join(originals,id),bytes);const icc=profile(),iccPath=path.join(root,'icc');await writeFile(iccPath,icc);const document={template:{pages:[]}},contentHash=documentHash(document);const inspection={schemaVersion:'production-image-inspection.v1',revisionId:'v5',documentHash:'legacy',plan:{revisionId:'v5',documentHash:'legacy',contentHash,sources:[source]},results:[{revisionId:'v5',documentHash:'legacy',contentHash,source,sourceHash:hash(bytes),byteSize:bytes.length,pixelWidth:10,pixelHeight:20,placements:[]}]};const options={inspection,document,sourceDir:originals,outputDir:path.join(root,'derived'),iccPath,expectedIccSha256:hash(icc),convertImage:async(a,b)=>{assert.deepEqual(await readFile(a),bytes);await writeFile(b,'test-derived');return {bytes:Buffer.from('test-derived'),info:{width:10,height:20},engine:'test-only',inputProfileBasis:'explicit-srgb'};}};const manifest=await prepareProductionCmykImages(options);assert.equal(manifest.finalApproved,false);assert.equal(manifest.derived[0].sourceHash,hash(bytes));assert.equal(manifest.derived[0].finalApproved,false);assert.deepEqual(await readFile(path.join(originals,id)),bytes);await assert.rejects(prepareProductionCmykImages(options),/EEXIST/);const wrong=structuredClone(inspection);wrong.results[0].sourceHash='0'.repeat(64);await assert.rejects(prepareProductionCmykImages({...options,inspection:wrong,outputDir:path.join(root,'bad')}),/원본 SHA/);const failure=JSON.parse(await readFile(path.join(root,'bad','failure.json'),'utf8'));assert.equal(failure.failedSource,source);assert.equal(failure.completed,0);assert.equal(failure.contentHash,contentHash);assert.equal(failure.finalApproved,false);await assert.rejects(readFile(path.join(root,'bad','manifest.json')),/ENOENT/);}finally{await rm(root,{recursive:true,force:true});}});
test('actual image-only conversion writes four-component JPEG without changing pixels',async t=>{try{execFileSync('convert',['-version'],{stdio:'ignore'});await readFile('/usr/share/color/icc/ghostscript/default_cmyk.icc');}catch{t.skip('ImageMagick and technical-test ICC are not installed');return;}const root=await mkdtemp(path.join(tmpdir(),'cmyk-engine-'));try{const src=path.join(root,'source.ppm'),out=path.join(root,'derived.jpg');await writeFile(src,Buffer.concat([Buffer.from('P6\n2 1\n255\n'),Buffer.from([255,0,0,0,0,255])]));const result=await convertRasterToCmyk(src,out,'/usr/share/color/icc/ghostscript/default_cmyk.icc',{srgbProfilePath:'/usr/share/color/icc/ghostscript/srgb.icc'});assert.equal(result.info.components,4);assert.equal(result.info.width,2);assert.equal(result.info.height,1);}finally{await rm(root,{recursive:true,force:true});}});

test('CLI rejects mixed bundle inputs and unknown options before creating output',()=>{for(const args of [['--bundle-dir','input','--inspection','other'],['--unknown','value']]){const result=(()=>{try{execFileSync(process.execPath,['tools/prepare-production-cmyk-images.mjs',...args],{encoding:'utf8',stdio:'pipe'});}catch(e){return e;}})();assert.equal(result.status,1);assert.match(result.stderr,/CMYK 準備|CMYK 준비 중단/);}const help=execFileSync(process.execPath,['tools/prepare-production-cmyk-images.mjs','--help'],{encoding:'utf8'});assert.match(help,/--bundle-dir/);});
