import test from 'node:test';
import assert from 'node:assert/strict';
import '../apps/designer-studio/shared-screen-composition.js';
import '../apps/designer-studio/production-editor-adapter.js';
import { validateEditorCorrection } from '../server/production-editor-corrections.js';
const adapter=globalThis.ACDLProductionEditorAdapter,id='11111111-1111-4111-a111-111111111111',assetId='22222222-2222-4222-a222-222222222222';
function fixture(){
 const source={format:'acdl-project',settings:{year:2027,startMonth:3},productType:{category:'desk',pageSize:{width:260,height:180,unit:'mm'}},template:{id:'original',remoteId:'original',publishing:{lastReviewPackage:{templateId:'original',version:'1.0.0'}},metadata:{state:'published'},resources:{},masters:{calendar:{}},masterElements:{}},book:{pageInstances:[{id:'p1',role:'cover-front'},{id:'p2',role:'monthly-front',calendarYear:2027,calendarMonth:3}],sheets:[],school:{name:'샘플'},elementsByPage:{p1:[{id:'text',type:'text',binding:'school.name'}],p2:[]}}};
 const document={template:{id:'package',revision:'1.0.4',pages:[{id:'p1',role:'cover-front',size:{width:260,height:180},objects:[{id:'text',type:'text',payload:'사용자 학교',frame:{x:10,y:10,width:80,height:15},style:{fontSize:20},runtimeWidget:{}},{id:'photo',type:'image',payload:{src:`production-asset://${assetId}`,placement:{x:35,y:65,scale:1.2}},frame:{x:20,y:30,width:100,height:70},style:{},runtimeWidget:{}}]},{id:'p2',role:'monthly-front',size:{width:260,height:180},objects:[{id:'cal',type:'calendar',payload:{year:2027,month:3},frame:{x:25,y:40,width:200,height:120},style:{calendarLayout:{rowsMode:'5'}},runtimeWidget:{rows:5}}]}]},dataset:{school:{name:'사용자 학교'},calendar:{year:2027,startMonth:3,events:[]},monthlyImages:{},monthlyQuotes:{}}};
 return {source,document};
}
test('editor projection round trip preserves every frozen runtime field without mutating source',()=>{const {source,document}=fixture(),before=structuredClone(source),p=adapter.createProject(source,document,id);assert.deepEqual(adapter.toDocument(p),document);assert.deepEqual(source,before);assert.equal(p.template.remoteId,undefined);assert.deepEqual(p.template.publishing,{});assert.equal(p.book.school.name,'사용자 학교');assert.equal(p.book.elementsByPage.p1[1].image.focalPoint.x,.35);});
test('editing one page changes its object and keeps other pages and image placement',()=>{const {source,document}=fixture(),p=adapter.createProject(source,document,id);p.book.elementsByPage.p1[0].content='학교명 교정';p.book.elementsByPage.p1[0].x+=1;const result=adapter.toDocument(p);assert.equal(result.template.pages[0].objects[0].payload,'학교명 교정');assert.ok(Math.abs(result.template.pages[0].objects[0].frame.x-12.6)<.0001);assert.deepEqual(result.template.pages[1],document.template.pages[1]);assert.deepEqual(result.template.pages[0].objects[1],document.template.pages[0].objects[1]);});
test('calendar uses common content coordinates and changes only the selected page',()=>{const {source,document}=fixture(),p=adapter.createProject(source,document,id);p.book.pageInstances[1].productionCalendarMaster.calendarRegion.x+=1;const result=adapter.toDocument(p);assert.ok(Math.abs(result.template.pages[1].objects[0].frame.x-27.34)<.0001);assert.deepEqual(result.template.pages[0],document.template.pages[0]);});
test('server saves a new isolated project and reopens the saved revision losslessly',async()=>{const {source,document}=fixture(),p=adapter.createProject(source,document,id);p.book.elementsByPage.p1[0].content='첫 교정';const result=await validateEditorCorrection(p,document,{},id,[{id:assetId}],{loadSource:async()=>({projectData:source})});assert.deepEqual(adapter.toDocument(result.editorProject),adapter.withoutEditor(result));assert.equal(document.template.pages[0].objects[0].payload,'사용자 학교');const reopened=structuredClone(result.editorProject);reopened.book.elementsByPage.p1[0].content='두 번째 교정';const second=await validateEditorCorrection(reopened,result,{},id,[{id:assetId}]);assert.equal(second.template.pages[0].objects[0].payload,'두 번째 교정');assert.equal(result.template.pages[0].objects[0].payload,'첫 교정');assert.equal(second.editorProject.productionCorrection.printInspection,null);});
test('server rejects foreign assets, injected baselines, changed page size and unsupported new objects',async()=>{const {source,document}=fixture(),p=adapter.createProject(source,document,id),options={loadSource:async()=>({projectData:source})};p.productionCorrection.baseDocument.template.pages[0].objects[0].payload='injected';const saved=await validateEditorCorrection(p,document,{},id,[{id:assetId}],options);assert.equal(saved.template.pages[0].objects[0].payload,'사용자 학교');p.book.elementsByPage.p1[1].image.src='production-asset://33333333-3333-4333-a333-333333333333';await assert.rejects(validateEditorCorrection(p,document,{},id,[{id:assetId}],options),/보관된 원본/);p.book.elementsByPage.p1[1].image.src=`production-asset://${assetId}`;p.productType.pageSize.width=261;await assert.rejects(validateEditorCorrection(p,document,{},id,[{id:assetId}],options),/규격/);p.productType.pageSize.width=260;p.book.elementsByPage.p1.push({...p.book.elementsByPage.p1[0],id:'new'});await assert.rejects(validateEditorCorrection(p,document,{},id,[{id:assetId}],options),/새 개체/);});
test('receipt assetRef images restore and replacement updates the actual runtime reference',()=>{const {source,document}=fixture();document.template.pages[0].objects[1].payload={assetRef:{ref:'url',src:`production-asset://${assetId}`},placement:{scale:1.4,x:25,y:75},fit:'cover'};const p=adapter.createProject(source,document,id);assert.equal(p.book.elementsByPage.p1[1].image.src,`production-asset://${assetId}`);assert.deepEqual(adapter.toDocument(p),document);p.book.elementsByPage.p1[1].image.src='production-asset://replacement';assert.equal(adapter.toDocument(p).template.pages[0].objects[1].payload.assetRef.src,'production-asset://replacement');});
test('school semantic images display frozen user assets and retain runtime references on save',()=>{const {source,document}=fixture();document.template.pages[0].objects.push({id:'logo',type:'semantic-object',role:'school-logo',payload:{assetRef:{ref:'url',src:`production-asset://${assetId}`},fit:'contain'},frame:{x:1,y:2,width:20,height:15},style:{},runtimeWidget:{}});const p=adapter.createProject(source,document,id);assert.equal(p.book.elementsByPage.p1[2].sampleContent.image,`production-asset://${assetId}`);assert.deepEqual(adapter.toDocument(p),document);p.book.elementsByPage.p1[2].sampleContent.image='production-asset://new-logo';assert.equal(adapter.toDocument(p).template.pages[0].objects[2].payload.assetRef.src,'production-asset://new-logo');});
