import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/production-correction-assets.js';
process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';const old=globalThis.fetch;
const id='11111111-1111-4111-a111-111111111111',assetId='22222222-2222-4222-a222-222222222222';
const image=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(image);image.write('IHDR',12);image.writeUInt32BE(2048,16);image.writeUInt32BE(1365,20);
function response(){return {statusCode:200,setHeader(){},end(b){this.body=JSON.parse(b);}};}
function setup({admin=true,status='reviewing',size=24,mime='image/png'}={}){const calls=[];let asset={id:assetId,request_id:id,path:`${id}/${assetId}`,status:'pending',name:'새 원본.png',mime_type:mime,byte_size:size};globalThis.fetch=async(url,options={})=>{calls.push({url,options});if(url.includes('/auth/v1/user'))return new Response(JSON.stringify({id}));if(url.includes('template_admins'))return new Response(JSON.stringify(admin?[{user_id:id}]:[]));if(url.includes('calendar_production_requests'))return new Response(JSON.stringify([{id,status}]));if(url.includes('calendar_production_correction_assets')){if(options.method==='POST')return new Response('',{status:201});if(options.method==='PATCH')asset={...asset,...JSON.parse(options.body)};return new Response(JSON.stringify([asset]));}if(url.includes('/object/upload/sign/'))return new Response(JSON.stringify({url:`/object/upload/sign/calendar-correction-assets/${url.split('calendar-correction-assets/')[1]}?token=test-token`}));if(url.includes('/object/sign/'))return new Response(JSON.stringify({signedURL:'/object/sign/calendar-correction-assets/test?token=test-only'}));if(url.includes('/object/calendar-correction-assets/'))return new Response(image);throw Error(url);};return calls;}
function request(action='prepare'){return {method:'POST',headers:{authorization:'Bearer token'},body:{requestId:id,action,name:'new.png',mimeType:'image/png',byteSize:24,assetId}};}
test('non-admin cannot prepare private image uploads',async()=>{const calls=setup({admin:false}),res=response();await handler(request(),res);assert.equal(res.statusCode,403);assert.equal(calls.length,2);});
test('approved receipts do not accept correction uploads',async()=>{const calls=setup({status:'approved'}),res=response();await handler(request(),res);assert.equal(res.statusCode,409);assert.equal(calls.some(c=>c.url.includes('/storage/')),false);});
test('prepare creates a receipt-scoped upload URL with overwrite disabled',async()=>{const calls=setup(),res=response();await handler(request(),res);assert.equal(res.statusCode,200);assert.ok(res.body.uploadUrl.startsWith(`https://example.invalid/storage/v1/object/upload/sign/calendar-correction-assets/${id}/`));assert.ok(res.body.uploadUrl.includes('token='));const signed=calls.find(c=>c.url.includes('/object/upload/sign/'));assert.equal(signed.options.headers['x-upsert'],'false');assert.equal(JSON.stringify(res.body).includes('test-only'),false);});
test('finalize verifies pixels and records completed asset before returning preview',async()=>{const calls=setup(),res=response();await handler(request('finalize'),res);assert.equal(res.statusCode,200);assert.equal(res.body.asset.width,2048);assert.equal(res.body.asset.height,1365);assert.equal(res.body.asset.status,'ready');assert.equal(calls.some(c=>c.url.includes('calendar_production_requests')&&c.options.method==='PATCH'),false);});
test('mismatched file size or MIME never marks upload ready',async()=>{for(const options of [{size:25},{mime:'image/jpeg'}]){const calls=setup(options),res=response();await handler(request('finalize'),res);assert.equal(res.statusCode,400);assert.equal(calls.some(c=>c.options.method==='PATCH'),false);}});
test.after(()=>{globalThis.fetch=old;});
