import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {collectProductionWorkerInput} from '../tools/lib/production-worker-input.mjs';import {documentHash} from '../server/production-corrections.js';
const requestId='11111111-1111-4111-a111-111111111111',revisionId='22222222-2222-4222-a222-222222222222',assetId='33333333-3333-4333-a333-333333333333',owner='owner';
const bytes=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(bytes);bytes.write('IHDR',12);bytes.writeUInt32BE(1000,16);bytes.writeUInt32BE(500,20);
const document={template:{pages:[{id:'p1',size:{unit:'mm'},objects:[{id:'photo',type:'image-frame',frame:{x:0,y:0,width:50,height:25},payload:{src:`production-asset://${assetId}`,fit:'cover'}}]}]}};const hash=documentHash(document);
function fixture(correction=false){const asset={id:assetId,path:correction?`${requestId}/${assetId}`:`${owner}/${requestId}/${assetId}`,byte_size:bytes.length,width:1000,height:500,mime_type:'image/png',request_id:requestId,status:'ready'};const calls=[];return {asset,calls,query:async url=>{calls.push(url);if(url.startsWith('calendar_production_revisions'))return [{id:revisionId,document_hash:hash,document,revision_number:5}];if(url.startsWith('calendar_production_requests'))return [{id:requestId,owner_id:owner,snapshot:{assets:correction?[]:[asset]}}];return correction?[asset]:[];}};}
async function run(root,f,extra={}){return collectProductionWorkerInput({requestId,revisionId,documentHash:hash,contentHash:hash,outputDir:path.join(root,'input'),query:f.query,readImage:async(asset,bucket)=>{assert.equal(asset.id,assetId);assert.ok(['calendar-production-assets','calendar-correction-assets'].includes(bucket));return bytes;},...extra});}
test('Worker reads exact saved version and private originals, writes complete input without approval',async()=>{const root=await mkdtemp(path.join(tmpdir(),'worker-input-'));try{const f=fixture(),input=await run(root,f);assert.equal(input.inspection.results.length,1);assert.equal(input.inspection.finalApproved,false);assert.deepEqual(await readFile(path.join(input.sourceDir,assetId)),bytes);assert.ok(f.calls[0].includes(`request_id=eq.${requestId}&id=eq.${revisionId}`));await assert.rejects(run(root,f),/EEXIST/);}finally{await rm(root,{recursive:true,force:true});}});
test('Worker accepts only ready correction assets in this receipt and rejects foreign path',async()=>{const root=await mkdtemp(path.join(tmpdir(),'worker-path-'));try{const f=fixture(true);f.asset.path='foreign/path';await assert.rejects(run(root,f),/보관 완료/);await assert.rejects(readFile(path.join(root,'input','inspection.json')),/ENOENT/);const failure=JSON.parse(await readFile(path.join(root,'input','failure.json'),'utf8'));assert.equal(failure.completed,0);assert.equal(failure.finalApproved,false);}finally{await rm(root,{recursive:true,force:true});}});
test('stale document content is rejected before reading originals or creating input',async()=>{const root=await mkdtemp(path.join(tmpdir(),'worker-hash-'));try{await assert.rejects(run(root,fixture(),{contentHash:'0'.repeat(64)}),/내용/);await assert.rejects(readFile(path.join(root,'input','pending.json')),/ENOENT/);}finally{await rm(root,{recursive:true,force:true});}});

test('changed source bytes after admin inspection stop before publishing consumable input',async()=>{const root=await mkdtemp(path.join(tmpdir(),'worker-source-'));try{const inspection={schemaVersion:'production-image-inspection.v1',requestId,revisionId,documentHash:hash,plan:{contentHash:hash,uses:[]},results:[{source:`production-asset://${assetId}`,sourceHash:'0'.repeat(64),byteSize:bytes.length}]};await assert.rejects(run(root,fixture(),{inspection}),/원본 바이트/);await assert.rejects(readFile(path.join(root,'input','inspection.json')),/ENOENT/);}finally{await rm(root,{recursive:true,force:true});}});
