import test from 'node:test';import assert from 'node:assert/strict';
import {validateJobInspection} from '../server/production-image-jobs.js';import {runProductionImageJob} from '../tools/lib/production-image-job-worker.mjs';
import {documentHash} from '../server/production-corrections.js';import {productionImagePlan} from '../server/production-print-images.js';
const document={template:{pages:[]}},revisionId='22222222-2222-4222-a222-222222222222',hash=documentHash(document);const fixture={id:revisionId,document_hash:hash,document,revision_number:5};
const inspection={schemaVersion:'production-image-inspection.v1',requestId:'11111111-1111-4111-a111-111111111111',revisionId,documentHash:hash,plan:productionImagePlan(fixture),results:[]};
test('correction inspection record binds version and rejects other versions',()=>{const revision={id:inspection.revisionId,document_hash:inspection.documentHash,document,revision_number:5};const result=validateJobInspection(revision,inspection.requestId,inspection);assert.equal(result.finalApproved,false);assert.equal(result.plan.sources.length,0);assert.throws(()=>validateJobInspection(revision,'wrong',inspection),/保存|저장/);const bad=structuredClone(inspection);bad.results=[{sourceHash:'bad'}];assert.throws(()=>validateJobInspection(revision,inspection.requestId,bad),/모든 원본/);});
test('Worker claims once and persists progress and only same-version prepared result',async()=>{const calls=[],job={id:inspection.revisionId,worker_token:'token',revision_id:'v5',document_hash:'hash',content_hash:'content'};const query=async(route,options)=>{const body=JSON.parse(options.body);calls.push({route,body});return [route.includes('claim')?job:{}];};const result={schemaVersion:'production-cmyk-images.v1',revisionId:'v5',documentHash:'hash',contentHash:'content',finalApproved:false,derived:[]};await runProductionImageJob({id:job.id,query,execute:async(_,progress)=>{await progress({stage:'originals',completed:1,total:2});return result;}});assert.deepEqual(calls.map(x=>x.body.p_status).filter(Boolean),['processing','prepared']);assert.ok(calls.slice(1).every(c=>c.body.p_token==='token'));});
test('unclaimed jobs never execute, mismatched results fail and lost owners cannot complete',async()=>{await assert.rejects(runProductionImageJob({id:inspection.revisionId,query:async()=>[],execute:()=>assert.fail()}),/대기/);const states=[],job={worker_token:'token',revision_id:'v5',document_hash:'h',content_hash:'c'};await assert.rejects(runProductionImageJob({id:inspection.revisionId,query:async(route,o)=>{if(route.includes('claim'))return [job];states.push(JSON.parse(o.body).p_status);return [{}];},execute:async()=>({revisionId:'foreign'})}),/다른 버전/);assert.deepEqual(states,['failed']);});

import {spawnSync} from 'node:child_process';
test('job CLI does not require a manual inspection file',()=>{const result=spawnSync(process.execPath,['tools/run-production-image-worker.mjs','--job',inspection.revisionId,'--work-dir','work','--icc','profile','--icc-sha256','hash','--srgb-icc','srgb'],{encoding:'utf8',env:{...process.env,SUPABASE_URL:'',SUPABASE_SERVICE_ROLE_KEY:''}});assert.equal(result.status,1);assert.match(result.stderr,/연결 설정/);assert.doesNotMatch(result.stderr,/필수 옵션/);});
