import assert from 'node:assert/strict';
import test from 'node:test';
import { buildTemplatePackageCandidate } from '../server/template-package-candidate.js';

function fixture(){const pages=[{role:'cover-front'},...Array.from({length:12},(_,index)=>({role:'monthly-front',monthKey:`2028-${String(index+1).padStart(2,'0')}`})),{role:'back-cover-front'}],classification={schemaVersion:'template-classification.v1',managementName:'탁상형 260×180 · 기본 구성 · 에디토리얼 그래픽 · 01',productType:'desk',sizeCode:'260x180',compositionType:'basic',designStyle:'editorial-graphic'},userInput={schemaVersion:'template-user-input.v1',requiredInputs:['school.name','school.logo','calendar.events'],optionalInputs:['school.slogan'],imageSlots:{monthlyPhotos:0},recommendedFlow:'quick-order',supportsOptionalEditing:true,userServiceCapabilities:['add-text','add-image','edit-bound-content']},projectData={settings:{startMonth:3},productType:{category:'desk',pageSize:{width:260,height:180,unit:'mm'},productionSize:{width:266,height:186,unit:'mm'}},template:{classification,userInput},book:{pageInstances:pages}};return {template:{id:'source-template',state:'ready',isStandard:true},version:{id:'source-v3',versionNumber:3,projectData}}}

test('system base becomes one deterministic review package bundle',()=>{const source=fixture(),first=buildTemplatePackageCandidate({...source,packageId:'desk-260x180-basic-editorial-graphic-01',packageVersion:'1.0.0'}),second=buildTemplatePackageCandidate({...source,packageId:'desk-260x180-basic-editorial-graphic-01',packageVersion:'1.0.0'});assert.equal(first.status,'review');assert.equal(first.publishable,false);assert.equal(first.sha256,second.sha256);assert.match(first.sha256,/^[a-f0-9]{64}$/);assert.equal(first.packageBundle.manifest.pageComposition.surfaceCount,14);assert.equal(first.packageBundle.publishing.lifecycle.currentStatus,'review');assert.ok(first.packageBundle.publishing.editCompatibility.capabilities.includes('add-image'))});

test('candidate rejects an unclassified or mutable source',()=>{const source=fixture();source.template.isStandard=false;assert.throws(()=>buildTemplatePackageCandidate({...source,packageId:'desk-basic-01',packageVersion:'1.0.0'}),/System base classification is incomplete/)});

test('candidate requires immutable package identity syntax',()=>{const source=fixture();assert.throws(()=>buildTemplatePackageCandidate({...source,packageId:'Desk Basic',packageVersion:'v1'}),/Invalid Package ID/)});
