import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {forwardReviewPackage} from '../server/user-service-review-publisher.js';

const source=readFileSync(new URL('../apps/designer-studio/template-publishing-runtime.js',import.meta.url),'utf8');
const proxySource=readFileSync(new URL('../api/templates.js',import.meta.url),'utf8');
const vercel=JSON.parse(readFileSync(new URL('../vercel.json',import.meta.url),'utf8'));
function runtime(){const window={crypto:globalThis.crypto,fetch:globalThis.fetch,TextEncoder,FileReader:class{}};vm.runInNewContext(source,{window,TextEncoder,FileReader:window.FileReader,structuredClone,btoa,atob,decodeURIComponent});return window.ACDLTemplatePublishing}

test('snapshot review bundle preserves the complete editor project and author input contract',()=>{const api=runtime(),project={productType:{category:'desk',pageSize:{width:260,height:180,unit:'mm'}},settings:{startMonth:3},template:{publishing:{dataRequirements:[{path:'school.name',stage:'project-create-required'},{path:'monthlyImages',stage:'optional',fallback:'sample'}]}},book:{pageInstances:[{id:'cover',role:'cover-front'},{id:'month',role:'monthly-front'}]}};const bundle=api.buildBundle(project,{id:'test-template',version:'1.0.0',name:'테스트',productType:'desk'});assert.equal(bundle.template.kind,'designer-project-snapshot');assert.equal(bundle.template.projectData,project);assert.equal(bundle.bindings.bindings[0].required,true);assert.equal(bundle.bindings.bindings[1].missing,'sample');assert.equal(bundle.manifest.status,'review');assert.equal(bundle.manifest.publishable,false)});

test('package id normalization is stable and accepted by the user service contract',()=>{const api=runtime();assert.equal(api.packageId('TPL 2027 / Desk 01'),'tpl-2027-desk-01');assert.match(api.packageId('한글 이름'),/^template-\d+$/)});

test('new temporary templates receive a readable name and deterministic package identity',()=>{const api=runtime(),project={productType:{category:'desk',pageSize:{width:260,height:180}},settings:{frontInsertCount:0,rearInsertCount:0},template:{settings:{aiDesignSpec:{styleId:'editorial-graphic',styleSnapshots:[{id:'editorial-graphic',name:'에디토리얼 그래픽'}]}}}};const identity=api.publicationIdentity(project,'20260914_002',{id:'tpl-1789367395367',stableKey:'tpl-1789367395367'});assert.equal(identity.name,'탁상형 260×180 · 기본 구성 · 에디토리얼 그래픽 · 02');assert.equal(identity.id,'desk-260x180-basic-editorial-graphic-02')});

test('image data URLs are deduplicated into independently uploaded package assets',async()=>{const api=runtime(),source='data:image/png;base64,aGVsbG8=',result=await api.externalizeAssets({cover:source,nested:[source]},{templateId:'desk-test',version:'1.0.0'});assert.equal(result.assets.length,1);assert.equal(result.assets[0].mimeType,'image/png');assert.equal(result.assets[0].byteLength,5);assert.match(result.assets[0].id,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);assert.equal(result.project.cover,`package-asset://${result.assets[0].id}`);assert.equal(result.project.nested[0],result.project.cover);const bundle=api.buildBundle(result.project,{id:'desk-test',version:'1.0.0',name:'테스트',productType:'desk',assets:result.assets});assert.equal(bundle.assets.length,1);assert.equal('bytes' in bundle.assets[0],false)});

test('review proxy forwards only authenticated supported operations to the user service preview branch',async()=>{await assert.rejects(()=>forwardReviewPackage({authorization:'',body:{mode:'chunk'},fetcher:async()=>{}}),/AUTH_REQUIRED/);let received;const result=await forwardReviewPackage({authorization:'Bearer token',body:{mode:'next-version',packageId:'a',baseVersion:'1.0.0'},fetcher:async(url,options)=>{received={url,options};return {ok:true,status:200,json:async()=>({version:'1.0.1'})}}});assert.equal(result.version,'1.0.1');assert.match(received.url,/school-calendar-editor-servic-git-1a2acc/);assert.match(received.url,/template-packages\/review$/);assert.equal(received.options.headers.Authorization,'Bearer token')});

test('review proxy permits asset upload, activation, withdrawal, and catalog synchronization modes',async()=>{for(const mode of ['asset-chunk','activate-review','withdraw','retire-packages','sync-review-catalog']){let forwarded=false;await forwardReviewPackage({authorization:'Bearer token',body:{mode},fetcher:async()=>{forwarded=true;return {ok:true,status:200,json:async()=>({ok:true})}}});assert.equal(forwarded,true)}});

test('browser reuses the existing templates endpoint with bounded two-megabyte review chunks',()=>{assert.match(source,/fetch\('\/api\/templates'/);assert.match(source,/operation:'publish-review'/);assert.match(source,/CHUNK_BYTES=1800\*1024/)});

test('review proxy delegates authorization once to the receiving user service',()=>{const review=proxySource.indexOf("body?.operation==='publish-review'"),localAuth=proxySource.indexOf('await assertInternalAccess(request)');assert.ok(review>0);assert.ok(localAuth>review);assert.match(proxySource,/forwardReviewPackage\(\{authorization,body:body\.reviewBody\}\)/)});

test('image-heavy package finalization has an explicit long-running function budget',()=>{assert.equal(vercel.functions['api/templates.js'].maxDuration,300);assert.match(readFileSync(new URL('../server/user-service-review-publisher.js',import.meta.url),'utf8'),/body\.mode==='finalize'\?240000:60000/)});

test('published identities can be withdrawn and the review catalog follows the current system base exactly',async()=>{const calls=[],projects={one:{template:{publishing:{lastReviewPackage:{templateId:'desk-one',version:'1.0.2'}}}},two:{template:{publishing:{lastReviewPackage:{templateId:'desk-two',version:'1.0.1'}}}}},window={crypto:globalThis.crypto,fetch:async(_url,options)=>{const body=JSON.parse(options.body);calls.push(body.reviewBody);return {ok:true,json:async()=>({archived:[]})}},TextEncoder,FileReader:class{},ACDLTemplateRemotePersistence:{accessToken:()=>"token",isRemote:()=>true,list:async()=>[{id:'one',state:'published'},{id:'two',state:'published'},{id:'draft',state:'draft'}],load:async id=>({version:{projectData:projects[id]}})}};vm.runInNewContext(source,{window,TextEncoder,FileReader:window.FileReader,structuredClone,btoa});const project={template:{publishing:{lastReviewPackage:{templateId:'desk-new',version:'1.0.0'}}}};assert.equal(JSON.stringify(window.ACDLTemplatePublishing.publishedIdentity(project)),JSON.stringify({templateId:'desk-new',version:'1.0.0'}));await window.ACDLTemplatePublishing.withdraw(project);await window.ACDLTemplatePublishing.synchronizeCatalog();assert.equal(calls[0].mode,'withdraw');assert.equal(calls[1].mode,'sync-review-catalog');assert.deepEqual(calls[1].activePackages.map(item=>`${item.templateId}@${item.version}`),['desk-one@1.0.2','desk-two@1.0.1'])});
