import {randomUUID} from 'node:crypto';
import {storeTemplateAsset} from './template-persistence.js';
const BUCKET='template-assets',PREFIX='graphics-library',UUID=/^[0-9a-f-]{36}$/i;
export const GRAPHIC_CATEGORIES=['background','illustration','decoration'];
export function validateGraphicMetadata(body){
 const name=String(body.name||'').trim(),category=body.category||'illustration',width=Number(body.width),height=Number(body.height);
 if(!name||name.length>120||!GRAPHIC_CATEGORIES.includes(category)||!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>60000||height>60000)throw Object.assign(new Error('이미지 정보를 확인해주세요'),{statusCode:400,code:'INVALID_GRAPHIC_METADATA'});
 return {name,category,width,height,tags:String(body.tags||'').trim().slice(0,500),source:String(body.source||'').trim().slice(0,500)};
}
function fail(code,statusCode=400){throw Object.assign(new Error(code),{code,statusCode})}
async function storage(path,options={}){const url=process.env.SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)fail('SERVER_NOT_CONFIGURED',503);const r=await fetch(`${url.replace(/\/$/,'')}/storage/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,...options.headers}});if(!r.ok)fail('GRAPHIC_STORAGE_FAILED',502);return r}
const path=id=>{if(!UUID.test(id))fail('INVALID_GRAPHIC_ID');return `${PREFIX}/${id}.json`};
export async function listGraphics(){const items=[];let offset=0;while(true){const r=await storage(`object/list/${BUCKET}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefix:PREFIX,limit:100,offset,sortBy:{column:'name',order:'asc'}})}),rows=await r.json();for(const row of rows)if(UUID.test(row.name.replace(/\.json$/,''))&&row.name.endsWith('.json')){const value=await storage(`object/${BUCKET}/${PREFIX}/${row.name}`).then(r=>r.json());if(value.schemaVersion==='graphic-library.v1')items.push(value)}if(rows.length<100)break;offset+=100}return items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function getGraphic(id){return storage(`object/${BUCKET}/${path(id)}`).then(r=>r.json())}
async function write(value){await storage(`object/${BUCKET}/${path(value.id)}`,{method:'POST',headers:{'Content-Type':'application/json','x-upsert':'true'},body:JSON.stringify(value)});return value}
export async function uploadChunk(body){const {uploadId,index,total,data}=body;if(!UUID.test(uploadId)||!Number.isInteger(index)||!Number.isInteger(total)||total<1||total>20||index<0||index>=total||typeof data!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(data))fail('INVALID_GRAPHIC_CHUNK');const bytes=Buffer.from(data,'base64');if(!bytes.length||bytes.length>1024*1024)fail('GRAPHIC_CHUNK_TOO_LARGE',413);await storage(`object/${BUCKET}/graphics-uploads/${uploadId}/${index}`,{method:'POST',headers:{'Content-Type':'application/octet-stream','x-upsert':'true'},body:bytes});return {index}}
export async function createGraphic(body){const metadata=validateGraphicMetadata(body);if(!UUID.test(body.uploadId)||!Number.isInteger(body.total)||body.total<1||body.total>20||!['image/png','image/jpeg','image/webp'].includes(body.mimeType))fail('INVALID_GRAPHIC_UPLOAD');const chunks=[];for(let index=0;index<body.total;index++)chunks.push(Buffer.from(await storage(`object/${BUCKET}/graphics-uploads/${body.uploadId}/${index}`).then(r=>r.arrayBuffer())));const bytes=Buffer.concat(chunks);if(!bytes.length||bytes.length>20*1024*1024)fail('GRAPHIC_TOO_LARGE',413);
 const valid=body.mimeType==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):body.mimeType==='image/jpeg'?bytes[0]===255&&bytes[1]===216:bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid)fail('INVALID_GRAPHIC_IMAGE');
 const original=await storeTemplateAsset(`data:${body.mimeType};base64,${bytes.toString('base64')}`),preview=await storeTemplateAsset(body.previewDataUrl);const record=await write({schemaVersion:'graphic-library.v1',id:randomUUID(),...metadata,originalAssetId:original.id,previewAssetId:preview.id,mimeType:body.mimeType,byteSize:bytes.length,fileName:String(body.fileName||'').slice(0,200),status:'active',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
 await storage(`object/${BUCKET}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:chunks.map((_,i)=>`graphics-uploads/${body.uploadId}/${i}`)})}).catch(()=>{});return record}
export async function updateGraphic(body){const current=await getGraphic(body.id);if(!['active','archived'].includes(body.status))fail('INVALID_GRAPHIC_STATUS');return write({...current,status:body.status,updatedAt:new Date().toISOString()})}
