export type CalendarType="desk"|"wall"|"poster"|"postcard"; export type WeekStart="sunday"|"monday"; export type GridRows=5|6;
export interface SchoolProfile{id:string;name:string;logoAssetId?:string;flower?:string;tree?:string;song?:string;}
export interface AcademicEvent{id:string;title:string;start:string;end?:string;category?:string;allDay?:boolean;}
export interface CalendarProjectSettings{year:number;startMonth:number;calendarType:CalendarType;weekStart:WeekStart;gridRows:GridRows;frontDividerCount:number;backDividerCount:number;}
export interface CalendarMonth{year:number;month:number;key:string;}
export function buildTwelveMonths(year:number,startMonth:number):CalendarMonth[]{if(startMonth<1||startMonth>12)throw new RangeError("startMonth must be 1..12");return Array.from({length:12},(_,i)=>{const index=startMonth-1+i;const y=year+Math.floor(index/12);const m=index%12+1;return{year:y,month:m,key:`${y}-${String(m).padStart(2,"0")}`};});}
export function validateSettings(s:CalendarProjectSettings):string[]{const e:string[]=[];if(s.year<2000||s.year>2200)e.push("year.out_of_range");if(s.startMonth<1||s.startMonth>12)e.push("startMonth.invalid");if(s.frontDividerCount<0||s.backDividerCount<0)e.push("divider.negative");return e;}

export interface CalendarCell{date:string;year:number;month:number;day:number;inMonth:boolean;row:number;column:number;}
export interface CalendarGrid{year:number;month:number;weekStart:WeekStart;rows:5|6;cells:CalendarCell[];}
const dateKey=(date:Date)=>`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`;
export function buildCalendarGrid(year:number,month:number,weekStart:WeekStart="sunday",rows?:GridRows):CalendarGrid{
 if(month<1||month>12)throw new RangeError("month must be 1..12");const first=new Date(Date.UTC(year,month-1,1));const offset=(first.getUTCDay()-(weekStart==="monday"?1:0)+7)%7;const natural=Math.ceil((offset+new Date(Date.UTC(year,month,0)).getUTCDate())/7);const gridRows=rows??(natural<=5?5:6);if(gridRows<natural)throw new RangeError("gridRows cannot contain the month");
 const start=new Date(Date.UTC(year,month-1,1-offset));const cells=Array.from({length:gridRows*7},(_,index)=>{const date=new Date(start);date.setUTCDate(start.getUTCDate()+index);return{date:dateKey(date),year:date.getUTCFullYear(),month:date.getUTCMonth()+1,day:date.getUTCDate(),inMonth:date.getUTCMonth()===month-1,row:Math.floor(index/7),column:index%7};});return{year,month,weekStart,rows:gridRows,cells};
}
export interface RangeSegment{eventId:string;startDate:string;endDate:string;row:number;startColumn:number;endColumn:number;continuesBefore:boolean;continuesAfter:boolean;}
export function splitRangeEvent(event:{id:string;startDate:string;endDate:string},grid:CalendarGrid):RangeSegment[]{const visible=grid.cells.filter(cell=>cell.date>=event.startDate&&cell.date<=event.endDate);if(!visible.length)return[];const segments:RangeSegment[]=[];for(const cell of visible){const current=segments.at(-1);if(current&&current.row===cell.row&&current.endColumn+1===cell.column){current.endDate=cell.date;current.endColumn=cell.column;}else segments.push({eventId:event.id,startDate:cell.date,endDate:cell.date,row:cell.row,startColumn:cell.column,endColumn:cell.column,continuesBefore:cell.date>event.startDate,continuesAfter:cell.date<event.endDate});}for(const segment of segments){segment.continuesBefore=segment.startDate>event.startDate;segment.continuesAfter=segment.endDate<event.endDate;}return segments;}
