(function(root){
 const VERSION='ai-generation-context.v2@0.2.0';
 const ROLE_POLICY={cover:'cover',annual:'annualSingle',divider:'frontInsert',month:'monthlyFront','month-back':'monthlyBack','back-cover':'backCover'};
 const DEFAULT_SAFE_MARGIN_MM=5;
 const ESTIMATED_IMAGE_USD=Object.freeze({low:0.013,medium:0.05});
 function clone(value){return JSON.parse(JSON.stringify(value))}
 function definition(project){return project?.template?.calendarTypeSnapshot?.definition||null}
 function isDivider(page){const role=String(page?.role||''),semantic=String(page?.semanticPageRole||'');return role==='school-symbols'||role.includes('insert')||semantic==='school-symbols'||semantic==='divider'}
 function dividerPosition(page){const role=String(page?.role||'');if(role.startsWith('rear-'))return 'rear';if(role.startsWith('front-'))return 'front';return page?.dividerPosition||'middle'}
 function dividerSurface(page){const role=String(page?.role||'');if(role.endsWith('-front'))return 'front';if(role.endsWith('-back'))return 'back';return page?.side||'single'}
 function pagesFor(project,role){const pages=project?.book?.pageInstances||[];return pages.filter(page=>{if(role==='cover')return page.role==='cover-front'||page.role==='cover';if(role==='annual')return ['cover-back','poster-annual','annual'].includes(page.role)||page.semanticPageRole==='yearly-calendar';if(role==='divider')return isDivider(page);if(role==='month')return page.role==='monthly-front';if(role==='month-back')return page.role==='monthly-back';if(role==='back-cover')return ['back-cover-front','back-cover-back'].includes(page.role);return false})}
 function policyFor(type,role,pages){if(!pages.length)return 'unsupported';if(role==='divider')return 'optional';return type?.policies?.[ROLE_POLICY[role]]||(pages.length?'required':'unsupported')}
 function pageTarget(page,role,index,total,project){const configured=role==='divider'?project?.template?.settings?.aiDesignSpec?.dividerPages?.[page.id]:null;return {pageId:page.id,role,sourceRole:page.role||null,semanticPageRole:page.semanticPageRole||null,index:index+1,total,position:role==='divider'?dividerPosition(page):null,surface:role==='divider'?dividerSurface(page):(page.side||null),contentPurpose:configured?.purpose||page.contentPurpose||page.semanticPageRole||null,layoutId:configured?.layoutId||null,objects:configured?.objects||[],monthKey:page.monthKey||null,calendarYear:page.calendarYear||null,calendarMonth:page.calendarMonth||null}}
 function build(project){
  const type=definition(project),finished=clone(type?.finishedSize||project?.productType?.pageSize||{}),production=clone(type?.productionSize||finished),familyId=type?.family?.id||project?.productType?.category||null;
  const supported=familyId==='desk'||familyId==='table'||String(familyId||'').includes('desk');
  const roleIds=['cover','annual','divider','month','month-back','back-cover'];
  const roles=roleIds.map(role=>{const pages=pagesFor(project,role),policy=supported?policyFor(type,role,pages):'unsupported',targets=pages.map((page,index)=>pageTarget(page,role,index,pages.length,project));return {role,policy,pageCount:pages.length,enabled:supported&&policy!=='unsupported'&&pages.length>0,required:policy==='required',pageIds:pages.map(page=>page.id),targets}});
  const safeMarginMm=Number(project?.template?.resources?.exportSettings?.safeMargin)||DEFAULT_SAFE_MARGIN_MM;
  return {schemaVersion:VERSION,scope:'desk-first',supported,unsupportedReason:supported?null:'현재 AI 디자인 고도화는 탁상달력에만 적용됩니다.',calendarType:{id:type?.id||project?.productType?.calendarTypeId||project?.productType?.category||null,family:type?.family?clone(type.family):{id:familyId,name:''},orientation:type?.orientation||(Number(finished.width)>=Number(finished.height)?'landscape':'portrait'),printSides:type?.printSides||(project?.productType?.duplex?'duplex':'simplex'),binding:clone(type?.binding||{}),finishedSize:finished,productionSize:production},print:{bleedMm:Math.max(0,(Number(production.width)-Number(finished.width))/2)||Number(project?.template?.resources?.exportSettings?.bleed)||3,safeMarginMm,targetDpi:Number(project?.template?.resources?.exportSettings?.dpi)||300,colorMode:project?.template?.resources?.exportSettings?.colorMode||'cmyk'},roles,enabledRoles:roles.filter(item=>item.enabled).map(item=>item.role),monthlyRoles:roles.filter(item=>item.enabled&&['month','month-back'].includes(item.role)).map(item=>item.role),pageTargets:roles.filter(item=>item.enabled).flatMap(item=>item.targets)};
 }
 function plan(context,{monthCount=12,quality='low'}={}){const roles=context?.roles?.filter(item=>item.enabled)||[],monthlyRoles=roles.filter(item=>['month','month-back'].includes(item.role)),nonMonthly=roles.filter(item=>!['month','month-back'].includes(item.role)),months=monthlyRoles.length?Math.max(0,Number(monthCount)||0):0,monthlyAssetCount=monthlyRoles.reduce((sum,item)=>sum+Math.max(item.pageCount,months),0),nonMonthlyAssetCount=nonMonthly.reduce((sum,item)=>sum+item.pageCount,0),representativeCount=nonMonthlyAssetCount+monthlyRoles.length,generationCount=nonMonthlyAssetCount+monthlyAssetCount,unitCostUsd=ESTIMATED_IMAGE_USD[quality]??ESTIMATED_IMAGE_USD.low;return {familyId:context?.calendarType?.family?.id||null,supported:context?.supported!==false,enabledRoles:roles.map(item=>item.role),monthlyRoles:monthlyRoles.map(item=>item.role),representativeCount,actualPageCount:roles.reduce((sum,item)=>sum+item.pageCount,0),monthCount:months,monthlyAssetCount,nonMonthlyAssetCount,generationCount,estimatedCostUsd:Number((generationCount*unitCostUsd).toFixed(3)),unitCostUsd,quality,priceBasis:'gpt-image-1.5 · 1536x1024 · 2026-09-08 estimate'} }
 root.ACDLAIGenerationContext=Object.freeze({VERSION,ROLE_POLICY,DEFAULT_SAFE_MARGIN_MM,ESTIMATED_IMAGE_USD,definition,isDivider,dividerPosition,dividerSurface,pagesFor,build,plan});
})(typeof window==='undefined'?globalThis:window);
