(function(root){
 const VERSION='ai-design-quality.v1@0.2.0',SAFE_MARGIN=3,MIN_DRAFT_DPI=144,REGENERABLE=new Set(['forbidden-text','duplicate-asset','visual-inconsistency']);
 const ROLE_BY_PAGE=Object.freeze({'cover-front':'cover','cover-back':'annual','poster-annual':'annual','school-symbols':'divider','front-insert-front':'divider','front-insert-back':'divider','rear-insert-front':'divider','rear-insert-back':'divider','monthly-front':'month','monthly-back':'month-back','back-cover-front':'back-cover','back-cover-back':'back-cover'});
 function monthKey(page){return page?.monthKey||(page?.calendarYear&&page?.calendarMonth?`${page.calendarYear}-${String(page.calendarMonth).padStart(2,'0')}`:null)}
 function generatedRole(page){return ['school-symbols','divider'].includes(page?.semanticPageRole)?'divider':ROLE_BY_PAGE[page?.role]||null}
 function metadataFor(selected,page,role){return ['month','month-back'].includes(role)?selected?.monthlyAssets?.[monthKey(page)]?.metadata?.[role]||{}:selected?.assetMetadataByRole?.[role]||{}}
 function assetFor(selected,page,role){return ['month','month-back'].includes(role)?selected?.monthlyAssets?.[monthKey(page)]?.[role]||null:selected?.assetsByRole?.[role]||null}
 function frame(item){const value=item?.framePct||item;if(![value?.x,value?.y,value?.width,value?.height].every(Number.isFinite))return null;return {x:value.x,y:value.y,width:value.width,height:value.height}}
 function overlapRatio(a,b){const width=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)),height=Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));return width*height/Math.max(1,Math.min(a.width*a.height,b.width*b.height))}
 function dimensions(meta){if(Array.isArray(meta.size))return {width:Number(meta.size[0]),height:Number(meta.size[1])};const match=String(meta.size||'').match(/(\d+)\s*x\s*(\d+)/i);return match?{width:Number(match[1]),height:Number(match[2])}:null}
 function pageChecks(project,selected,page){
  const role=generatedRole(page),key=monthKey(page),elements=project?.book?.elementsByPage?.[page.id]||[],editable=elements.filter(item=>item.role!=='ai-design-background'),meta=metadataFor(selected,page,role),asset=assetFor(selected,page,role),issues=[],pageSize=project?.template?.calendarTypeSnapshot?.definition?.finishedSize||project?.productType?.pageSize||{},safeMm=Number(project?.template?.resources?.exportSettings?.safeMargin)||5,safeX=pageSize.width?safeMm/Number(pageSize.width)*100:SAFE_MARGIN,safeY=pageSize.height?safeMm/Number(pageSize.height)*100:SAFE_MARGIN;
  if(!asset)issues.push({code:'missing-asset',severity:'fail',regenerable:false});
  if(!editable.length)issues.push({code:'readability',severity:'fail',regenerable:false});
  const outside=editable.filter(item=>{const box=frame(item);return box&&(box.x<safeX||box.y<safeY||box.x+box.width>100-safeX||box.y+box.height>100-safeY)});
  if(outside.length)issues.push({code:'safe-area',severity:'fail',regenerable:false,elementIds:outside.map(item=>item.id)});
  const boxes=editable.map(item=>({item,box:frame(item)})).filter(item=>item.box);const collisions=[];
  for(let left=0;left<boxes.length;left+=1)for(let right=left+1;right<boxes.length;right+=1)if(overlapRatio(boxes[left].box,boxes[right].box)>.8)collisions.push([boxes[left].item.id,boxes[right].item.id]);
  if(collisions.length)issues.push({code:'collision',severity:'fail',regenerable:false,pairs:collisions});
  const forbidden=meta.qualityChecks?.forbiddenText||meta.quality?.forbiddenText;
  if(forbidden==='fail'||(meta.detectedForbiddenText||[]).length)issues.push({code:'forbidden-text',severity:'fail',regenerable:true,tokens:meta.detectedForbiddenText||[]});else if(forbidden==='review-required')issues.push({code:'forbidden-text-review',severity:'review',regenerable:false});
  const expectedStyle=selected?.key,actualStyle=meta.styleKey;if(expectedStyle&&actualStyle&&actualStyle!==expectedStyle)issues.push({code:'visual-inconsistency',severity:'fail',regenerable:true});
  const size=dimensions(meta),targetDpi=Number(project?.template?.resources?.exportSettings?.dpi)||300;if(size&&pageSize?.width&&pageSize?.height){const dpi=Math.min(size.width/(pageSize.width/25.4),size.height/(pageSize.height/25.4));if(dpi<MIN_DRAFT_DPI)issues.push({code:'effective-resolution',severity:'fail',regenerable:false,effectiveDpi:Math.round(dpi)});else if(dpi<targetDpi)issues.push({code:'print-resolution-review',severity:'review',regenerable:false,effectiveDpi:Math.round(dpi),targetDpi})}
  return {pageId:page.id,pageRole:page.role,generatedRole:role,monthKey:key,assetId:meta.id||null,sourceVersion:meta.promptVersion||null,sourceSize:meta.size||null,hasAsset:Boolean(asset),status:issues.some(item=>item.severity==='fail')?'fail':issues.length?'review':'pass',issues};
 }
 function printInspection(pages,now){
  const issues=pages.flatMap(page=>(page.issues||[]).map(item=>({...item,pageId:page.pageId}))),byCode=codes=>issues.filter(item=>codes.includes(item.code)),criterion=(status,message,evidence={})=>({status,message,evidence:{pageCount:pages.length,...evidence}}),failed=(codes,message)=>{const matches=byCode(codes);return matches.length?criterion('failed',message,{affectedPageIds:[...new Set(matches.map(item=>item.pageId))],issueCodes:[...new Set(matches.map(item=>item.code))]}):null},reviewed=(codes,message)=>{const matches=byCode(codes);return matches.length?criterion('review',message,{affectedPageIds:[...new Set(matches.map(item=>item.pageId))],issueCodes:[...new Set(matches.map(item=>item.code))]}):null};
  const unidentified=pages.filter(page=>!page.pageId||!page.generatedRole||!page.assetId),identity=unidentified.length?criterion('failed',`${unidentified.length}개 이미지의 페이지·용도·자산 식별 정보가 부족합니다.`,{affectedPageIds:unidentified.map(page=>page.pageId).filter(Boolean)}):criterion('passed',`${pages.length}개 AI 이미지의 페이지·용도·자산을 식별했습니다.`),generationStandard=criterion('review','생성 버전은 기록했지만 인쇄용 최대 품질 적용 여부는 후속 생성 기준이 필요합니다.',{sourceVersions:[...new Set(pages.map(page=>page.sourceVersion).filter(Boolean))],sourceSizes:[...new Set(pages.map(page=>String(page.sourceSize||'')).filter(Boolean))]}),frameSuitability=failed(['effective-resolution'],'대상 프레임에서 유효 해상도가 부족한 이미지가 있습니다.')||reviewed(['print-resolution-review'],'대상 프레임의 인쇄 해상도 확인이 필요합니다.')||criterion('review','화면비·크롭 안전성 전용 검사가 아직 필요합니다.'),placementIntegrity=failed(['missing-asset','safe-area','collision','effective-resolution'],'누락·이탈·충돌·과도한 확대 항목을 수정해야 합니다.')||reviewed(['print-resolution-review'],'확대 배치의 인쇄 해상도 확인이 필요합니다.')||criterion('passed','기존 자동검사에서 누락·이탈·충돌·과도한 확대 실패가 없습니다.'),visualArtifacts=failed(['duplicate-asset','visual-inconsistency'],'반복 이미지 또는 시각 일관성 실패가 있습니다.')||criterion('review','중복 검사는 완료했으며 흐림·노이즈·비정상 형상 검사가 필요합니다.'),contentLegibility=failed(['readability','collision','safe-area','forbidden-text'],'달력 개체와 AI 이미지의 가독성 충돌을 수정해야 합니다.')||reviewed(['forbidden-text-review'],'AI 이미지 안의 금지 텍스트를 수동 확인해야 합니다.')||criterion('passed','기존 자동검사에서 가독성 충돌 실패가 없습니다.'),criteria={identity,generationStandard,frameSuitability,placementIntegrity,visualArtifacts,contentLegibility},states=Object.values(criteria).map(item=>item.status);
  return {schemaVersion:'ai-image-print-quality.v1@0.1.0',criteriaVersion:'ai-image-print-quality.v1@0.1.0',status:states.includes('failed')?'failed':states.every(state=>state==='passed')?'passed':'pending',checkedAt:now,criteria};
 }
 function createReport(project,selected,now=new Date().toISOString()){
  const pages=(project?.book?.pageInstances||[]).filter(page=>generatedRole(page)).map(page=>pageChecks(project,selected,page)),seen=new Map();
  pages.forEach(page=>{const asset=assetFor(selected,page,page.generatedRole);if(!asset)return;const prior=seen.get(asset);if(prior&&prior.generatedRole===page.generatedRole&&prior.monthKey!==page.monthKey){page.issues.push({code:'duplicate-asset',severity:'fail',regenerable:true,duplicateOf:prior.pageId});page.status='fail'}else seen.set(asset,page)});
  const regenerationTargets=pages.flatMap(page=>page.issues.some(issue=>issue.severity==='fail'&&REGENERABLE.has(issue.code))?[{pageId:page.pageId,generatedRole:page.generatedRole,monthKey:page.monthKey,reasons:page.issues.filter(issue=>issue.severity==='fail'&&REGENERABLE.has(issue.code)).map(issue=>issue.code)}]:[]);
  const failedPages=pages.filter(page=>page.status==='fail'),reviewPages=pages.filter(page=>page.status==='review'),type=project?.template?.calendarTypeSnapshot?.definition;return {schemaVersion:VERSION,status:failedPages.length?'failed':reviewPages.length?'review-required':'passed',calendarTypeId:type?.id||project?.productType?.calendarTypeId||null,finishedSize:type?.finishedSize||project?.productType?.pageSize||null,pagePolicies:type?.policies||null,checks:['readability','collision','safe-area','forbidden-text','duplicate-asset','visual-inconsistency','effective-resolution'],pageCount:pages.length,passedPageCount:pages.filter(page=>page.status==='pass').length,failedPageCount:failedPages.length,reviewPageCount:reviewPages.length,failedRoles:[...new Set(failedPages.map(page=>page.generatedRole))],regenerationTargets,pages,printInspection:printInspection(pages,now),checkedAt:now};
 }
 root.ACDLDesignQuality=Object.freeze({VERSION,SAFE_MARGIN,MIN_DRAFT_DPI,ROLE_BY_PAGE,monthKey,generatedRole,pageChecks,printInspection,createReport});
})(typeof window==='undefined'?globalThis:window);
