(function(root){
 const VERSION='0.2.0',SCHEMA_VERSION='ai-design-object-style-application.v1';
 const presets=Object.freeze({
  editorial:{font:{title:'Noto Serif KR',body:'Noto Sans KR'},palette:['#24466f','#6885a8','#e9eef4','#ffffff'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:1,stroke:'#ffffff',strokeWidth:2},mini:{background:false,gridLine:false},planner:{background:'#f5f7fa',line:'#cbd5e1',radius:2}},
  'seasonal-watercolor':{font:{title:'Nanum Myeongjo',body:'Noto Sans KR'},palette:['#47866b','#d88772','#8e77a8','#f7f1e7'],calendar:{monthTitleStyle:'number-stack',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:4,stroke:'#ffffff',strokeWidth:3},mini:{background:true,gridLine:false},planner:{background:'#f4f1e9',line:'#b8cdbf',radius:5}},
  geometry:{font:{title:'Arial',body:'Noto Sans KR'},palette:['#1769e0','#ff5a47','#ffc928','#f5f7ff'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'detached-cards',eventStyle:'strong-bars'},frame:{borderRadius:0,stroke:'#1769e0',strokeWidth:2},mini:{background:true,gridLine:true},planner:{background:'#f5f7ff',line:'#1769e0',radius:0}},
  'photo-story':{font:{title:'Pretendard',body:'Pretendard'},palette:['#6b5948','#aa9278','#d7c8b6','#faf7f2'],calendar:{monthTitleStyle:'number-stack',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:2,stroke:'#ffffff',strokeWidth:4},mini:{background:false,gridLine:false},planner:{background:'#f7f2eb',line:'#c7b8a6',radius:2}},
  'student-playful':{font:{title:'Nanum Gothic',body:'Noto Sans KR'},palette:['#13a58b','#ff795f','#6b7ce8','#fff6dd'],calendar:{monthTitleStyle:'number-only',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'detached-cards',eventStyle:'strong-bars'},frame:{borderRadius:8,stroke:'#ffffff',strokeWidth:4},mini:{background:true,gridLine:false},planner:{background:'#fff8e8',line:'#13a58b',radius:8}},
  'premium-minimal':{font:{title:'Playfair Display',body:'Noto Sans KR'},palette:['#262626','#9a8352','#d8d2c5','#fbfaf7'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'center',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:0,stroke:'#9a8352',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#fbfaf7',line:'#b8aa8d',radius:0}}
 });
 function styleText(item,preset){item.style={...(item.style||{}),fontFamily:item.role==='year'||String(item.role||'').includes('title')?preset.font.title:preset.font.body,color:preset.palette[0]}}
 function styleElement(item,preset){const type=String(item.type||''),role=String(item.role||'');if(type==='text'||type==='year-text'||role==='year'||role.includes('title')||role.includes('name')||role.includes('motto')||role.includes('contact'))styleText(item,preset);if(type==='image'||type==='image-frame'||role.includes('image')||role.includes('photo')||role.includes('building'))item.style={...(item.style||{}),...preset.frame};if(['mini-calendar','mini-calendar-prev','mini-calendar-next','month-date-strip'].includes(type))item.style={...(item.style||{}),...preset.mini,primary:preset.palette[0],weekdayColor:preset.palette[1],dateColor:preset.palette[0],sunday:'#d92d20',saturday:'#175cd3',lineColor:preset.palette[1]};if(type==='memo'||role.includes('planner')||role.includes('todo')||role.includes('goal'))item.style={...(item.style||{}),background:preset.planner.background,lineColor:preset.planner.line,borderRadius:preset.planner.radius,titleColor:preset.palette[0],fontFamily:preset.font.body}}
 function rhythmColors(preset,expression={}){const rhythm=expression.variationRhythm||'seasonal';if(rhythm==='uniform')return [preset.palette[0]];if(rhythm==='alternating')return preset.palette.slice(0,2);if(rhythm==='story'||rhythm==='color')return preset.palette.slice(0,3);return expression.seasonal==='low'?[preset.palette[0]]:expression.seasonal==='high'?preset.palette.slice(0,3):preset.palette.slice(0,2)}
 function apply(project,spec){const preset=presets[spec?.styleId]||presets.editorial;if(!project?.template||!project?.book)throw new Error('Template project is required');const expression=spec.expression||{};project.template.resources=project.template.resources||{};project.template.resources.colorTheme={...(project.template.resources.colorTheme||{}),primary:preset.palette[0],secondary:preset.palette[1],accent:preset.palette[1],background:preset.palette[3],line:preset.palette[2]};project.template.resources.fontTheme={...(project.template.resources.fontTheme||{}),title:preset.font.title,body:preset.font.body,calendar:preset.font.body,event:preset.font.body};project.template.masters=project.template.masters||{};project.template.masters.calendar=project.template.masters.calendar||{};project.template.masters.calendar.design={...(project.template.masters.calendar.design||{}),...preset.calendar,presetId:`ai-style-${spec.styleId}`};project.template.masters.calendar.calendarOverrides={...(project.template.masters.calendar.calendarOverrides||{}),...preset.calendar,lineColor:preset.palette[2]};const pageElements=Object.values(project.book.elementsByPage||{}),masterElements=Object.values(project.template.masterElements||{});[...pageElements,...masterElements].forEach(list=>(list||[]).forEach(item=>styleElement(item,preset)));const colors=rhythmColors(preset,expression);(project.book.monthlyStyleOverrides||[]).forEach((entry,index)=>{const color=colors[index%colors.length];entry.tokens={...(entry.tokens||{}),primary:color,accent:color,calendarHeader:color,plannerBackground:preset.planner.background,variationRhythm:expression.variationRhythm||'seasonal',variationStep:index}});const application={schemaVersion:SCHEMA_VERSION,version:VERSION,styleId:spec.styleId,presetId:`ai-style-${spec.styleId}`,calendar:{...preset.calendar},expression:{variationRhythm:expression.variationRhythm||'seasonal',decorationFamily:expression.decorationFamily||'seasonal',material:expression.material||'clean-digital'},monthlyColorCount:colors.length,styledPageElements:pageElements.reduce((sum,list)=>sum+(list?.length||0),0),styledMasterElements:masterElements.reduce((sum,list)=>sum+(list?.length||0),0),editable:true};project.template.settings=project.template.settings||{};project.template.settings.aiDesignObjectStyleApplication=application;return application}
 root.ACDLDesignObjectStylePresets=Object.freeze({VERSION,SCHEMA_VERSION,presets,rhythmColors,styleElement,apply});
})(typeof window!=='undefined'?window:globalThis);
