(function(root){
 const VERSION='ai-design-quality.v1@0.2.0',SAFE_MARGIN=3,MIN_DRAFT_DPI=144,REGENERABLE=new Set(['forbidden-text','duplicate-asset','visual-inconsistency']);
 const ROLE_BY_PAGE=Object.freeze({'cover-front':'cover','cover-back':'divider','poster-annual':'annual',annual:'annual','school-symbols':'divider','front-insert-front':'divider','front-insert-back':'divider','rear-insert-front':'divider','rear-insert-back':'divider','monthly-front':'month','monthly-back':'month-back','back-cover-front':'back-cover','back-cover-back':'back-cover'});
 function monthKey(page){return page?.monthKey||(page?.calendarYear&&page?.calendarMonth?`${page.calendarYear}-${String(page.calendarMonth).padStart(2,'0')}`:null)}
 function generatedRole(page){return ['school-symbols','divider','yearly-calendar'].includes(page?.semanticPageRole)?'divider':ROLE_BY_PAGE[page?.role]||null}
 function metadataFor(selected,page,role){return ['month','month-back'].includes(role)?selected?.monthlyAssets?.[monthKey(page)]?.metadata?.[role]||{}:selected?.assetMetadataByRole?.[role]||{}}
 function assetFor(selected,page,role){return ['month','month-back'].includes(role)?selected?.monthlyAssets?.[monthKey(page)]?.[role]||null:selected?.assetsByRole?.[role]||null}
 function frame(item){const value=item?.framePct||item;if(![value?.x,value?.y,value?.width,value?.height].every(Number.isFinite))return null;return {x:value.x,y:value.y,width:value.width,height:value.height}}
 function overlapRatio(a,b){const width=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)),height=Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));return width*height/Math.max(1,Math.min(a.width*a.height,b.width*b.height))}
 function dimensions(meta){if(Array.isArray(meta.size))return {width:Number(meta.size[0]),height:Number(meta.size[1])};const match=String(meta.size||'').match(/(\d+)\s*x\s*(\d+)/i);return match?{width:Number(match[1]),height:Number(match[2])}:null}
 function pageChecks(project,selected,page){
  const role=generatedRole(page),key=monthKey(page),elements=project?.book?.elementsByPage?.[page.id]||[],editable=elements.filter(item=>item.role!=='ai-design-background'),meta=metadataFor(selected,page,role),asset=assetFor(selected,page,role),issues=[],pageSize=project?.template?.calendarTypeSnapshot?.definition?.finishedSize||project?.productType?.pageSize||{},safeMm=Number(project?.template?.resources?.exportSettings?.safeMargin)||5,safeX=pageSize.width?safeMm/Number(pageSize.width)*100:SAFE_MARGIN,safeY=pageSize.height?safeMm/Number(pageSize.height)*100:SAFE_MARGIN;
  if(!asset)issues.push({code:'missing-asset',severity:'fail',regenerable:false});
  if(!editable.length)issues.push({code:'readability',severity:'fail',regenerable:false});
  const outside=editable.filter(item=>{const box=frame(item);return box&&(box.x<safeX||box.y<safeY||box.x+box.width>100-safeX||box.y+box.height>100-safeY)});
  if(outside.length)issues.push({code:'safe-area',severity:'fail',regenerable:false,elementIds:outside.map(item=>item.id)});
  const boxes=editable.map(item=>({item,box:frame(item)})).filter(item=>item.box);const collisions=[];
  for(let left=0;left<boxes.length;left+=1)for(let right=left+1;right<boxes.length;right+=1)if(overlapRatio(boxes[left].box,boxes[right].box)>.8)collisions.push([boxes[left].item.id,boxes[right].item.id]);
  if(collisions.length)issues.push({code:'collision',severity:'fail',regenerable:false,pairs:collisions});
  const forbidden=meta.qualityChecks?.forbiddenText||meta.quality?.forbiddenText;
  if(forbidden==='fail'||(meta.detectedForbiddenText||[]).length)issues.push({code:'forbidden-text',severity:'fail',regenerable:true,tokens:meta.detectedForbiddenText||[]});else if(forbidden==='review-required')issues.push({code:'forbidden-text-review',severity:'review',regenerable:false});
  const expectedStyle=selected?.key,actualStyle=meta.styleKey;if(expectedStyle&&actualStyle&&actualStyle!==expectedStyle)issues.push({code:'visual-inconsistency',severity:'fail',regenerable:true});
  const size=dimensions(meta),targetDpi=Number(project?.template?.resources?.exportSettings?.dpi)||300;if(size&&pageSize?.width&&pageSize?.height){const dpi=Math.min(size.width/(pageSize.width/25.4),size.height/(pageSize.height/25.4));if(dpi<MIN_DRAFT_DPI)issues.push({code:'effective-resolution',severity:'fail',regenerable:false,effectiveDpi:Math.round(dpi)});else if(dpi<targetDpi)issues.push({code:'print-resolution-review',severity:'review',regenerable:false,effectiveDpi:Math.round(dpi),targetDpi})}
  return {pageId:page.id,pageRole:page.role,generatedRole:role,monthKey:key,assetId:meta.id||null,sourceVersion:meta.promptVersion||null,sourceSize:meta.size||null,generationQuality:meta.quality||null,generationEvidence:meta.generationEvidence||null,hasAsset:Boolean(asset),status:issues.some(item=>item.severity==='fail')?'fail':issues.length?'review':'pass',issues};
 }
 function printInspection(pages,now){
  const issues=pages.flatMap(page=>(page.issues||[]).map(item=>({...item,pageId:page.pageId}))),byCode=codes=>issues.filter(item=>codes.includes(item.code)),criterion=(status,message,evidence={})=>({status,message,evidence:{pageCount:pages.length,...evidence}}),failed=(codes,message)=>{const matches=byCode(codes);return matches.length?criterion('failed',message,{affectedPageIds:[...new Set(matches.map(item=>item.pageId))],issueCodes:[...new Set(matches.map(item=>item.code))]}):null},reviewed=(codes,message)=>{const matches=byCode(codes);return matches.length?criterion('review',message,{affectedPageIds:[...new Set(matches.map(item=>item.pageId))],issueCodes:[...new Set(matches.map(item=>item.code))]}):null};
  const unidentified=pages.filter(page=>!page.pageId||!page.generatedRole||!page.assetId),identity=unidentified.length?criterion('failed',`${unidentified.length}개 이미지의 페이지·용도·자산 식별 정보가 부족합니다.`,{affectedPageIds:unidentified.map(page=>page.pageId).filter(Boolean)}):criterion('passed',`${pages.length}개 AI 원본의 페이지 용도와 자산을 식별했습니다.`),generationEvidence=pages.map(page=>page.generationEvidence).filter(Boolean),failedGeneration=pages.filter(page=>page.generationEvidence&&page.generationEvidence.status!=='passed'),missingGeneration=pages.filter(page=>!page.generationEvidence),generationStandard=failedGeneration.length?criterion('failed',`${failedGeneration.length}개 이미지가 인쇄용 생성 품질 계약 검증에 실패했습니다.`,{affectedPageIds:failedGeneration.map(page=>page.pageId),qualityContract:'ai-image-generation-quality.v1'}):missingGeneration.length?criterion('review',`${missingGeneration.length}개 이미지는 이전 생성물이라 인쇄용 생성 품질 증거가 없습니다. 다시 생성해야 합니다.`,{affectedPageIds:missingGeneration.map(page=>page.pageId),qualityContract:'ai-image-generation-quality.v1'}):criterion('passed',`${generationEvidence.length}개 이미지가 high 품질 생성 기준을 통과했습니다.`,{qualityContract:'ai-image-generation-quality.v1',qualities:[...new Set(pages.map(page=>page.generationQuality).filter(Boolean))],actualSizes:[...new Set(generationEvidence.map(item=>item.actualSize).filter(Boolean))]}),invalidFiles=pages.filter(page=>{const evidence=page.generationEvidence||{};return evidence.status==='passed'&&(String(evidence.outputFormat||'').toLowerCase()!=='webp'||Number(evidence.outputCompression)!==0||!(Number(evidence.byteLength)>0)||!evidence.actualSize)}),frameSuitability=invalidFiles.length?criterion('failed',`${invalidFiles.length}개 원본 파일의 WebP·무추가압축·파일 규격 증거가 올바르지 않습니다.`,{affectedPageIds:invalidFiles.map(page=>page.pageId)}):missingGeneration.length?criterion('review','이전 생성물은 원본 파일 규격과 손상 여부를 증명할 수 없습니다.') : criterion('passed',`${generationEvidence.length}개 원본의 WebP·무추가압축·파일 규격 증거를 확인했습니다.`),placementIntegrity=criterion('review','검토용 PDF의 원본·확대 화면에서 선명도와 색상 계조를 확인해야 합니다.'),visualArtifacts=failed(['duplicate-asset','visual-inconsistency'],'반복 이미지 또는 시각 일관성 실패가 있습니다.')||criterion('review','검토용 PDF에서 흐림·노이즈·반복 패턴·비정상 형상을 확인해야 합니다.'),contentLegibility=failed(['forbidden-text'],'AI 원본에 금지된 문자 또는 기능 요소가 감지되었습니다.')||criterion('review','원치 않는 문자·숫자·가짜 버튼·프레임이 생성되지 않았는지 확인해야 합니다.'),criteria={identity,generationStandard,frameSuitability,placementIntegrity,visualArtifacts,contentLegibility},states=Object.values(criteria).map(item=>item.status);
  return {schemaVersion:'ai-image-print-quality.v1@0.1.0',criteriaVersion:'ai-image-print-quality.v1@0.1.0',status:states.includes('failed')?'failed':states.every(state=>state==='passed')?'passed':'pending',checkedAt:now,criteria};
 }
 function createReport(project,selected,now=new Date().toISOString()){
  const pages=(project?.book?.pageInstances||[]).filter(page=>generatedRole(page)).map(page=>pageChecks(project,selected,page)),seen=new Map();
  pages.forEach(page=>{const asset=assetFor(selected,page,page.generatedRole);if(!asset)return;const prior=seen.get(asset);if(prior&&prior.generatedRole===page.generatedRole&&prior.monthKey!==page.monthKey){page.issues.push({code:'duplicate-asset',severity:'fail',regenerable:true,duplicateOf:prior.pageId});page.status='fail'}else seen.set(asset,page)});
  const regenerationTargets=pages.flatMap(page=>page.issues.some(issue=>issue.severity==='fail'&&REGENERABLE.has(issue.code))?[{pageId:page.pageId,generatedRole:page.generatedRole,monthKey:page.monthKey,reasons:page.issues.filter(issue=>issue.severity==='fail'&&REGENERABLE.has(issue.code)).map(issue=>issue.code)}]:[]);
  const failedPages=pages.filter(page=>page.status==='fail'),reviewPages=pages.filter(page=>page.status==='review'),type=project?.template?.calendarTypeSnapshot?.definition;return {schemaVersion:VERSION,status:failedPages.length?'failed':reviewPages.length?'review-required':'passed',calendarTypeId:type?.id||project?.productType?.calendarTypeId||null,finishedSize:type?.finishedSize||project?.productType?.pageSize||null,pagePolicies:type?.policies||null,checks:['readability','collision','safe-area','forbidden-text','duplicate-asset','visual-inconsistency','effective-resolution'],pageCount:pages.length,passedPageCount:pages.filter(page=>page.status==='pass').length,failedPageCount:failedPages.length,reviewPageCount:reviewPages.length,failedRoles:[...new Set(failedPages.map(page=>page.generatedRole))],regenerationTargets,pages,printInspection:printInspection(pages,now),checkedAt:now};
 }
 root.ACDLDesignQuality=Object.freeze({VERSION,SAFE_MARGIN,MIN_DRAFT_DPI,ROLE_BY_PAGE,monthKey,generatedRole,pageChecks,printInspection,createReport});
})(typeof window==='undefined'?globalThis:window);
