(function(root){
 const VERSION='0.2.0',SCHEMA_VERSION='ai-design-object-style-application.v1';
 const presets=Object.freeze({
  editorial:{font:{title:'Noto Serif KR',body:'Noto Sans KR'},palette:['#24466f','#6885a8','#e9eef4','#ffffff'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:1,stroke:'#ffffff',strokeWidth:2},mini:{background:false,gridLine:false},planner:{background:'#f5f7fa',line:'#cbd5e1',radius:2}},
  'seasonal-watercolor':{font:{title:'Nanum Myeongjo',body:'Noto Sans KR'},palette:['#47866b','#d88772','#8e77a8','#f7f1e7'],calendar:{monthTitleStyle:'number-stack',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:4,stroke:'#ffffff',strokeWidth:3},mini:{background:true,gridLine:false},planner:{background:'#f4f1e9',line:'#b8cdbf',radius:5}},
  geometry:{font:{title:'Arial',body:'Noto Sans KR'},palette:['#1769e0','#ff5a47','#ffc928','#f5f7ff'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'detached-cards',eventStyle:'strong-bars'},frame:{borderRadius:0,stroke:'#1769e0',strokeWidth:2},mini:{background:true,gridLine:true},planner:{background:'#f5f7ff',line:'#1769e0',radius:0}},
  'photo-story':{font:{title:'Pretendard',body:'Pretendard'},palette:['#6b5948','#aa9278','#d7c8b6','#faf7f2'],calendar:{monthTitleStyle:'number-stack',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:2,stroke:'#ffffff',strokeWidth:4},mini:{background:false,gridLine:false},planner:{background:'#f7f2eb',line:'#c7b8a6',radius:2}},
  'student-playful':{font:{title:'Nanum Gothic',body:'Noto Sans KR'},palette:['#13a58b','#ff795f','#6b7ce8','#fff6dd'],calendar:{monthTitleStyle:'number-only',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'detached-cards',eventStyle:'strong-bars'},frame:{borderRadius:8,stroke:'#ffffff',strokeWidth:4},mini:{background:true,gridLine:false},planner:{background:'#fff8e8',line:'#13a58b',radius:8}},
  'premium-minimal':{font:{title:'Playfair Display',body:'Noto Sans KR'},palette:['#262626','#9a8352','#d8d2c5','#fbfaf7'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'center',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:0,stroke:'#9a8352',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#fbfaf7',line:'#b8aa8d',radius:0}},
  'warm-neutral-mocha':{font:{title:'Noto Serif KR',body:'Noto Sans KR'},palette:['#6f5142','#a88772','#cbb9aa','#f4eee7'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:2,stroke:'#cbb9aa',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#f4eee7',line:'#cbb9aa',radius:2}},
  'modern-sage-eco':{font:{title:'Pretendard',body:'Noto Sans KR'},palette:['#526b5d','#9eab96','#c9c0aa','#f3efe6'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:3,stroke:'#9eab96',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#f3efe6',line:'#9eab96',radius:3}},
  'soft-pastel-watercolor':{font:{title:'Nanum Myeongjo',body:'Noto Sans KR'},palette:['#8b6672','#c9d9ec','#c9dfda','#fbf7f4'],calendar:{monthTitleStyle:'number-stack',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:5,stroke:'#ffffff',strokeWidth:3},mini:{background:true,gridLine:false},planner:{background:'#fbf7f4',line:'#c9dfda',radius:5}},
  'clear-ui-line':{font:{title:'Pretendard',body:'Pretendard'},palette:['#33465b','#7c8b99','#aeb9c4','#f4f5f5'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'minimal',eventStyle:'strong-bars'},frame:{borderRadius:2,stroke:'#aeb9c4',strokeWidth:1},mini:{background:false,gridLine:true},planner:{background:'#f4f5f5',line:'#aeb9c4',radius:2}},
  'traditional-hanji-tone':{font:{title:'Nanum Myeongjo',body:'Noto Sans KR'},palette:['#69735f','#a56e5d','#c8b590','#f0e6d2'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'center',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars'},frame:{borderRadius:0,stroke:'#c8b590',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#f0e6d2',line:'#c8b590',radius:0}},
  'trendy-mesh-aura':{font:{title:'Pretendard',body:'Pretendard'},palette:['#8a769d','#d69f83','#d7c873','#fbf9f3'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'open-rows',eventStyle:'soft-bars'},frame:{borderRadius:5,stroke:'#ffffff',strokeWidth:2},mini:{background:true,gridLine:false},planner:{background:'#fbf9f3',line:'#d9d4ea',radius:5}}
  ,'editorial-graphic':{font:{title:'Pretendard',body:'Pretendard'},palette:['#1f3557','#de5b4f','#e8b84a','#f7f5ef'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'minimal',eventStyle:'strong-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:0,stroke:'#1f3557',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#f7f5ef',line:'#9aa7b7',radius:0}},
  'campus-documentary':{font:{title:'Pretendard',body:'Pretendard'},palette:['#244b62','#d6a34a','#bf584c','#f5f6f3'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:1,stroke:'#ffffff',strokeWidth:3},mini:{background:false,gridLine:false},planner:{background:'#f5f6f3',line:'#aeb9bf',radius:1}},
  'modular-color-system':{font:{title:'Pretendard',body:'Pretendard'},palette:['#2458a6','#e55445','#e5b72f','#f6f7f3'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'filled-tabs',gridStyle:'open-rows',eventStyle:'strong-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:0,stroke:'#2458a6',strokeWidth:1},mini:{background:false,gridLine:true},planner:{background:'#f6f7f3',line:'#95a5bc',radius:0}},
  'contemporary-illustration':{font:{title:'Pretendard',body:'Noto Sans KR'},palette:['#3678b8','#e96b55','#e6b94d','#f7f4ea'],calendar:{monthTitleStyle:'number-only',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:3,stroke:'#ffffff',strokeWidth:2},mini:{background:false,gridLine:false},planner:{background:'#f7f4ea',line:'#b8c5ce',radius:3}},
  'digital-aura-motion':{font:{title:'Pretendard',body:'Pretendard'},palette:['#596bd6','#78c9d2','#f0a36b','#f6f7fb'],calendar:{monthTitleStyle:'english-month',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'minimal',eventStyle:'soft-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:4,stroke:'#ffffff',strokeWidth:2},mini:{background:false,gridLine:false},planner:{background:'#f6f7fb',line:'#b9c1df',radius:4}},
  'korean-modern-graphic':{font:{title:'Pretendard',body:'Noto Sans KR'},palette:['#24505b','#c8574e','#d6a33e','#f5f2ea'],calendar:{monthTitleStyle:'number-inline',monthTitleAlign:'left',weekdayStyle:'outlined-pills',gridStyle:'open-rows',eventStyle:'soft-bars',background:false,gridBackground:'transparent'},frame:{borderRadius:0,stroke:'#24505b',strokeWidth:1},mini:{background:false,gridLine:false},planner:{background:'#f5f2ea',line:'#a8b3ac',radius:0}}
 });
 function styleText(item,preset){item.style={...(item.style||{}),fontFamily:item.role==='year'||String(item.role||'').includes('title')?preset.font.title:preset.font.body,color:preset.palette[0]}}
 function styleElement(item,preset){const type=String(item.type||''),role=String(item.role||'');if(type==='text'||type==='year-text'||role==='year'||role.includes('title')||role.includes('name')||role.includes('motto')||role.includes('contact'))styleText(item,preset);if(type==='image'||type==='image-frame'||role.includes('image')||role.includes('photo')||role.includes('building'))item.style={...(item.style||{}),...preset.frame};if(['mini-calendar','mini-calendar-prev','mini-calendar-next','month-date-strip'].includes(type))item.style={...(item.style||{}),...preset.mini,primary:preset.palette[0],weekdayColor:preset.palette[1],dateColor:preset.palette[0],sunday:'#d92d20',saturday:'#175cd3',lineColor:preset.palette[1]};if(type==='memo'||role.includes('planner')||role.includes('todo')||role.includes('goal'))item.style={...(item.style||{}),background:preset.planner.background,lineColor:preset.planner.line,borderRadius:preset.planner.radius,titleColor:preset.palette[0],fontFamily:preset.font.body}}
 function rhythmColors(preset,expression={}){const mode=expression.monthFrontMode||'color-accent';if(mode==='quarterly-theme')return preset.palette.slice(0,4);if(mode==='alternating-accent')return preset.palette.slice(0,2);return preset.palette.slice(0,3)}
 function apply(project,spec){const preset=presets[spec?.styleId]||presets.editorial;if(!project?.template||!project?.book)throw new Error('Template project is required');const expression=spec.expression||{};project.template.resources=project.template.resources||{};project.template.resources.colorTheme={...(project.template.resources.colorTheme||{}),primary:preset.palette[0],secondary:preset.palette[1],accent:preset.palette[1],background:preset.palette[3],line:preset.palette[2]};project.template.resources.fontTheme={...(project.template.resources.fontTheme||{}),title:preset.font.title,body:preset.font.body,calendar:preset.font.body,event:preset.font.body};project.template.masters=project.template.masters||{};project.template.masters.calendar=project.template.masters.calendar||{};project.template.masters.calendar.design={...(project.template.masters.calendar.design||{}),...preset.calendar,presetId:`ai-style-${spec.styleId}`};project.template.masters.calendar.calendarOverrides={...(project.template.masters.calendar.calendarOverrides||{}),...preset.calendar,lineColor:preset.palette[2]};const pageElements=Object.values(project.book.elementsByPage||{}),masterElements=Object.values(project.template.masterElements||{});[...pageElements,...masterElements].forEach(list=>(list||[]).forEach(item=>styleElement(item,preset)));const colors=rhythmColors(preset,expression);(project.book.monthlyStyleOverrides||[]).forEach((entry,index)=>{const color=colors[index%colors.length];entry.tokens={...(entry.tokens||{}),primary:color,accent:color,calendarHeader:color,plannerBackground:preset.planner.background,monthFrontMode:expression.monthFrontMode||'color-accent',variationStep:index}});const application={schemaVersion:SCHEMA_VERSION,version:VERSION,styleId:spec.styleId,presetId:`ai-style-${spec.styleId}`,calendar:{...preset.calendar},expression:{monthFrontMode:expression.monthFrontMode||'color-accent',monthBackMode:expression.monthBackMode||'auto-match'},monthlyColorCount:colors.length,styledPageElements:pageElements.reduce((sum,list)=>sum+(list?.length||0),0),styledMasterElements:masterElements.reduce((sum,list)=>sum+(list?.length||0),0),editable:true};project.template.settings=project.template.settings||{};project.template.settings.aiDesignObjectStyleApplication=application;return application}
 root.ACDLDesignObjectStylePresets=Object.freeze({VERSION,SCHEMA_VERSION,presets,rhythmColors,styleElement,apply});
})(typeof window!=='undefined'?window:globalThis);
