import type { RenderNode, ResolvedDocument, ResolvedPage } from "../../template-runtime/dist/src/index.js";
const esc=(v:unknown)=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
const imageType=(type:string)=>type==="image"||type==="image-frame";
const calendarType=(type:string)=>["calendar","calendar-grid","mini-calendar","mini-calendar-prev","mini-calendar-next"].includes(type);
const imageSource=(payload:unknown)=>typeof payload==="string"?payload:payload&&typeof payload==="object"&&"asset" in payload&&typeof (payload as any).asset?.src==="string"?(payload as any).asset.src:undefined;
export class PublishingRenderer {
 toSvg(document:ResolvedDocument,pageId:string):string{const p=document.pages.find(x=>x.id===pageId);if(!p)throw new Error(`페이지를 찾을 수 없습니다: ${pageId}`);return this.page(p)}
 toSvgPages(document:ResolvedDocument):string[]{return document.pages.map(p=>this.page(p))}
 private page(p:ResolvedPage):string{const nodes=p.objects.filter(n=>n.visible).map(n=>this.node(n)).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${p.size.width} ${p.size.height}" width="${p.size.width}${p.size.unit}" height="${p.size.height}${p.size.unit}"><rect width="100%" height="100%" fill="${esc(p.background.fill??"white")}"/>${nodes}</svg>`}
 private calendar(n:RenderNode,t:string):string{const f=n.frame,p=(n.payload&&typeof n.payload==="object"?n.payload:{}) as any,rows=Number(p.rows)||6,cw=f.width/7,ch=f.height/(rows+1),labels=p.weekStart==="monday"?["월","화","수","목","금","토","일"]:["일","월","화","수","목","금","토"];const heads=labels.map((label:string,i:number)=>`<text x="${(i+.5)*cw}" y="${ch*.7}" text-anchor="middle" font-size="${Math.max(2,ch*.35)}">${label}</text>`).join("");const cells=(p.cells||[]).map((cell:any)=>`<g opacity="${cell.inMonth?1:.35}"><rect x="${cell.column*cw}" y="${(cell.row+1)*ch}" width="${cw}" height="${ch}" fill="none" stroke="${esc(n.style.lineColor??"#cbd5e1")}" stroke-width=".2"/><text x="${(cell.column+.5)*cw}" y="${(cell.row+1.65)*ch}" text-anchor="middle" font-size="${Math.max(2,ch*.32)}">${cell.day}</text></g>`).join("");return `<g transform="${t}" opacity="${n.opacity}">${heads}${cells}</g>`}
 private dateStrip(n:RenderNode,t:string):string{const f=n.frame,p=(n.payload&&typeof n.payload==="object"?n.payload:{}) as any,days=p.days||[],cw=f.width/Math.max(1,days.length),labels=["일","월","화","수","목","금","토"];return `<g transform="${t}" opacity="${n.opacity}">${days.map((item:any,i:number)=>`<rect x="${i*cw}" width="${cw}" height="${f.height}" fill="none" stroke="${esc(n.style.lineColor??"#cbd5e1")}" stroke-width=".15"/><text x="${(i+.5)*cw}" y="${f.height*.38}" text-anchor="middle" font-size="${Math.max(1.4,f.height*.22)}">${labels[item.weekday]}</text><text x="${(i+.5)*cw}" y="${f.height*.78}" text-anchor="middle" font-size="${Math.max(1.5,f.height*.28)}">${item.day}</text>`).join("")}</g>`}
 private memo(n:RenderNode,t:string):string{const f=n.frame,p=(n.payload&&typeof n.payload==="object"?n.payload:{}) as any,count=Number(p.layout==="checklist"?p.itemCount:p.layout==="weekly"?p.weekCount:p.lineCount)||5,row=(f.height-6)/count;return `<g transform="${t}" opacity="${n.opacity}"><text x="1" y="4" font-size="3.5" font-weight="bold">${esc(p.title||"MEMO")}</text>${Array.from({length:count},(_,i)=>`<line x1="1" x2="${f.width-1}" y1="${6+(i+1)*row}" y2="${6+(i+1)*row}" stroke="${esc(n.style.lineColor??"#cbd5e1")}" stroke-width=".25"/>`).join("")}</g>`}
 private node(n:RenderNode):string{const f=n.frame,t=`translate(${f.x} ${f.y}) rotate(${n.rotation} ${f.width/2} ${f.height/2})`,opacity=n.opacity,src=imageType(n.type)?imageSource(n.payload):undefined;if(n.type==="text")return `<text transform="${t}" opacity="${opacity}" x="0" y="${Number(n.style.fontSize??12)}" font-size="${Number(n.style.fontSize??12)}" font-family="${esc(n.style.fontFamily??"sans-serif")}">${esc(n.payload)}</text>`;if(src)return `<image transform="${t}" opacity="${opacity}" href="${esc(src)}" width="${f.width}" height="${f.height}" preserveAspectRatio="xMidYMid slice"/>`;if(calendarType(n.type))return this.calendar(n,t);if(n.type==="month-date-strip")return this.dateStrip(n,t);if(n.type==="memo")return this.memo(n,t);return `<rect transform="${t}" opacity="${opacity}" width="${f.width}" height="${f.height}" fill="${esc(n.style.fill??"none")}" stroke="${esc(n.style.stroke??"none")}"/>`}
}
