import type { RenderNode, ResolvedDocument } from "../../template-runtime/dist/src/index.js";
export interface ScreenNode { id:string; type:string; style:Record<string,string>; text?:string; src?:string; payload?:unknown; }
const imageType=(type:string)=>type==="image"||type==="image-frame";
const calendarType=(type:string)=>["calendar","calendar-grid","mini-calendar","mini-calendar-prev","mini-calendar-next"].includes(type);
const imageSource=(payload:unknown)=>typeof payload==="string"?payload:payload&&typeof payload==="object"&&"asset" in payload&&typeof (payload as any).asset?.src==="string"?(payload as any).asset.src:undefined;
export class ScreenRenderer {
 renderModel(document:ResolvedDocument,pageId:string):ScreenNode[]{const page=document.pages.find(p=>p.id===pageId);if(!page)return[];return page.objects.filter(o=>o.visible).map(o=>this.node(o,page.size.width,page.size.height))}
 private node(o:RenderNode,w:number,h:number):ScreenNode{const s=o.style;return{id:o.id,type:o.type,style:{position:"absolute",left:`${o.frame.x/w*100}%`,top:`${o.frame.y/h*100}%`,width:`${o.frame.width/w*100}%`,height:`${o.frame.height/h*100}%`,zIndex:String(o.zIndex),opacity:String(o.opacity),transform:`rotate(${o.rotation}deg)`,overflow:String(s.overflow??"hidden"),fontSize:s.fontSize?`${s.fontSize}px`:"",fontFamily:String(s.fontFamily??"inherit"),fontWeight:String(s.fontWeight??"normal"),textAlign:String(s.textAlign??"left"),objectFit:String(s.objectFit??"cover")},text:o.type==="text"&&typeof o.payload==="string"?o.payload:undefined,src:imageType(o.type)?imageSource(o.payload):undefined,payload:o.payload}}
 private calendar(el:HTMLElement,payload:unknown):void{const p=(payload&&typeof payload==="object"?payload:{}) as any;el.style.display="grid";el.style.gridTemplateColumns="repeat(7,minmax(0,1fr))";el.style.gridTemplateRows=`auto repeat(${Number(p.rows)||6},minmax(0,1fr))`;el.style.fontSize="clamp(7px,1.5vw,12px)";for(const label of (p.weekStart==="monday"?["월","화","수","목","금","토","일"]:["일","월","화","수","목","금","토"])){const head=document.createElement("b");head.textContent=label;head.style.textAlign="center";el.appendChild(head)}for(const cell of p.cells||[]){const day=document.createElement("span");day.textContent=String(cell.day);day.style.cssText="display:grid;place-items:center;border-top:1px solid currentColor;opacity:"+(cell.inMonth?"1":".35");el.appendChild(day)}}
 private dateStrip(el:HTMLElement,payload:unknown):void{const p=(payload&&typeof payload==="object"?payload:{}) as any,labels=["일","월","화","수","목","금","토"];el.style.display="grid";el.style.gridTemplateColumns=`repeat(${p.days?.length||1},minmax(0,1fr))`;for(const item of p.days||[]){const day=document.createElement("span");day.style.cssText="display:grid;grid-template-rows:1fr 1fr;text-align:center;align-items:center;border-right:1px solid currentColor";day.innerHTML=`<small>${labels[item.weekday]}</small><b>${item.day}</b>`;el.appendChild(day)}}
 private memo(el:HTMLElement,payload:unknown):void{const p=(payload&&typeof payload==="object"?payload:{}) as any;const title=document.createElement("strong");title.textContent=String(p.title||"MEMO");el.appendChild(title);const count=Number(p.layout==="checklist"?p.itemCount:p.layout==="weekly"?p.weekCount:p.lineCount)||5;for(let i=0;i<count;i++){const line=document.createElement("div");line.style.cssText="height:calc((100% - 1.5em)/"+count+");border-bottom:1px solid currentColor";if(p.layout==="checklist")line.textContent="□";else if(p.layout==="weekly")line.textContent=`${i+1}주`;el.appendChild(line)}}
 mount(container:HTMLElement,doc:ResolvedDocument,pageId:string):void{container.innerHTML="";container.style.position="relative";for(const n of this.renderModel(doc,pageId)){const el=imageType(n.type)?globalThis.document.createElement("img"):globalThis.document.createElement("div");el.dataset.renderNodeId=n.id;Object.assign(el.style,n.style);if(n.src&&(el as HTMLImageElement).src!==undefined)(el as HTMLImageElement).src=n.src;if(n.text!==undefined)el.textContent=n.text;else if(calendarType(n.type))this.calendar(el,n.payload);else if(n.type==="month-date-strip")this.dateStrip(el,n.payload);else if(n.type==="memo")this.memo(el,n.payload);container.appendChild(el)}}
}
