import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';

await import('./native-print-authoring.js');
const authoring=globalThis.ACDLNativePrintAuthoring;
const project=()=>({productType:{pageSize:{width:260,height:180,unit:'mm'}},settings:{},template:{resources:{exportSettings:{bleed:3}},masterElements:{front:[{id:'title',type:'text',style:{color:'#17202e'}}]}},book:{elementsByPage:{page:[{id:'photo',type:'image-frame',replaceable:true},{id:'accent',type:'shape',style:{fill:'#ef3340'}},{id:'school',type:'semantic-object'}]}}});

test('new projects start with the physical native print authoring contract',()=>{const value=authoring.initializeProject(project());assert.deepEqual(value.template.nativePrintAuthoring.contract.trimSizeMm,{width:260,height:180});assert.deepEqual(value.template.nativePrintAuthoring.contract.productionSizeMm,{width:266,height:186});assert.equal(value.template.nativePrintAuthoring.contract.pdfStandard,'PDF/X-4');assert.equal(value.template.nativePrintAuthoring.contract.outputIntent,'Japan Color 2011 Coated');assert.deepEqual(value.template.resources.nativePrint.colors['#d92d20'],{space:'cmyk',c:0,m:.82,y:.72,k:.12});assert.equal(value.template.resources.nativePrint.fonts.body.sha256,'3ffbacde6ab8411f1d2db54bb9b1f0b3ee2a738932033722cf0388c06aed1c93');assert.equal(value.template.resources.nativePrint.fonts.body.packaged,false)});
test('new elements declare print meaning without inventing final CMYK assets',()=>{const value=authoring.initializeProject(project()),title=value.template.masterElements.front[0],photo=value.book.elementsByPage.page[0],accent=value.book.elementsByPage.page[1],semantic=value.book.elementsByPage.page[2];assert.equal(title.printIntent.text.mode,'outline');assert.equal(title.printIntent.paint.fill.blackMode,'k100');assert.equal(photo.printIntent.asset.requiredColorSpace,'cmyk');assert.equal(photo.printIntent.asset.approvalRequired,true);assert.equal(accent.printIntent.paint.fill.resolution,'pending-cmyk-authoring');assert.equal(semantic.printIntent.structure,'runtime-expansion-required');assert.equal(semantic.printIntent.directPdfMapping,false)});
test('existing projects are not silently promoted into the new print baseline',()=>{const value=project();authoring.syncProject(value);assert.equal(value.template.masterElements.front[0].printIntent,undefined);assert.equal(value.template.nativePrintAuthoring,undefined)});
test('style changes refresh print intent and explicit CMYK registration stays declarative',()=>{const value=authoring.initializeProject(project()),accent=value.book.elementsByPage.page[1];accent.style.fill='#123456';authoring.syncProject(value);assert.equal(accent.printIntent.paint.fill.source,'#123456');assert.equal(accent.printIntent.paint.fill.resolution,'pending-cmyk-authoring');authoring.registerCmykColor(value,'#123456',{space:'cmyk',c:.9,m:.7,y:.2,k:.1});assert.deepEqual(value.template.resources.nativePrint.colors['#123456'],{space:'cmyk',c:.9,m:.7,y:.2,k:.1})});
test('unverified CMYK input is rejected instead of being normalized silently',()=>{const value=authoring.initializeProject(project());assert.throws(()=>authoring.registerCmykColor(value,'#123456',{space:'cmyk',c:90,m:0,y:0,k:0}),/0~1 범위/)});
test('a four-component JPEG is eligible but never receives an invented output-condition approval',async()=>{const bytes=await readFile(new URL('../../templates/native-cmyk-image-layout/0.1.0/assets/images/proof-cmyk.jpg',import.meta.url)),file={type:'image/jpeg',arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)},result=await authoring.inspectPrintImageFile(file,'Japan Color 2011 Coated');assert.equal(result.eligible,true);assert.equal(result.approved,false);assert.equal(result.outputConditionIdentifier,null);assert.equal(result.proposedOutputConditionIdentifier,'Japan Color 2011 Coated')});
test('image output condition requires explicit editor approval and can be revoked',()=>{const source={eligible:true,components:4,mimeType:'image/jpeg',proposedOutputConditionIdentifier:'Japan Color 2011 Coated'};authoring.approvePrintImageSource(source,'Japan Color 2011 Coated');assert.equal(source.approved,true);assert.equal(source.outputConditionIdentifier,'Japan Color 2011 Coated');assert.equal(source.approvalBasis,'explicit-editor-confirmation');authoring.revokePrintImageSource(source);assert.equal(source.approved,false);assert.equal(source.outputConditionIdentifier,null);assert.equal(source.approvalBasis,undefined);assert.throws(()=>authoring.approvePrintImageSource({...source,eligible:false},'Japan Color 2011 Coated'),/4채널 CMYK JPEG/);assert.throws(()=>authoring.approvePrintImageSource({...source,eligible:true,proposedOutputConditionIdentifier:'Other'},'Japan Color 2011 Coated'),/일치하지 않습니다/)});
test('effective DPI follows physical frame, fit and zoom and blocks low-resolution approval',()=>{const element={width:40,height:40,image:{fit:'cover',scale:1},printSource:{width:1600,height:1200}},placement=authoring.inspectPrintImagePlacement(element,{width:260,height:180},300);assert.equal(placement.effectiveDpi,390.8);assert.equal(placement.status,'passed');element.image.scale=2;const zoomed=authoring.inspectPrintImagePlacement(element,{width:260,height:180},300);assert.equal(zoomed.effectiveDpi,195.4);assert.equal(zoomed.status,'blocked');const source={eligible:true,components:4,mimeType:'image/jpeg',proposedOutputConditionIdentifier:'Japan Color 2011 Coated'};assert.throws(()=>authoring.approvePrintImageSource(source,'Japan Color 2011 Coated',zoomed),/최소 300DPI/)});
