import assert from 'node:assert/strict';
import test from 'node:test';

globalThis.window=globalThis;
await import('./native-print-authoring.js');
await import('./native-print-package-compiler.js');
await import('./project-document.js');
await import('./native-print-full-template.js');
await import('./dataset-domain-bridge.js');
await import('./runtime-project-adapter.js');

const dependencies={sizePresets:{desk:[{id:'desk-260x180',label:'탁상형 260 × 180 mm',width:260,height:180}]},buildMonths:(year,startMonth)=>Array.from({length:12},(_,index)=>{const date=new Date(Date.UTC(year,startMonth-1+index,1));return {year:date.getUTCFullYear(),month:date.getUTCMonth()+1}})};
const create=()=>globalThis.ACDLNativePrintFullTemplate.create({year:2028,startMonth:3},dependencies);
const elementsFor=(project,page)=>[...(project.template.masterElements[page.masterId]||[]),...(project.book.elementsByPage[page.id]||[])];

test('new native baseline is generated as fifteen sheets and thirty ordered surfaces',()=>{const project=create(),roles=project.book.pageInstances.map(page=>page.role);assert.equal(project.book.sheets.length,15);assert.equal(project.book.pageInstances.length,30);assert.deepEqual(roles.slice(0,4),['cover-front','cover-back','front-insert-front','front-insert-back']);assert.deepEqual(roles.slice(4,28),Array.from({length:12},()=>['monthly-front','monthly-back']).flat());assert.deepEqual(roles.slice(28),['back-cover-front','back-cover-back']);assert.deepEqual(project.book.pageInstances.map(page=>page.number),Array.from({length:30},(_,index)=>index+1));assert.equal(project.template.pageComposition.pageCount,30);assert.equal(project.template.nativePrintAuthoring.origin,'new-template');assert.equal(project.template.standardIdentity,undefined)});

test('physical surface roles stay separate from the content placed on those surfaces',()=>{const project=create(),pages=project.book.pageInstances;assert.deepEqual(pages.slice(0,4).map(page=>[page.role,page.semanticPageRole]),[['cover-front','cover-front'],['cover-back','yearly-calendar'],['front-insert-front','school-symbols'],['front-insert-back','academic-schedule']]);assert.deepEqual(pages.slice(28).map(page=>[page.role,page.semanticPageRole]),[['back-cover-front','yearly-plan'],['back-cover-back','back-cover']]);assert.equal(pages.filter(page=>page.role==='monthly-front'&&page.semanticPageRole==='month-calendar').length,12);assert.equal(pages.filter(page=>page.role==='monthly-back'&&page.semanticPageRole==='month-back').length,12)});

test('all approved cover and cover-inside layouts materialize as editor-authored native objects',()=>{for(const coverType of ['center-photo','left-photo','right-photo','free']){const project=globalThis.ACDLNativePrintFullTemplate.create({year:2028,startMonth:3,coverType},dependencies),page=project.book.pageInstances.find(item=>item.role==='cover-front'),elements=elementsFor(project,page);assert.equal(project.template.settings.nativePageCompositions.cover.typeId,coverType);assert.ok(elements.some(item=>item.role==='year'));assert.ok(elements.some(item=>item.role==='school-name'));assert.equal(elements.some(item=>item.id==='cover.photo'),coverType!=='free');assert.equal(elements.some(item=>item.id==='cover.logo'),coverType==='free')}for(const annualType of ['open-grid','individual-month-boxes','vertical-three-month-groups','horizontal-four-month-groups']){const project=globalThis.ACDLNativePrintFullTemplate.create({year:2028,startMonth:3,annualType,annualLogo:true},dependencies),page=project.book.pageInstances.find(item=>item.role==='cover-back'),calendar=elementsFor(project,page).find(item=>item.type==='year-calendar');assert.equal(project.template.settings.nativePageCompositions.coverInside.typeId,annualType);assert.equal(calendar.yearlyLayoutType,annualType);assert.equal(calendar.columns,annualType==='horizontal-four-month-groups'?3:4);assert.ok(elementsFor(project,page).some(item=>item.id==='yearly.logo'))}});

test('every surface has editor-authored elements with bounded layout and print intent',()=>{const project=create(),empty=[],unbounded=[],missingIntent=[];for(const page of project.book.pageInstances){const elements=elementsFor(project,page);if(!elements.length)empty.push(page.id);for(const element of elements){if(![element.x,element.y,element.width,element.height].every(Number.isFinite)||element.x<0||element.y<0||element.x+element.width>100||element.y+element.height>100)unbounded.push(`${page.id}:${element.id}`);if(!element.printIntent)missingIntent.push(`${page.id}:${element.id}`)}}assert.deepEqual(empty,[]);assert.deepEqual(unbounded,[]);assert.deepEqual(missingIntent,[])});

test('full baseline covers representative and follow-up component families before print refinement',()=>{const project=create(),types=new Set(),roles=new Set();for(const page of project.book.pageInstances)for(const element of elementsFor(project,page)){types.add(element.type);roles.add(element.role)}for(const type of ['text','shape','image-frame','calendar-grid','mini-calendar-prev','mini-calendar-next','year-calendar','event-list','memo','month-date-strip'])assert.equal(types.has(type),true,`missing ${type}`);for(const role of ['cover-image','year-overview','current-calendar','weekday-sunday','weekday','weekday-saturday','monthly-image','academic-schedule','monthly-checklist','monthly-plan','school-logo','school-flower','year-academic-schedule'])assert.equal(roles.has(role),true,`missing ${role}`);const representatives={cover:project.book.pageInstances.find(page=>page.role==='cover-front'),yearly:project.book.pageInstances.find(page=>page.semanticPageRole==='yearly-calendar'),month:project.book.pageInstances.find(page=>page.role==='monthly-front')};assert.deepEqual(Object.fromEntries(Object.entries(representatives).map(([key,page])=>[key,elementsFor(project,page).length])),{cover:9,yearly:4,month:12});assert.equal(project.template.masterElements['master.monthly.front'].find(item=>item.id==='master.month.calendar').style.gridMode,'rows');assert.equal(elementsFor(project,project.book.pageInstances.find(page=>page.semanticPageRole==='yearly-plan')).filter(item=>item.role==='monthly-plan').length,12)});

test('all thirty surfaces preserve editor layout, style and bindings in Runtime',()=>{const project=create(),runtime=globalThis.ACDLRuntimeProjectAdapter.create().adapt(project).template;assert.equal(runtime.pages.length,30);for(const [index,page] of runtime.pages.entries()){const source=project.book.pageInstances[index],expected=elementsFor(project,source);assert.equal(page.sourcePageId,source.id);assert.equal(page.role,source.role);assert.equal(page.objects.length,expected.length);for(const object of page.objects){const element=expected.find(item=>item.id===object.sourceObjectId);assert.ok(element,`${page.id}:${object.sourceObjectId}`);assert.deepEqual(object.frame,{x:element.x/100*260,y:element.y/100*180,width:element.width/100*260,height:element.height/100*180});assert.equal(object.zIndex,Number(element.zIndex||0));const binding=element.binding||element.image?.binding;if(binding==='calendar.monthlyImages.current')assert.equal(object.binding,`monthlyImages.${source.calendarYear}-${String(source.calendarMonth).padStart(2,'0')}`);else if(binding==='calendar.events'&&element.displayMode==='month')assert.deepEqual({binding:object.binding,titles:object.value.map(item=>item.title)},{binding:undefined,titles:source.calendarMonth===3?['개학식']:source.calendarMonth===5?['체육대회']:source.calendarMonth===7||source.calendarMonth===8?['여름방학']:[]});else if(binding==='calendar.year')assert.deepEqual({binding:object.binding,value:object.value},{binding:undefined,value:project.settings.year});else if(binding==='calendar.currentMonth')assert.deepEqual({binding:object.binding,value:object.value},{binding:undefined,value:source.calendarMonth});else if(binding==='calendar.currentYear')assert.deepEqual({binding:object.binding,value:object.value},{binding:undefined,value:source.calendarYear});else if(binding)assert.equal(object.binding,binding)}}const cover=runtime.pages[0];assert.deepEqual(cover.objects.find(item=>item.id==='cover.accent').frame,{x:0,y:0,width:260,height:57.6});assert.equal(cover.objects.find(item=>item.id==='cover.year').style.color,'#ffffff');assert.equal(runtime.pages.filter(page=>page.role==='monthly-front').every(page=>{const calendar=page.objects.find(item=>item.type==='calendar-grid');return calendar&&calendar.value.year===page.metadata.calendarYear&&calendar.value.month===page.metadata.calendarMonth}),true)});
